Repository adeo/mozaic-design-system, pull requests merged in 2019-08, with the labels that each got.

#308 refactor(patterns/inputs): simplify docs and previews
  packages/styles/components/_c.checkbox.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/base.json
  packages/tokens/properties/color/button.json
  packages/tokens/properties/color/input.json
  packages/tokens/properties/color/link.json
  src/pages/Components/Checkbox/code.md
  src/pages/Components/Checkbox/index.md
  src/pages/Components/Checkbox/previews/checkbox-disabled-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-disabled-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-focus-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-focus-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-hover-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-hover-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-invalid-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-invalid-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-valid-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-valid-state.preview.scss
  src/pages/Components/Checkbox/previews/intro.preview.html
  src/pages/Components/Checkbox/previews/intro.preview.scss
  src/pages/Components/TextInput/code.md
  src/pages/Components/TextInput/index.md
Labels: docs, refactor, scope:pattern

#314 fix(ci): wait if an other deploy is pending
  .github/main.workflow
  ci/deploy.js
  ci/docker-wait/Dockerfile
  ci/docker-wait/entrypoint.sh
  package.json
Labels: fix, skill:build, status:await-core-team-review

#312 feat(pattern/aspectratios): add documentation
  packages/designer-kit/sketch-libraries/[AA] Aspect ratios.sketch
  src/pages/Foundations/AspectRatios/aspect-ratios--preview.png
  src/pages/Foundations/AspectRatios/aspect-ratios-sketch-menu.png
  src/pages/Foundations/AspectRatios/design.md
  src/pages/Foundations/AspectRatios/index.md
Labels: docs, feat, skill:design

#322 feat(pattern/textarea): add design doc
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  src/pages/Components/TextArea/design.md
  src/pages/Components/TextArea/index.md
  src/pages/Components/TextArea/textarea--sketch-menu.png
  src/pages/Components/TextArea/textarea-symbols.png
Labels: docs, feat, scope:styleguide, skill:design

#321 fix(tokens/color input): change color token for placeholer input
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/input.json
Labels: fix

#309 feat(pattern/textarea): create textarea pattern
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/styles/components/_c.textarea.scss
  src/pages/Components/TextArea/TextAreas-documentation.png
  src/pages/Components/TextArea/code.md
  src/pages/Components/TextArea/design.md
  src/pages/Components/TextArea/index.md
  src/pages/Components/TextArea/previews/TextArea.preview.html
  src/pages/Components/TextArea/previews/TextArea.preview.scss
  src/pages/Components/TextArea/specs.md
  src/pages/Components/TextArea/textarea--sketch-menu.png
  src/pages/Components/TextArea/textarea-symbols.png
Labels: feat, scope:pattern

#323 fix(logo/hp): add logo on HP and adapt heading part
  src/data/icons.json
  src/pages/index.js
  src/pages/index.scss
Labels: fix, refactor

#306 feat(pattern/select): create select form item
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/styles/components/_c.select.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.select.scss
  src/pages/Components/Select/Selects-documentation.png
  src/pages/Components/Select/code.md
  src/pages/Components/Select/design.md
  src/pages/Components/Select/index.md
  src/pages/Components/Select/previews/Select-all-states.preview.html
  src/pages/Components/Select/previews/Select-all-states.preview.scss
  src/pages/Components/Select/previews/Select-default.preview.html
  src/pages/Components/Select/previews/Select-default.preview.scss
  src/pages/Components/Select/previews/Selects.preview.html
  src/pages/Components/Select/previews/Selects.preview.scss
  src/pages/Components/Select/selects--sketch-menu.png
  src/pages/Components/Select/selects-symbols.png
  src/pages/Components/Select/specs.md
Labels: feat, scope:pattern

#327 feat(documentation): contributing documentation files structure
  src/pages/Contributing/Conventions/index.md
  src/pages/Contributing/GitConventions/index.md
  src/pages/Contributing/Glossary/index.md
  src/pages/Contributing/Help/index.md
  src/pages/Contributing/Philosophy/index.md
  src/pages/Contributing/ReportBug/index.md
  src/pages/Contributing/SubmitBugFix/index.md
  src/pages/Contributing/SubmitNewPattern/index.md
  src/pages/Contributing/SubmitPatternEnhancement/index.md
  src/pages/Contributing/SuggestNewPattern/index.md
  src/pages/Contributing/SuggestPatternEnhancement/index.md
  src/pages/Contributing/TechnicalDocumentation/index.md
  src/pages/Contributing/index.md
Labels: docs, scope:styleguide

#320 build(gatsby-source-preview): recompile only the changed file
  packages/gatsby-source-preview/create-fsmachine.js
  packages/gatsby-source-preview/functions.js
  packages/gatsby-source-preview/gatsby-node.js
  packages/gatsby-source-preview/node-model.js
Labels: fix, scope:styleguide

#331 fix(styleguide/version select): return the right styleguide version
  packages/gatsby-github-release/gatsby-node.js
Labels: fix, scope:styleguide

#333 Fix version patch
  .github/main.workflow
  .gitignore
  ci/deploy.js
  packages/gatsby-github-release/gatsby-node.js
  packages/gatsby-github-release/package.json
  src/data/icons.json
  yarn.lock
Labels: fix, scope:styleguide

#319 feat(pattern/toggle): add usage and design documentation
  src/pages/Components/Toggle/design.md
  src/pages/Components/Toggle/index.md
  src/pages/Components/Toggle/previews/toggle-states.preview.html
  src/pages/Components/Toggle/toggle-sketch-menu.png
Labels: feat, scope:pattern

#332 fix(devtools / commitlint): augment the commit header max length so w…
  commitlint.config.js
Labels: fix, scope:styleguide

#317 feat(pattern/toggle): create toggle form element
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.magic-unit.scss
  packages/styles/settings-tools/_s.toggle.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/toggle.json
  src/pages/Components/Buttons/previews/basic.preview.scss
  src/pages/Components/Toggle/Toggles-documentation.png
  src/pages/Components/Toggle/code.md
  src/pages/Components/Toggle/design.md
  src/pages/Components/Toggle/index.md
  src/pages/Components/Toggle/previews/Toggle.preview.html
  src/pages/Components/Toggle/previews/Toggle.preview.scss
  src/pages/Components/Toggle/previews/ToggleBase.preview.html
  src/pages/Components/Toggle/previews/ToggleBase.preview.scss
  src/pages/Components/Toggle/previews/ToggleExtendSizes.preview.html
  src/pages/Components/Toggle/previews/ToggleExtendSizes.preview.scss
  src/pages/Components/Toggle/previews/ToggleSizes.preview.html
  src/pages/Components/Toggle/previews/ToggleSizes.preview.scss
  src/pages/Components/Toggle/previews/ToggleStates.preview.html
  src/pages/Components/Toggle/previews/ToggleStates.preview.scss
  src/pages/Components/Toggle/previews/ToggleStatesLabel.preview.html
  src/pages/Components/Toggle/previews/ToggleStatesLabel.preview.scss
  src/pages/Components/Toggle/previews/toggle-states.preview.html
  src/pages/Components/Toggle/specs.md
  src/pages/Components/Toggle/toggle-sketch-menu.png
Labels: feat, scope:pattern

#336 test(build): launch pipeline
  .github/main.workflow
  ci/deploy.js
  packages/gatsby-github-release/gatsby-node.js
Labels: [ W I P ]

#330 feat(pages/contributing): add git convention to contributing
  src/pages/Components/index.md
  src/pages/Contributing/GitConventions/index.md
  src/pages/Contributing/InstallAndRun/index.md
  src/pages/Contributing/SubmitBugFix/index.md
  src/pages/Contributing/SubmitNewPattern/index.md
  src/pages/Contributing/SubmitPatternEnhancement/index.md
  src/pages/Contributing/SuggestNewPattern/index.md
  src/pages/Contributing/SuggestPatternEnhancement/index.md
  src/pages/Contributing/TechnicalDocumentation/index.md
  src/pages/Contributing/index.md
Labels: docs, scope:styleguide
