Repository adeo/mozaic-design-system, pull requests merged in 2019-09, with the labels that each got.

#342 feat(pattern/fileuploader): add usage, code, specs, and design doc
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/icons/Media_Upload_24px.svg
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.file-uploader.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/fileuploder.json
  src/data/icons.json
  src/icons/24px/Media_Upload_24px.svg
  src/pages/Components/FileUploader/FileUploader--Specs.png
  src/pages/Components/FileUploader/code.md
  src/pages/Components/FileUploader/design.md
  src/pages/Components/FileUploader/fileuploader-sketch-menu.png
  src/pages/Components/FileUploader/fileuploader-sketch-menu2.png
  src/pages/Components/FileUploader/index.md
  src/pages/Components/FileUploader/previews/file-uploader-accept.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-accept.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader-all-states.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-all-states.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader-multiple.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-multiple.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader-type-file.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-type-file.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader-with-file-delete.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-with-file-delete.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader-with-file.preview.html
  src/pages/Components/FileUploader/previews/file-uploader-with-file.preview.scss
  src/pages/Components/FileUploader/previews/file-uploader.preview.html
  src/pages/Components/FileUploader/previews/file-uploader.preview.scss
  src/pages/Components/FileUploader/specs.md
  static/icons/Media_Upload_24px.svg
Labels: feat, scope:pattern, skill:design, skill:dev

#349 refactor(pattern/buttons): refactoring sketch file
  packages/designer-kit/sketch-libraries/[BA] Buttons.sketch
Labels: refactor, skill:design

#350 feat(pattern/flags): add code and specs docs
  packages/styles/components/_c.flag.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.flags.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/flag.json
  src/pages/Components/Flags/Flags--Specs.png
  src/pages/Components/Flags/code.md
  src/pages/Components/Flags/previews/Flags.preview.html
  src/pages/Components/Flags/previews/Flags.preview.scss
  src/pages/Components/Flags/previews/flag-bordered.preview.html
  src/pages/Components/Flags/previews/flag-bordered.preview.scss
  src/pages/Components/Flags/previews/flag-default.preview.html
  src/pages/Components/Flags/previews/flag-default.preview.scss
  src/pages/Components/Flags/previews/flag-solid.preview.html
  src/pages/Components/Flags/previews/flag-solid.preview.scss
  src/pages/Components/Flags/specs.md
Labels: feat, scope:pattern, skill:dev

#351 feat(pattern/flags): add usage doc
  src/pages/Components/Flags/design.md
  src/pages/Components/Flags/flags--sketch-menu.png
  src/pages/Components/Flags/flags-symbols.png
  src/pages/Components/Flags/index.md
Labels: docs, feat, scope:pattern, skill:design

#359 fix(pattern/grids): fix typo in flexy class name
  .gitignore
  packages/styles/layouts/_l.flexy.scss
  src/pages/Foundations/Layout/Grid/previews/flexyCentered.preview.html
Labels: fix, scope:pattern

#348 feat(pattern/flags): add flags pattern
  packages/designer-kit/sketch-libraries/[BA] Flags.sketch
  packages/styles/components/_c.flag.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.flags.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/flag.json
  src/pages/Components/Flags/Flags--Specs.png
  src/pages/Components/Flags/Flags-Danger--Zoning.png
  src/pages/Components/Flags/Flags-DarkLight--Zoning.png
  src/pages/Components/Flags/Flags-Primary--Zoning.png
  src/pages/Components/Flags/Flags-PrimaryCampus--Zoning.png
  src/pages/Components/Flags/code.md
  src/pages/Components/Flags/design.md
  src/pages/Components/Flags/flags--sketch-menu.png
  src/pages/Components/Flags/flags-symbols.png
  src/pages/Components/Flags/index.md
  src/pages/Components/Flags/previews/flag-all.preview.html
  src/pages/Components/Flags/previews/flag-all.preview.scss
  src/pages/Components/Flags/previews/flag-basic.preview.html
  src/pages/Components/Flags/previews/flag-basic.preview.scss
  src/pages/Components/Flags/previews/flag-bordered.preview.html
  src/pages/Components/Flags/previews/flag-bordered.preview.scss
  src/pages/Components/Flags/previews/flag-default.preview.html
  src/pages/Components/Flags/previews/flag-default.preview.scss
  src/pages/Components/Flags/previews/flag-solid.preview.html
  src/pages/Components/Flags/previews/flag-solid.preview.scss
  src/pages/Components/Flags/specs.md
Labels: feat, scope:pattern, skill:design, skill:dev

#354 feat(website/dodRequestReview): definition of done request review Abstract
  src/pages/Contributing/Designers/definitionOfDoneReview/index.md
  src/pages/Contributing/Designers/definitionOfDoneReview/request-dod.png
  src/pages/Contributing/Designers/definitionOfDoneReview/up-to-date.png
  src/pages/Contributing/Designers/definitionOfDoneSymbols/index.md
  src/pages/Contributing/Designers/definitionOfDoneSymbols/overrides--dod.png
Labels: Getting Started Designers, docs, skill:design

#361 feat(onboard/glossary): add glossary
  src/pages/Contributing/Glossary/index.md
Labels: docs, feat

#363 feat(onboard/help): add need help page
  src/pages/Contributing/Help/index.md
Labels: docs, feat

#362 feat(onboard/design tokens): create docs about design tokens
  src/pages/Contributing/DesignTokens/index.md
Labels: docs, feat, scope:pattern

#364 feat(onboard/contributing install): create installation instructions …
  README.md
  src/pages/Contributing/Install/index.md
  src/pages/Contributing/InstallAndRun/index.md
Labels: docs, feat

#365 feat(onboard/css conventions): create docs about css conventions
  src/pages/Contributing/CSSConventions/Concept/index.md
  src/pages/Contributing/CSSConventions/DeclarationOrders/index.md
  src/pages/Contributing/CSSConventions/Formatting/index.md
  src/pages/Contributing/CSSConventions/Naming/index.md
  src/pages/Contributing/CSSConventions/index.md
Labels: docs, feat

#367 fix(onboard/contributing install): change paths to new repo name
  src/pages/Contributing/Install/index.md
Labels: fix, scope:onboard, skill:dev

#368 fix(onboard/css conventions): add images
  src/pages/Contributing/CSSConventions/Concept/ITCSS.jpg
  src/pages/Contributing/CSSConventions/Concept/blocks.png
  src/pages/Contributing/CSSConventions/Concept/elements.png
  src/pages/Contributing/CSSConventions/Concept/modifiers.png
Labels: fix, scope:onboard, skill:dev

#356 [WIP] feat(pattern/rating-stars): add code and specs docs
  packages/icons/Social_View_Star--Half_16px.svg
  packages/icons/Social_View_Star--Half_24px.svg
  packages/icons/Social_View_Star--Half_32px.svg
  packages/icons/Social_View_Star--Half_48px.svg
  packages/styles/components/_c.stars-input.scss
  packages/styles/components/_c.stars-result.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.hide.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.stars.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/star.json
  src/icons/16px/Social_View_Star--Half_16px.svg
  src/icons/24px/Social_View_Star--Half_24px.svg
  src/icons/32px/Social_View_Star--Half_32px.svg
  src/icons/48px/Social_View_Star--Half_48px.svg
  src/pages/Components/RatingStars/Ratings--Specs.png
  src/pages/Components/RatingStars/code.md
  src/pages/Components/RatingStars/previews/RatingStars.preview.html
  src/pages/Components/RatingStars/previews/stars-input-all-sizes.preview.html
  src/pages/Components/RatingStars/previews/stars-input-all-sizes.preview.scss
  src/pages/Components/RatingStars/previews/stars-input-basic.preview.html
  src/pages/Components/RatingStars/previews/stars-input-basic.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-all-sizes.preview.html
  src/pages/Components/RatingStars/previews/stars-result-all-sizes.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-all-states.preview.html
  src/pages/Components/RatingStars/previews/stars-result-all-states.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-basic.preview.html
  src/pages/Components/RatingStars/previews/stars-result-basic.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-size-l.preview.html
  src/pages/Components/RatingStars/previews/stars-result-size-l.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-size-m.preview.html
  src/pages/Components/RatingStars/previews/stars-result-size-m.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-size-s.preview.html
  src/pages/Components/RatingStars/previews/stars-result-size-s.preview.scss
  src/pages/Components/RatingStars/previews/stars-result-size-xl.preview.html
  src/pages/Components/RatingStars/previews/stars-result-size-xl.preview.scss
  src/pages/Components/RatingStars/specs.md
  static/icons/Social_View_Star--Half_16px.svg
  static/icons/Social_View_Star--Half_24px.svg
  static/icons/Social_View_Star--Half_32px.svg
  static/icons/Social_View_Star--Half_48px.svg
Labels: [ W I P ], feat, scope:pattern, skill:dev

#370 fix(chore/deployment): add gh token to aws lambda queries to fix depl…
  .github/main.workflow
Labels: fix, scope:chore, skill:dev

#371 fix(onboard/contributing): report updates of the contribution made on…
  README.md
  src/pages/Contributing/Conventions/index.md
  src/pages/Contributing/Install/index.md
Labels: fix, scope:onboard
