Repository adeo/mozaic-design-system, pull requests merged in 2019-07, with the labels that each got.

#291 fix(documentation): wrong import for typography and components
  src/pages/Foundations/Typography/BodyStyles/code.md
  src/pages/Foundations/Typography/HeadingStyles/code.md
  src/pages/Foundations/Typography/HeroStyles/code.md
  src/pages/GetStarted/Developers/npmScriptTutorial/index.md
Labels: docs, fix, status:await-core-team-review

#292 feat(patterns/inputs): add base64 postcss + state icon inputs
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  packages/styles/components/_c.text-input.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/pages/Components/TextInput/index.md
  yarn.lock
Labels: feat, scope:pattern, scope:styleguide

#290 feat(pattern/checkbox): add checkbox input component and documentation
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/styles/components/_c.checkbox.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s-checkbox.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/input.json
  src/data/icons.json
  src/pages/Components/Checkbox/checkboxes--sketch-menu.png
  src/pages/Components/Checkbox/code.md
  src/pages/Components/Checkbox/design.md
  src/pages/Components/Checkbox/index.md
  src/pages/Components/Checkbox/previews/checkbox-disabled-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-disabled-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-focus-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-focus-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-hover-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-hover-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-invalid-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-invalid-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-state.preview.scss
  src/pages/Components/Checkbox/previews/checkbox-valid-state.preview.html
  src/pages/Components/Checkbox/previews/checkbox-valid-state.preview.scss
  src/pages/Components/Checkbox/previews/intro.preview.html
  src/pages/Components/Checkbox/previews/intro.preview.scss
  src/pages/Components/Checkbox/specs.md
Labels: feat, scope:pattern, status:await-core-team-review

#300 fix(pattern/inputs): fix size and alignment of inputs
  packages/styles/components/_c.text-input.scss
Labels: fix, scope:pattern

#298 fix(tokens/font-scales): correct wrong values
  packages/tokens/build/ios/StyleDictionarySize.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/size/font.json
  src/pages/Foundations/Typography/ScaleAndSizes/index.md
Labels: fix, scope:pattern

#294 feat(pattern/inputs): add left icon support
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/styles/components/_c.left-icon-input.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/pages/Components/TextInput/Inputs-documentation.png
  src/pages/Components/TextInput/code.md
  src/pages/Components/TextInput/index.md
  src/pages/Components/TextInput/previews/left-icon-input.preview.html
  src/pages/Components/TextInput/previews/left-icon-input.preview.scss
Labels: feat, scope:pattern, status:await-core-team-review

#307 fix(patterns / designerkit): standardize sizes names using tee-shirt sizes
  packages/designer-kit/sketch-libraries/[AA] Fonts.sketch
  packages/designer-kit/sketch-libraries/[AA] Shadows.sketch
  packages/designer-kit/sketch-libraries/[BA] Bodies.sketch
  packages/designer-kit/sketch-libraries/[BA] Buttons.sketch
  packages/designer-kit/sketch-libraries/[BA] Headings.sketch
  packages/designer-kit/sketch-libraries/[BA] Heros.sketch
  packages/designer-kit/sketch-libraries/[BA] Links.sketch
Labels: refactor, skill:design
