Repository adeo/mozaic-design-system, pull requests merged in 2019-12, with the labels that each got.

#445 fix(onboard/design kit): use dynamic link to fix kit path
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  src/docs/GetStarted/Designers/installation/index.mdx
  src/docs/GetStarted/Designers/whatsIncluded/index.mdx
Labels: fix, scope:onboard, scope:website

#427 feat(tools/devmode): manage dev or production mode for scss
  packages/css-dev-tools/postcssPluginConfig.js
  packages/postcss-prepend/CHANGELOG.md
  packages/postcss-prepend/index.js
  packages/postcss-prepend/index.test.js
  packages/postcss-prepend/package.json
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.select.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/components/_c.textarea.scss
  packages/styles/dev-utils/_qdu.magic-unit-grid.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.links.scss
  packages/styles/settings-tools/_t.demo-state-class.scss
  src/docs/Foundations/MagicUnit/code.mdx
  src/docs/Foundations/MagicUnit/previews/mdu-magic-unit-grid.preview.html
  src/docs/Foundations/MagicUnit/previews/mdu-magic-unit-grid.preview.scss
Labels: feat, scope:tools, skill:dev

#447 feat(pattern/icons): add week 47 icons
  iconCompiler/index.js
  iconCompiler/reactIcon.js
  iconCompiler/svg-cleaner.js
  packages/icons/react/index.js
  packages/icons/svg/Media_ReduceScreen_16px.svg
  packages/icons/svg/Media_ReduceScreen_24px.svg
  packages/icons/svg/Media_ReduceScreen_32px.svg
  packages/icons/svg/Media_ReduceScreen_48px.svg
  packages/icons/svg/Media_Upload_24px.svg
  packages/icons/svg/Media_Upload_48px.svg
  packages/icons/svg/Product_Promise_Destocking_48px.svg
  packages/icons/svg/Service_Delivery_Delivery--Home_64px.svg
  packages/icons/svg/Service_Delivery_Delivery_Pickup--RelayPoint_64px.svg
  packages/icons/svg/Social_View_Star--First_16px.svg
  packages/icons/svg/Social_View_Star--First_24px.svg
  packages/icons/svg/Social_View_Star--First_48px.svg
  packages/icons/svg/Social_View_Star--Full_16px.svg
  packages/icons/svg/Social_View_Star--Full_24px.svg
  packages/icons/svg/Social_View_Star--Full_32px.svg
  packages/icons/svg/Social_View_Star--Full_48px.svg
  packages/icons/svg/Social_View_TesterView_24px.svg
  packages/icons/svg/Social_View_TesterView_48px.svg
  packages/icons/svg/Store_StoreLM_64px.svg
  packages/icons/svg/User_Card_LoyaltyCard_64px.svg
  packages/icons/svg/Various_Blower_32px.svg
  packages/icons/svg/Various_Blower_48px.svg
  packages/icons/svg/Various_Door_32px.svg
  packages/icons/svg/Various_Door_48px.svg
  packages/icons/svg/Various_Heat_32px.svg
  packages/icons/svg/Various_Pipe_32px.svg
  packages/icons/svg/Various_Pipe_48px.svg
  packages/icons/svg/Various_Shutter_32px.svg
  packages/icons/vue/index.vue
  src/icons/32px/Various_Blower_32px.svg
  src/icons/32px/Various_Door_32px.svg
  src/icons/32px/Various_Heat_32px.svg
  src/icons/32px/Various_Pipe_32px.svg
  src/icons/32px/Various_Shutter_32px.svg
  src/icons/48px/Various_Blower_48px.svg
  src/icons/48px/Various_Door_48px.svg
  src/icons/48px/Various_Pipe_48px.svg
Labels: feat, scope:chore, scope:pattern, skill:design, skill:dev

#446 feat(website/patterns status): redesign more readable pages for patte…
  package.json
  packages/gatsby-theme-styleguide/jest-preprocess.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternStatusFlagBox.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatusFlags.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/__snapshots__/patternStatus.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/patternStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/patternsstatusflags.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/__snapshots__/StatusFlag.test.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/index.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  packages/gatsby-theme-styleguide/src/utils/__tests__/status.js
  packages/gatsby-theme-styleguide/src/utils/status.js
  packages/icons/react/index.js
  src/pages/index.js
  yarn.lock
Labels: feat, scope:website, skill:design, skill:dev

#448 fix(getting-started/adeo preset): rename "preset adeo" into "adeo pre…
  src/docs/GetStarted/Developers/AdeoPreset/index.mdx
Labels: fix, scope:onboard, skill:dev

#449 fix(chore/test): new config for pre-commit and remove enzyme
  ci/jest.config.js
  iconCompiler/jest.config.js
  jest.config.base.js
  jest.config.js
  lint-staged.config.js
  package.json
  packages/gatsby-theme-styleguide/jest.config.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/setup-test-env.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Code/__tests__/Code.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Code/__tests__/__snapshots__/Code.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/Color/__tests__/Color.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Color/__tests__/__snapshots__/Color.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/patternStatus.basic.mock.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/patternStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewFrame.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/__tests__/__snapshots__/preview.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/__tests__/preview.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js
  packages/icons/react/index.js
  yarn.lock
Labels: fix, test

#452 fix(tools/css-dev-tools): add dotenv and @mozaic-ds/postcss-prepend
  packages/css-dev-tools/package.json
Labels: fix, scope:tools, skill:dev

#450 feat(pattern/input): add small input text
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Forms.sketch
  packages/styles/components/_c.left-icon-input.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.text-input.scss
  src/docs/Components/TextInput/code.mdx
  src/docs/Components/TextInput/index.mdx
  src/docs/Components/TextInput/inputs-documentation--medium.png
  src/docs/Components/TextInput/inputs-documentation--small.png
  src/docs/Components/TextInput/previews/input-sizes.preview.html
  src/docs/Components/TextInput/previews/input-sizes.preview.scss
  src/docs/Components/TextInput/previews/input-small-left-icon.preview.html
  src/docs/Components/TextInput/previews/input-small-left-icon.preview.scss
  src/docs/Components/TextInput/previews/input-small-state.preview.html
  src/docs/Components/TextInput/previews/input-small-state.preview.scss
  src/docs/Components/TextInput/specs.mdx
Labels: refactor, scope:pattern, skill:design, skill:dev

#451 feat(website/icons): Add new icon workflow documentation
  src/docs/Contributing/Designers/AddNewIcons/error--styleguide.png
  src/docs/Contributing/Designers/AddNewIcons/error--terminal.png
  src/docs/Contributing/Designers/AddNewIcons/index.mdx
Labels: feat, scope:website

#454 feat(chore/lint): add and configure stylelint mozaic plugin
  package.json
  packages/css-dev-tools/package.json
  packages/css-dev-tools/styleLintConfig.js
  packages/stylelint-plugin-mozaic/.gitignore
  packages/stylelint-plugin-mozaic/LICENSE
  packages/stylelint-plugin-mozaic/index.js
  packages/stylelint-plugin-mozaic/lib/checkCase.js
  packages/stylelint-plugin-mozaic/lib/getSelectors.js
  packages/stylelint-plugin-mozaic/lib/splitSelector.js
  packages/stylelint-plugin-mozaic/package-lock.json
  packages/stylelint-plugin-mozaic/package.json
  packages/stylelint-plugin-mozaic/test/index.js
  src/docs/GetStarted/Developers/Configuration/index.mdx
  src/docs/GetStarted/Developers/configureStylelint/index.mdx
  yarn.lock
Labels: feat, scope:chore

#459 fix(website: release selector): fix link to older versions
  packages/gatsby-github-release/gatsby-node.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuVersionSelect.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/__tests__/MenuVersionSelect.test.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/__tests__/__snapshots__/MenuVersionSelect.test.js.snap
  yarn.lock
Labels: fix, scope:website, skill:dev

#460 feat(patterns/status): set stable patterns status and prep bêta release
  package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  packages/gatsby-theme-styleguide/src/utils/status.js
  src/docs/Foundations/AspectRatios/index.mdx
  src/docs/Foundations/BorderRadius/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Layout/Container/index.mdx
  src/docs/Foundations/Layout/Grid/index.mdx
  src/docs/Foundations/Layout/MarginAndPaddings/index.mdx
  src/docs/Foundations/Layout/Responsive/index.mdx
  src/docs/Foundations/MagicUnit/index.mdx
  src/docs/Foundations/Shadows/index.mdx
  src/docs/Foundations/Strokes/index.mdx
  src/docs/Foundations/Typography/BodyStyles/index.mdx
  src/docs/Foundations/Typography/Colors/index.mdx
  src/docs/Foundations/Typography/FontFamilies/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeroStyles/index.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
Labels: feat, scope:pattern, scope:website, skill:design, skill:dev

#461 fix(website/previews): resize previews using availableWidth
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/Preview.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/__tests__/__snapshots__/preview.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/__tests__/preview.js
Labels: fix, scope:website, skill:dev

#458 feat(website/header): header redesign
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/__snapshots__/patternStatus.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/__snapshots__/StatusFlag.test.js.snap
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  yarn.lock
Labels: [ W I P ], feat, scope:website, skill:design, skill:dev

#463 refactor(website/dod): small refactor after designers feedback
  src/docs/Contributing/Designers/DesignToolsConventions/index.mdx
  src/docs/Contributing/Designers/DesignToolsConventions/up-to-date.png
Labels: refactor, scope:website, skill:design

#462 feat(pattern/icons): week 51 icons
  packages/icons/pdf-color/Store_Colors_RelayLocation_48px.pdf
  packages/icons/pdf-color/Store_Colors_RelayLocation_64px.pdf
  packages/icons/pdf-color/Store_Colors_StoreLocation_48px.pdf
  packages/icons/pdf-color/Store_Colors_StoreLocation_64px.pdf
  packages/icons/pdf/Media_View360_24px.pdf
  packages/icons/pdf/Media_View360_32px.pdf
  packages/icons/pdf/Media_View360_48px.pdf
  packages/icons/pdf/Media_View360_96px.pdf
  packages/icons/react/index.js
  packages/icons/svg-color/Store_Colors_RelayLocation_48px.svg
  packages/icons/svg-color/Store_Colors_RelayLocation_64px.svg
  packages/icons/svg-color/Store_Colors_StoreLocation_48px.svg
  packages/icons/svg-color/Store_Colors_StoreLocation_64px.svg
  packages/icons/svg/Store_Monochrome_RelayLocation_48px.svg
  packages/icons/svg/Store_Monochrome_RelayLocation_64px.svg
  packages/icons/svg/Store_Monochrome_StoreLocation_24px.svg
  packages/icons/svg/Store_Monochrome_StoreLocation_32px.svg
  packages/icons/svg/Store_Monochrome_StoreLocation_48px.svg
  packages/icons/svg/Store_Monochrome_StoreLocation_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/PDF/48px/Store_Colors_RelayLocation_48px.pdf
  src/icons/COLORS/PDF/48px/Store_Colors_StoreLocation_48px.pdf
  src/icons/COLORS/PDF/64px/Store_Colors_RelayLocation_64px.pdf
  src/icons/COLORS/PDF/64px/Store_Colors_StoreLocation_64px.pdf
  src/icons/COLORS/SVG/48px/Store_Colors_RelayLocation_48px.svg
  src/icons/COLORS/SVG/48px/Store_Colors_StoreLocation_48px.svg
  src/icons/COLORS/SVG/64px/Store_Colors_RelayLocation_64px.svg
  src/icons/COLORS/SVG/64px/Store_Colors_StoreLocation_64px.svg
  src/icons/PDF/24px/Media_View360_24px.pdf
  src/icons/PDF/32px/Media_View360_32px.pdf
  src/icons/PDF/48px/Media_View360_48px.pdf
  src/icons/PDF/96px/Media_View360_96px.pdf
  src/icons/SVG/24px/Store_Monochrome_StoreLocation_24px.svg
  src/icons/SVG/32px/Store_Monochrome_StoreLocation_32px.svg
  src/icons/SVG/48px/Store_Monochrome_RelayLocation_48px.svg
  src/icons/SVG/48px/Store_Monochrome_StoreLocation_48px.svg
  src/icons/SVG/64px/Store_Monochrome_RelayLocation_64px.svg
  src/icons/SVG/64px/Store_Monochrome_StoreLocation_64px.svg
  static/colorsvg/Store_Colors_RelayLocation_48px.svg
  static/colorsvg/Store_Colors_RelayLocation_64px.svg
  static/colorsvg/Store_Colors_StoreLocation_48px.svg
  static/colorsvg/Store_Colors_StoreLocation_64px.svg
Labels: feat, scope:pattern
