Repository adeo/mozaic-design-system, pull requests merged in 2019-10, with the labels that each got.

#373 feat(onboard/git conventions): add label and breaking changes informa…
  src/docs/Contributing/GitConventions/index.mdx
Labels: feat, scope:onboard

#366 fix(chore/pr template): update git conventions and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  src/docs/Contributing/GitConventions/index.mdx
Labels: fix, scope:chore

#374 fix(chore/npm publish): fix npm publish command (hopefuly)
  package.json
  yarn.lock
Labels: fix, scope:chore, skill:dev

#369 feat(patterns/rating stars): create rating stars component
  packages/designer-kit/sketch-libraries/[BA] Ratings.sketch
  packages/gatsby-theme-styleguide/package.json
  packages/icons/Social_View_Star--Half_16px.svg
  packages/icons/Social_View_Star--Half_24px.svg
  packages/icons/Social_View_Star--Half_32px.svg
  packages/icons/Social_View_Star--Half_48px.svg
  packages/styles/components/_c.stars-input.scss
  packages/styles/components/_c.stars-result.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.hide.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.stars.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/star.json
  src/docs/Components/RatingStars/Ratings--Specs.png
  src/docs/Components/RatingStars/code.mdx
  src/docs/Components/RatingStars/design.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/RatingStars/previews/stars-input-all-sizes.preview.html
  src/docs/Components/RatingStars/previews/stars-input-all-sizes.preview.scss
  src/docs/Components/RatingStars/previews/stars-input-basic.preview.html
  src/docs/Components/RatingStars/previews/stars-input-basic.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-all-sizes.preview.html
  src/docs/Components/RatingStars/previews/stars-result-all-sizes.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-all-states.preview.html
  src/docs/Components/RatingStars/previews/stars-result-all-states.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-basic.preview.html
  src/docs/Components/RatingStars/previews/stars-result-basic.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-size-l.preview.html
  src/docs/Components/RatingStars/previews/stars-result-size-l.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-size-m.preview.html
  src/docs/Components/RatingStars/previews/stars-result-size-m.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-size-s.preview.html
  src/docs/Components/RatingStars/previews/stars-result-size-s.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-size-xl.preview.html
  src/docs/Components/RatingStars/previews/stars-result-size-xl.preview.scss
  src/docs/Components/RatingStars/ratingStars--sketch-menu.png
  src/docs/Components/RatingStars/ratingStars-symbols.png
  src/docs/Components/RatingStars/specs.mdx
  src/docs/Contributing/Designers/overrides--dod.png
  src/icons/16px/Social_View_Star--Half_16px.svg
  src/icons/24px/Social_View_Star--Half_24px.svg
  src/icons/32px/Social_View_Star--Half_32px.svg
  src/icons/48px/Social_View_Star--Half_48px.svg
  static/icons/Social_View_Star--Half_16px.svg
  static/icons/Social_View_Star--Half_24px.svg
  static/icons/Social_View_Star--Half_32px.svg
  static/icons/Social_View_Star--Half_48px.svg
Labels: feat, scope:pattern

#372 feat(onboard/contributing): documentation - report a bug
  src/docs/Contributing/ReportBug/index.mdx
Labels: feat, scope:onboard

#375 fix(patterns/flags): fix flags issues
  src/docs/Components/Flags/code.mdx
  src/docs/Components/Flags/previews/flag-all.preview.scss
  src/docs/Components/Flags/previews/flag-basic.preview.scss
  src/docs/Components/Flags/previews/flag-bordered.preview.scss
  src/docs/Components/Flags/previews/flag-default.preview.scss
  src/docs/Components/Flags/previews/flag-solid.preview.scss
Labels: fix, scope:pattern, skill:dev

#376 fix(chore/releases): fix npm publish (hopefully again)
  package.json
Labels: fix, scope:chore, skill:dev

#352 refactor(foundations/breakpoints): proposition of new breakpoints for h…
  packages/styles/settings-tools/_s.screens.scss
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/size/screens.json
  src/data/icons.json
  src/docs/Foundations/Layout/Container/index.mdx
  src/docs/Foundations/Layout/Grid/code.mdx
  src/docs/Foundations/Layout/Responsive/code.mdx
  src/docs/Foundations/Layout/Responsive/index.mdx
  src/docs/Foundations/Layout/Responsive/previews/responsive.preview.html
  src/docs/Foundations/Layout/Responsive/previews/responsive.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/code.mdx
  src/docs/Foundations/Typography/HeroStyles/code.mdx
  src/docs/GetStarted/Developers/CssNamingConventions/index.mdx
Labels: BREAKING CHANGE, refactor, scope:pattern, skill:design, skill:dev

#379 fix(tools/github templates): update github templates for issues
  .github/ISSUE_TEMPLATE/1-styleguide-bug-report.md
  .github/ISSUE_TEMPLATE/2-styleguide-feature-request.md
  .github/ISSUE_TEMPLATE/3-pattern-addition-proposal.md
  .github/ISSUE_TEMPLATE/4-pattern-bug-report.md
  .github/ISSUE_TEMPLATE/5-pattern-enhancement-proposal.md
  .github/ISSUE_TEMPLATE/6-other.md
Labels: fix, scope:tools

#378 feat(website/toc): add table of contents
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/base.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  yarn.lock
Labels: feat, scope:website

#380 fix(chore/github action): migrate actions to yaml
  .github/actions/installAndBuild.yml
  .github/main.workflow
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: fix, scope:chore

#377 feat(onboard/newpattern): suggest and submit a new pattern
  plopfile.js
  src/docs/Contributing/NewPattern/AcceptanceCriterias/index.mdx
  src/docs/Contributing/NewPattern/SubmitNewPattern/index.mdx
  src/docs/Contributing/NewPattern/index.mdx
  src/docs/Contributing/SubmitNewPattern/index.mdx
  src/docs/Contributing/SuggestNewPattern/index.mdx
Labels: feat, scope:onboard

#381 feat(onboard/patternenhancement): suggest/submit a pattern enhancement
  src/docs/Contributing/PatternEnhancement/index.mdx
  src/docs/Contributing/SubmitPatternEnhancement/index.mdx
  src/docs/Contributing/SuggestPatternEnhancement/index.mdx
Labels: feat, scope:onboard

#384 feat(onboard/contrib): create contrib doc for bug fixes
  src/docs/Contributing/ReportBug/index.mdx
  src/docs/Contributing/SubmitBugFix/index.mdx
Labels: feat, scope:onboard

#385 fix(website/toc): fix layout and add some styles to the toc
  packages/gatsby-theme-styleguide/src/gatsby-components/Container/Container.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/base.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: fix, scope:website

#386 feat(onboard/css comments): add comments section
  src/docs/Contributing/CSSConventions/Comments/index.mdx
Labels: feat, scope:onboard

#387 fix(chore/deploy): remove unused job
  .github/workflows/release.yml
Labels: fix, scope:chore

#389 fix(website/layout): render better responsive layout
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: fix, scope:website

#388 fix(website/scss-syntax-highlight): fix scss syntax highlight
  packages/gatsby-theme-styleguide/gatsby-browser.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewCodeSample.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/base.scss
  packages/gatsby-theme-styleguide/static/css/prism-base2tone-morning-dark.css
  plop-templates/pattern/code.md.hbs
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Checkbox/code.mdx
  src/docs/Components/FileUploader/code.mdx
  src/docs/Components/Flags/code.mdx
  src/docs/Components/Links/code.mdx
  src/docs/Components/Notification/code.mdx
  src/docs/Components/Radio/code.mdx
  src/docs/Components/RatingStars/code.mdx
  src/docs/Components/Select/code.mdx
  src/docs/Components/Tag/code.mdx
  src/docs/Components/TextArea/code.mdx
  src/docs/Components/TextInput/code.mdx
  src/docs/Components/Toggle/code.mdx
  src/docs/Contributing/CSSConventions/Concept/index.mdx
  src/docs/Contributing/CSSConventions/DeclarationOrders/index.mdx
  src/docs/Contributing/CSSConventions/Formatting/index.mdx
  src/docs/Contributing/CSSConventions/Naming/index.mdx
  src/docs/Contributing/DesignTokens/index.mdx
  src/docs/Foundations/BorderRadius/code.mdx
  src/docs/Foundations/Layout/Container/code.mdx
  src/docs/Foundations/Layout/Grid/code.mdx
  src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
  src/docs/Foundations/Layout/Responsive/code.mdx
  src/docs/Foundations/MagicUnit/code.mdx
  src/docs/Foundations/Shadows/code.mdx
  src/docs/Foundations/Strokes/code.mdx
  src/docs/Foundations/Typography/BodyStyles/code.mdx
  src/docs/Foundations/Typography/Colors/code.mdx
  src/docs/Foundations/Typography/FontFamilies/code.mdx
  src/docs/Foundations/Typography/HeadingStyles/code.mdx
  src/docs/Foundations/Typography/HeroStyles/code.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/code.mdx
  src/docs/GetStarted/Developers/CssNamingConventions/index.mdx
  src/docs/GetStarted/Developers/importingMozaicComponents/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  src/docs/GetStarted/Developers/usingStaticAssets/index.mdx
Labels: fix, scope:website

#382 feat(onboard/namingconvention): Add naming convention
  src/data/icons.json
  src/docs/Contributing/Designers/NamingConvention/buttons--sketch-menu.png
  src/docs/Contributing/Designers/NamingConvention/hierarchy--importance.png
  src/docs/Contributing/Designers/NamingConvention/hierarchy--specific.png
  src/docs/Contributing/Designers/NamingConvention/icon-override.png
  src/docs/Contributing/Designers/NamingConvention/index.mdx
  src/docs/Contributing/Designers/NamingConvention/sizes-naming.png
  src/docs/Contributing/Designers/NamingConvention/text--label.png
  src/docs/Contributing/Designers/NamingConvention/texts-naming.png
  src/docs/Foundations/AspectRatios/design.mdx
  src/docs/Foundations/AspectRatios/index.mdx
  src/docs/GetStarted/Designers/namingConvention/buttons--sketch-menu.png
  src/docs/GetStarted/Designers/namingConvention/index.mdx
  src/docs/GetStarted/Designers/requirements/index.mdx
Labels: feat, scope:onboard, skill:design

#392 feat(onboard/contrib): create philosophy page
  src/docs/Contributing/Philosophy/index.mdx
Labels: feat, scope:onboard

#391 feat(onboard/postcss vuejs): postcss config for vue.js
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
Labels: feat, scope:onboard

#390 feat(website/feedback-module): add feedback module
  packages/gatsby-theme-styleguide/src/gatsby-components/Helmet/Helmet.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Helmet/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  src/pages/index.js
Labels: feat, scope:website

#394 fix(website): fixing some typos
  src/docs/Components/index.mdx
  src/docs/Contributing/Prerequisite/GitConventions/index.mdx
Labels: fix, scope:website

#396 fix(patterns/links): Fix a responsive bug on the links sketch file
  packages/designer-kit/sketch-libraries/[BA] Links.sketch
Labels: fix, skill:design

#399 feat(onboard/figma): add Figma design conventions
  src/docs/Contributing/Prerequisite/NamingConvention/index.mdx
  src/docs/Contributing/SubmitChanges/DesignToolsConventions/index.mdx
Labels: feat, scope:onboard, skill:design

#398 feat(tools/customization): handle config file, add production build s…
  package.json
  packages/configuration-manager/index.js
  packages/configuration-manager/package.json
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/package.json
  src/docs/GetStarted/Developers/Customization/index.mdx
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
  yarn.lock
Labels: feat, scope:tools

#406 refactor(chore/logs): delete console log everywhere they are not rele…
  ci/assets.js
  iconCompiler/generateIconsDatas.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  packages/tokens/config.js
Labels: refactor, scope:chore, skill:dev
