Repository adeo/mozaic-design-system, pull requests merged in 2019-11, with the labels that each got.

#405 refactor(website/filesystem listing): refactor filesystem listing
  packages/gatsby-source-directory-tree/CHANGELOG.md
  packages/gatsby-source-directory-tree/gatsby-node.js
  packages/gatsby-source-directory-tree/index.js
  packages/gatsby-source-directory-tree/package.json
  packages/gatsby-source-preview/gatsby-node.js
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/BuildMenuModel.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/tools.js
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
Labels: refactor, scope:website

#410 refactor(patterns/sketchfiles): bump sketch version to 59.1 and make required changes
  packages/designer-kit/sketch-libraries/[AA] Aspect ratios.sketch
  packages/designer-kit/sketch-libraries/[AA] Colors.sketch
  packages/designer-kit/sketch-libraries/[AA] Fonts.sketch
  packages/designer-kit/sketch-libraries/[AA] Icons.sketch
  packages/designer-kit/sketch-libraries/[AA] Shadows.sketch
  packages/designer-kit/sketch-libraries/[AA] Colors.sketch
  packages/designer-kit/sketch-libraries/[BA] Bodies.sketch
  packages/designer-kit/sketch-libraries/[BA] Buttons.sketch
  packages/designer-kit/sketch-libraries/[BA] Flags.sketch
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/designer-kit/sketch-libraries/[BA] Headings.sketch
  packages/designer-kit/sketch-libraries/[BA] Heros.sketch
  packages/designer-kit/sketch-libraries/[BA] Links.sketch
  packages/designer-kit/sketch-libraries/[BA] Ratings.sketch
  packages/designer-kit/sketch-libraries/[BA] Tags.sketch
  packages/designer-kit/sketch-libraries/[BA] Flags.sketch
  packages/designer-kit/sketch-libraries/[BB] Notifications.sketch
Labels: refactor, scope:pattern, skill:design

#407 refactor(tools/mqpacker): remove css-mqpacker and update postcss docs
  package.json
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
  yarn.lock
Labels: refactor, scope:tools, skill:dev

#408 feat(website/test): create separated html for each preview (and display it in previews iframe)
  gatsby-config.js
  packages/gatsby-theme-styleguide/gatsby-node.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/Preview.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewFrame.js
  packages/gatsby-theme-styleguide/src/templates/preview-page.js
Labels: feat, scope:website, test

#414 fix(chore/ci): rename sketch files with non ascii names
  packages/designer-kit/sketch-libraries/[AA] Colors.sketch
  packages/designer-kit/sketch-libraries/[BA] Flags.sketch
Labels: fix, scope:chore, skill:design, skill:dev

#409 fix(patterns/docs): fix list of documentation typos or inacurate values
  packages/icons/package.json
  packages/styles/typography/_t.heros.scss
  packages/web-fonts/package.json
  src/docs/Components/Flags/index.mdx
  src/docs/Contributing/Introduction/Philosophy/index.mdx
  src/docs/Contributing/Prerequisite/CSSConventions/index.mdx
  src/docs/Contributing/Prerequisite/DesignRequirements/index.mdx
  src/docs/Contributing/Prerequisite/GitConventions/index.mdx
  src/docs/Contributing/index.mdx
  src/docs/Foundations/Layout/Grid/previews/flexyResponsive.preview.html
  src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
  src/docs/Foundations/Shadows/index.mdx
  src/docs/Foundations/Typography/FontFamilies/previews/font-families.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeroStyles/code.mdx
  src/docs/Foundations/Typography/HeroStyles/design.mdx
  src/docs/Foundations/Typography/HeroStyles/index.mdx
  src/docs/GetStarted/Designers/aboutTheSystem/index.mdx
  src/docs/GetStarted/Designers/index.mdx
  src/docs/GetStarted/Designers/installation/index.mdx
  src/docs/GetStarted/Designers/whatsIncluded/index.mdx
  src/docs/GetStarted/Developers/CssNamingConventions/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
  src/docs/GetStarted/Developers/configureStylelint/index.mdx
  src/docs/GetStarted/Developers/importingMozaicComponents/index.mdx
  src/docs/GetStarted/Developers/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  src/docs/GetStarted/Developers/whatsincluded/index.mdx
  src/docs/GetStarted/index.mdx
Labels: fix, scope:onboard, scope:pattern, skill:design, skill:dev

#416 feat(onboard/getting started): add angular CLI support to postcss con…
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
Labels: feat, scope:onboard, skill:dev

#417 fix(website/codes blocks): allow blank lines, and fix lines splits wh…
  package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Code/Code.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Code/normalize.js
  packages/gatsby-theme-styleguide/src/gatsby-components/InlineCode/InlineCode.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: fix, scope:website, skill:dev

#395 feat(pattern/colors): refactor color system
  packages/designer-kit/sketch-libraries/[AA] Colors.sketch
  packages/designer-kit/sketch-libraries/[BA] Buttons.sketch
  packages/designer-kit/sketch-libraries/[BA] Forms.sketch
  packages/designer-kit/sketch-libraries/[BA] Links.sketch
  packages/designer-kit/sketch-libraries/[BB] Notifications.sketch
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/base.json
  packages/tokens/properties/color/button.json
  packages/tokens/properties/color/fileuploder.json
  packages/tokens/properties/color/flag.json
  packages/tokens/properties/color/font.json
  packages/tokens/properties/color/input.json
  packages/tokens/properties/color/link.json
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Buttons/design.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Buttons/previews/button-state.preview.html
  src/docs/Components/Buttons/previews/button-styles.preview.html
  src/docs/Components/Buttons/specs.mdx
  src/docs/Components/Flags/code.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Flags/previews/flag-all.preview.html
  src/docs/Components/Flags/previews/flag-bordered.preview.html
  src/docs/Components/Flags/previews/flag-solid.preview.html
  src/docs/Components/Flags/specs.mdx
  src/docs/Components/Links/code.mdx
  src/docs/Components/Links/previews/contextual-links.preview.html
  src/docs/Components/Links/previews/link-state.preview.html
  src/docs/Components/Links/previews/link-styles.preview.html
  src/docs/Components/Links/specs.mdx
  src/docs/Foundations/Colors/design.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Typography/Colors/code.mdx
  src/docs/Foundations/Typography/Colors/previews/font-colors.preview.html
Labels: feat, refactor, scope:pattern, skill:design, skill:dev

#413 feat(website/chapters): list pages and patterns in chapters landing pages
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/tools.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SubContents/SubContents.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SubContents/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SubContents/subcontents.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Checkbox/index.mdx
  src/docs/Components/FileUploader/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Radio/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Select/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/TextArea/index.mdx
  src/docs/Components/TextInput/index.mdx
  src/docs/Components/Toggle/index.mdx
  src/docs/Components/index.mdx
  src/docs/Contributing/Introduction/index.mdx
  src/docs/Contributing/Prerequisite/index.mdx
  src/docs/Contributing/SubmitChanges/index.mdx
  src/docs/Contributing/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Colors/thumbnail.png
  src/docs/Foundations/Layout/MarginAndPaddings/index.mdx
  src/docs/Foundations/Layout/index.mdx
  src/docs/Foundations/Layout/preview.png
  src/docs/Foundations/Typography/index.mdx
  src/docs/Foundations/index.mdx
  src/docs/GetStarted/Designers/index.mdx
  src/docs/GetStarted/Developers/index.mdx
  src/docs/GetStarted/index.mdx
Labels: feat, scope:website

#420 feat(website/patterns-status): add patterns status table and flags
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternStatusFlagBox.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatusFlags.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/patternsstatusflags.scss
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Checkbox/index.mdx
  src/docs/Components/FileUploader/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Radio/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Select/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/TextArea/index.mdx
  src/docs/Components/TextInput/index.mdx
  src/docs/Components/Toggle/index.mdx
  src/docs/Foundations/AspectRatios/index.mdx
  src/docs/Foundations/BorderRadius/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Layout/Container/index.mdx
  src/docs/Foundations/Layout/Grid/index.mdx
  src/docs/Foundations/Layout/MarginAndPaddings/index.mdx
  src/docs/Foundations/Layout/Responsive/index.mdx
  src/docs/Foundations/MagicUnit/index.mdx
  src/docs/Foundations/Shadows/index.mdx
  src/docs/Foundations/Strokes/index.mdx
  src/docs/Foundations/Typography/BodyStyles/index.mdx
  src/docs/Foundations/Typography/Colors/index.mdx
  src/docs/Foundations/Typography/FontFamilies/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeroStyles/index.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
  src/docs/PatternsStatus/index.mdx
Labels: feat, scope:website

#418 [WIP] feat(website/test): with a command i can generate snapshots for all previews (#199)
  package.json
  src/docs/Contributing/VisualTesting/applitools-API-key.gif
  src/docs/Contributing/VisualTesting/applitools-analyse-screenshots.png
  src/docs/Contributing/VisualTesting/applitools-how-it-works.png
  src/docs/Contributing/VisualTesting/index.mdx
  test/previewsPath.js
  test/spec/screenshots.test.js
  wdio.conf.js
  wdio.conf.local.js
  yarn.lock
Labels: scope:website, test

#421 refactor(pattern/namingconvention): remove spacings in the sketch files
  packages/designer-kit/sketch-libraries/[AA]AspectRatios.sketch
  packages/designer-kit/sketch-libraries/[AA]Colors.sketch
  packages/designer-kit/sketch-libraries/[AA]Fonts.sketch
  packages/designer-kit/sketch-libraries/[AA]Icons.sketch
  packages/designer-kit/sketch-libraries/[AA]Shadows.sketch
  packages/designer-kit/sketch-libraries/[BA]Bodies.sketch
  packages/designer-kit/sketch-libraries/[BA]Buttons.sketch
  packages/designer-kit/sketch-libraries/[BA]Flags.sketch
  packages/designer-kit/sketch-libraries/[BA]Forms.sketch
  packages/designer-kit/sketch-libraries/[BA]Headings.sketch
  packages/designer-kit/sketch-libraries/[BA]Heros.sketch
  packages/designer-kit/sketch-libraries/[BA]Icons.sketch
  packages/designer-kit/sketch-libraries/[BA]Links.sketch
  packages/designer-kit/sketch-libraries/[BA]Ratings.sketch
  packages/designer-kit/sketch-libraries/[BA]Tags.sketch
  packages/designer-kit/sketch-libraries/[BB]Notifications.sketch
  src/docs/Components/Checkbox/design.mdx
  src/docs/Components/FileUploader/design.mdx
  src/docs/Components/Radio/design.mdx
  src/docs/Components/Select/design.mdx
  src/docs/Components/TextArea/design.mdx
  src/docs/Components/TextInput/design.mdx
  src/docs/Components/Toggle/design.mdx
  src/docs/Contributing/Prerequisite/NamingConvention/index.mdx
  src/docs/GetStarted/Designers/namingConvention/index.mdx
Labels: refactor, scope:pattern, skill:design

#415 feat(patterns/spaces): add an utility class to manage all sides in one css classes
  packages/styles/settings-tools/_s.spaces.scss
  src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
Labels: feat, scope:pattern

#423 feat(website/home): update home page
  src/pages/index.js
Labels: feat, scope:website

#428 feat(chore/test): previews and screenshots generation
  .gitignore
  gatsby-config.js
  package.json
  packages/gatsby-theme-styleguide/gatsby-node.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/Preview.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewFrame.js
  src/docs/Contributing/VisualTesting/applitools-API-key.gif
  src/docs/Contributing/VisualTesting/applitools-analyse-screenshots.png
  src/docs/Contributing/VisualTesting/applitools-how-it-works.png
  src/docs/Contributing/VisualTesting/index.mdx
  test/spec/screenshots.test.js
  wdio.conf.js
  yarn.lock
Labels: feat, scope:chore, test

#432 fix(tools/tokens build cmd): remove : char from command to fix an ins…
  package.json
  packages/tokens/package.json
  src/docs/GetStarted/Developers/CustomizeTokens/index.mdx
Labels: fix, scope:tools, skill:dev

#429 fix(website/previews): fix copy and paste for colors and icons & previews height
  package.json
  packages/gatsby-theme-styleguide/gatsby-node.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Color/ColorInfo.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Copy/Copy.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconLibrairy/IconLibrairy.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewFrame.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewToolBar.js
  yarn.lock
Labels: fix, scope:website

#430 fix(pattern/various): fixe ie11 bugs for buttons, notifs, file-upload…
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.notification.scss
  packages/styles/layouts/_l.flexy.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.file-uploader.scss
  packages/styles/settings-tools/_s.flags.scss
  packages/styles/settings-tools/_s.notification.scss
  src/docs/Components/FileUploader/code.mdx
  src/docs/Components/FileUploader/previews/file-uploader-with-file-delete.preview.html
  src/docs/Components/FileUploader/previews/file-uploader-with-file.preview.html
  src/docs/Components/Notification/previews/notification-types.preview.html
  src/docs/Components/Notification/previews/notification-types.preview.scss
  src/docs/Components/Toggle/previews/toggle-states.preview.html
  src/docs/Foundations/Layout/Grid/previews/flexyAlign.preview.scss
  src/docs/Foundations/Layout/Grid/previews/flexyCentered.preview.scss
Labels: fix, scope:pattern, skill:dev

#435 fix(pattern/various): fix ie11 bugs for input, checkbox, radio and stars
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.stars-input.scss
  packages/styles/components/_c.stars-result.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/settings-tools/_s.stars.scss
Labels: fix, scope:pattern, skill:dev

#436 feat(pattern/icons): fix icons on icon kit
  packages/designer-kit/sketch-libraries/leroy-merlin/[AA]Icons.sketch
  packages/icons/svg/Navigation_Publish_Trashbin_24px.svg
  packages/icons/svg/Payment_Cards_Monochrome_OneyX3_48px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Oney_24px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Paypal_24px.svg
  packages/icons/svg/Payment_Monochrome_Oney_24px.svg
  packages/icons/svg/Universe_Electricity_32px.svg
  packages/icons/svg/Universe_Electricity_64px.svg
  packages/icons/svg/Universe_Garden1_64px.svg
  packages/icons/svg/Universe_Heater_32px.svg
  packages/icons/svg/Universe_Lighting_32px.svg
  packages/icons/svg/Universe_Terrace_32px.svg
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  src/data/icons.json
  src/icons/16px/Navigation_Display_ExternalLink_16px.svg
  src/icons/24px/Navigation_Display_ExternalLink_24px.svg
  src/icons/24px/Navigation_Display_LinkOut_24px.svg
  src/icons/24px/Navigation_Publish_Trashbin_24px.svg
  src/icons/24px/Payment_Cards_Monochrome_Oney_24px.svg
  src/icons/24px/Payment_Cards_Monochrome_Paypal_24px.svg
  src/icons/24px/Payment_Monochrome_Oney_24px.svg
  src/icons/32px/Navigation_Display_ExternalLink_32px.svg
  src/icons/32px/Navigation_Display_LinkOut_32px.svg
  src/icons/32px/Universe_Electricity_32px.svg
  src/icons/32px/Universe_Heater_32px.svg
  src/icons/32px/Universe_Lighting_32px.svg
  src/icons/32px/Universe_Terrace_32px.svg
  src/icons/48px/Navigation_Display_ExternalLink_48px.svg
  src/icons/48px/Navigation_Display_LinkOut_48px.svg
  src/icons/48px/Payment_Cards_Monochrome_OneyX3_48px.svg
  src/icons/64px/Navigation_Display_ExternalLink_64px.svg
  src/icons/64px/Navigation_Display_LinkOut_64px.svg
  src/icons/64px/Universe_ConnectedHome_32px.svg
  src/icons/64px/Universe_Electricity_64px.svg
  src/icons/64px/Universe_Garden1_64px.svg
  src/icons/64px/Universe_Heater_32px.svg
  src/icons/64px/Universe_Kids_32px.svg
  static/icons/Navigation_Publish_Trashbin_24px.svg
  static/icons/Payment_Cards_Monochrome_OneyX3_48px.svg
  static/icons/Payment_Cards_Monochrome_Oney_24px.svg
  static/icons/Payment_Cards_Monochrome_Paypal_24px.svg
  static/icons/Payment_Monochrome_Oney_24px.svg
  static/icons/Universe_Electricity_32px.svg
  static/icons/Universe_Electricity_64px.svg
  static/icons/Universe_Garden1_64px.svg
  static/icons/Universe_Heater_32px.svg
  static/icons/Universe_Lighting_32px.svg
  static/icons/Universe_Terrace_32px.svg
Labels: feat, scope:pattern, skill:design

#438 fix(tools/css-dev-tools): add missing dependency
  packages/css-dev-tools/package.json
Labels: fix

#439 feat(pattern/icons): add missing icon
  packages/icons/svg/Navigation_Display_ExternalLink_16px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_24px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_32px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_48px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_64px.svg
  packages/icons/svg/Universe_Garden1_64px.svg
  src/data/icons.json
  src/icons/64px/Universe_ConnectedHome_32px.svg
  src/icons/64px/Universe_Garden1_64px.svg
  src/icons/64px/Universe_Heater_32px.svg
  src/icons/64px/Universe_Kids_32px.svg
  static/icons/Navigation_Display_ExternalLink_16px.svg
  static/icons/Navigation_Display_ExternalLink_24px.svg
  static/icons/Navigation_Display_ExternalLink_32px.svg
  static/icons/Navigation_Display_ExternalLink_48px.svg
  static/icons/Navigation_Display_ExternalLink_64px.svg
  static/icons/Universe_Garden1_64px.svg
Labels: fix, scope:pattern

#440 fix(chore/test): fix screenshots for mobile devices (#231)
  wdio.conf.js
Labels: fix, scope:chore, test

#442 fix(pattern/icon): rename social icon
  packages/icons/svg/Social_View_Like--Negative_16px.svg
  packages/icons/svg/Social_View_Like--Negative_32px.svg
  packages/icons/svg/Social_View_Like--Negative_48px.svg
  src/data/icons.json
  src/icons/16px/Social_View_Like--Negative_16px.svg
  src/icons/16px/Social_View_Like-Negative_16px.svg
  src/icons/32px/Social_View_Like--Negative_32px.svg
  src/icons/32px/Social_View_Like-Negative_32px.svg
  src/icons/48px/Social_View_Like--Negative_48px.svg
  src/icons/48px/Social_View_Like-Negative_48px.svg
  static/icons/Social_View_Like--Negative_16px.svg
  static/icons/Social_View_Like--Negative_32px.svg
  static/icons/Social_View_Like--Negative_48px.svg
Labels: fix, scope:pattern

#443 fix(patterns/margins and paddings): fix bug where units where rendere…
  packages/styles/settings-tools/_s.spaces.scss
  src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
  src/docs/Foundations/Layout/MarginAndPaddings/previews/margins.preview.html
  src/docs/Foundations/Layout/MarginAndPaddings/previews/margins.preview.scss
Labels: fix, skill:dev

#444 feat(chore/test): add jest testing to required packages
  .gitignore
  __mocks__/styleMock.js
  babel.config.js
  jest.config.base.js
  jest.config.js
  package.json
  packages/gatsby-source-preview/jest.config.js
  packages/gatsby-source-preview/tests/sourcePreview.test.js
  packages/gatsby-theme-styleguide/__mocks__/file-mock.js
  packages/gatsby-theme-styleguide/__mocks__/gatsby.js
  packages/gatsby-theme-styleguide/jest-preprocess.js
  packages/gatsby-theme-styleguide/jest.config.js
  packages/gatsby-theme-styleguide/loadershim.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Code/__tests__/Code.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Color/__tests__/Color.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Color/__tests__/__snapshots__/Color.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/IconLibrairy/IconLibrairy.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/patternStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/Preview.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewFrame.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/__tests__/preview.js
  packages/postcss-media-queries-packer-on-demand/index.test.js
  packages/postcss-media-queries-packer-on-demand/jest.config.js
  packages/postcss-media-queries-packer-on-demand/package.json
  yarn.lock
Labels: feat, scope:chore, test
