Repository adeo/mozaic-design-system, pull requests merged in 2020-02, with the labels that each got.

#481 fix(tools/stylelint): quickfix stylelint for vuejs - disable max-empt…
  packages/css-dev-tools/styleLintConfig.js
Labels: fix, scope:tools, skill:dev

#482 fix(onboard/sketch): update the doc with the current sketch version
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Icons.sketch
  src/docs/Contributing/Designers/DesignRequirements/index.mdx
  src/docs/GetStarted/Designers/requirements/index.mdx
  src/docs/GetStarted/Designers/whatsIncluded/index.mdx
Labels: fix, scope:onboard, skill:design

#480 feat(patterns/input): update documentation about css pseudo-classes
  src/docs/Components/TextInput/code.mdx
Labels: feat, scope:onboard, scope:pattern

#479 feat(website/search): create search engine
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/gatsby-node.js
  packages/gatsby-theme-styleguide/gatsby-ssr.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuHeader.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Search/Search.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Search/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SubContents/SubContents.js
  packages/tokens/build/scss/_tokens.scss
  src/docs/Components/Flags/index.mdx
  yarn.lock
Labels: feat, scope:website, skill:dev

#484 feat(website/home): redesign home and change global font
  src/pages/Adeo_logo.jpg
  src/pages/Leroy_Merlin.jpg
  src/pages/homepage-illustration.png
  src/pages/index.js
  src/pages/index.scss
Labels: feat, scope:website, skill:design

#477 feat(onboard/roadmap): add a roadmap and want to help to the documentation under the u…
  src/docs/Updates/PatternsStatus/index.mdx
  src/docs/Updates/Roadmap/index.mdx
  src/docs/Updates/Updates/index.mdx
  src/docs/WantToHelp/index.mdx
Labels: feat, scope:onboard, skill:design, skill:dev

#486 fix(pattern/colors): updated color.font values
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/font.json
Labels: fix, scope:pattern, skill:design, skill:dev

#483 feat(component/fields): create component fields
  packages/styles/components/_c.fields.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/fields.json
  src/docs/Components/Field/Fields--Overview.png
  src/docs/Components/Field/code.mdx
  src/docs/Components/Field/index.mdx
  src/docs/Components/Field/previews/fields-full.preview.html
  src/docs/Components/Field/previews/fields-full.preview.scss
  src/docs/Components/Field/previews/fields-help.preview.html
  src/docs/Components/Field/previews/fields-help.preview.scss
  src/docs/Components/Field/previews/fields-requirement.preview.html
  src/docs/Components/Field/previews/fields-requirement.preview.scss
  src/docs/Components/Field/previews/fields-sizes.preview.html
  src/docs/Components/Field/previews/fields-sizes.preview.scss
  src/docs/Components/Field/previews/fields-state.preview.html
  src/docs/Components/Field/previews/fields-state.preview.scss
  src/docs/Components/Field/previews/fields-validation.preview.html
  src/docs/Components/Field/previews/fields-validation.preview.scss
  src/docs/Components/Field/previews/fields.preview.html
  src/docs/Components/Field/previews/fields.preview.scss
  src/docs/Components/Field/specs.mdx
  src/docs/Components/Fields/Fields--Overview.png
Labels: feat, scope:pattern, skill:design, skill:dev

#490 feat(pattern/sketchfiles): design kit sketch files update
  packages/designer-kit/sketch-libraries/leroy-merlin/[AA]Grids.sketch
  packages/designer-kit/sketch-libraries/leroy-merlin/[AA]Icons.sketch
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Forms.sketch
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Notifications.sketch
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Notifications.sketch
Labels: feat, scope:pattern

#487 fix(foundations/gridsystem): add the disappeared doc and fixed some typos
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/Foundations/Layout/Container/code.mdx
  src/docs/Foundations/Layout/Container/index.mdx
  src/docs/Foundations/Layout/Grid/1024-fixed&fluid.png
  src/docs/Foundations/Layout/Grid/1280-fixed&fluid.png
  src/docs/Foundations/Layout/Grid/1366-fixed.png
  src/docs/Foundations/Layout/Grid/1366-fluid.png
  src/docs/Foundations/Layout/Grid/1440-fixed.png
  src/docs/Foundations/Layout/Grid/1440-fluid.png
  src/docs/Foundations/Layout/Grid/1920-fixed&fluid.png
  src/docs/Foundations/Layout/Grid/320-fluid.png
  src/docs/Foundations/Layout/Grid/360-fluid.png
  src/docs/Foundations/Layout/Grid/375-fluid.png
  src/docs/Foundations/Layout/Grid/680-fluid.png
  src/docs/Foundations/Layout/Grid/768-fluid.png
  src/docs/Foundations/Layout/Grid/code.mdx
  src/docs/Foundations/Layout/Grid/design.mdx
  src/docs/Foundations/Layout/Grid/fixed-grid.png
  src/docs/Foundations/Layout/Grid/fluid-grid.png
  src/docs/Foundations/Layout/Grid/index.mdx
Labels: fix, scope:pattern, skill:design

#488 fix(website/links): repair broken links in the documentation
  README.md
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Contributing/Designers/AddNewIcons/index.mdx
  src/docs/Contributing/Designers/DesignToolsConventions/index.mdx
  src/docs/Contributing/Developers/CSSConventions/index.mdx
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/Contributing/SubmitChanges/AddNewPattern/index.mdx
  src/docs/Contributing/SubmitChanges/PatternEnhancement/index.mdx
  src/docs/Contributing/SubmitChanges/SubmitBugFix/index.mdx
  src/docs/Contributing/SubmitChanges/SubmitNewPattern/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
  src/docs/GetStarted/Developers/CustomizeTokens/index.mdx
  src/docs/GetStarted/Developers/configureStylelint/index.mdx
  src/pages/index.js
Labels: fix, scope:website

#489 fix(pattern/notifications): improve the notification requirements
  src/docs/Components/Notification/index.mdx
Labels: fix, scope:pattern
