Repository adeo/mozaic-design-system, pull requests merged in 2020-10, with the labels that each got.

#653 fix(onboard): repair broken link
  src/docs/Contributing/SubmitChanges/SubmitNewPattern/index.mdx
Labels: fix, scope:onboard

#655 refactor(website/roadmap): update the roadmap
  src/docs/Updates/Roadmap/index.mdx
Labels: refactor, scope:website

#654 fix(patterns/notification): remove margin-top on notification message…
  packages/styles/components/_c.notification.scss
Labels: fix, scope:pattern

#617 feat(patterns/layers): add layer pattern
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Layers/accessibility.mdx
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Layers/layers-anatomy.png
  src/docs/Components/Layers/previews/cta-link.preview.html
  src/docs/Components/Layers/previews/cta-link.preview.scss
  src/docs/Components/Layers/previews/cta-two.preview.html
  src/docs/Components/Layers/previews/cta-two.preview.scss
  src/docs/Components/Layers/previews/default.preview.html
  src/docs/Components/Layers/previews/default.preview.scss
  src/docs/Components/Layers/previews/header-with-icon.preview.html
  src/docs/Components/Layers/previews/header-with-icon.preview.scss
  src/docs/Components/Layers/previews/scrolling-content.preview.html
  src/docs/Components/Layers/previews/scrolling-content.preview.scss
  src/docs/Components/Layers/previews/without-footer.preview.html
  src/docs/Components/Layers/previews/without-footer.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#657 docs(getstarted): clean documentation
  src/docs/GetStarted/Designers/aboutTheSystem/index.mdx
  src/docs/GetStarted/Designers/installation/index.mdx
  src/docs/GetStarted/Designers/namingConvention/index.mdx
  src/docs/GetStarted/Designers/requirements/index.mdx
  src/docs/GetStarted/Designers/whatsIncluded/index.mdx
  src/docs/GetStarted/Developers/Configuration/index.mdx
  src/docs/GetStarted/Developers/CssNamingConventions/index.mdx
  src/docs/GetStarted/Developers/CustomizeTokens/adeoPreset.mdx
  src/docs/GetStarted/Developers/CustomizeTokens/index.mdx
  src/docs/GetStarted/Developers/Installation/assets.mdx
  src/docs/GetStarted/Developers/Installation/import.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/Installation/itcss-atomic-prefixes.jpg
  src/docs/GetStarted/Developers/Installation/postcss.mdx
  src/docs/GetStarted/Developers/Installation/stylelint.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  src/docs/GetStarted/Developers/whatsincluded/index.mdx
  src/docs/GetStarted/Principles/index.mdx
  src/docs/GetStarted/Principles/the6s.mdx
  src/docs/GetStarted/index.mdx
Labels: feat, scope:onboard

#658 docs(foundations/color): grammar review
  src/docs/Foundations/Colors/index.mdx
Labels: fix, scope:onboard

#616 feat(patterns/fonts): implementing the new LM webfont
  packages/styles/components/_c.accordion.scss
  packages/styles/components/_c.breadcrumb.scss
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.fields.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.flag.scss
  packages/styles/components/_c.links.scss
  packages/styles/components/_c.modal.scss
  packages/styles/components/_c.notification.scss
  packages/styles/components/_c.pagination.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.tabs.scss
  packages/styles/components/_c.tag.scss
  packages/styles/components/_c.toggle.scss
  packages/styles/components/_c.tooltip.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.flags.scss
  packages/styles/settings-tools/_s.links.scss
  packages/styles/settings-tools/_s.notification.scss
  packages/styles/settings-tools/_s.select.scss
  packages/styles/settings-tools/_s.tag.scss
  packages/styles/settings-tools/_s.text-input.scss
  packages/web-fonts/LeroyMerlinSans-Web-Italic.woff
  packages/web-fonts/LeroyMerlinSans-Web-Italic.woff2
  packages/web-fonts/LeroyMerlinSans-Web-Light.woff
  packages/web-fonts/LeroyMerlinSans-Web-Light.woff2
  packages/web-fonts/LeroyMerlinSans-Web-LightItalic.woff
  packages/web-fonts/LeroyMerlinSans-Web-LightItalic.woff2
  packages/web-fonts/LeroyMerlinSans-Web-Regular.woff
  packages/web-fonts/LeroyMerlinSans-Web-Regular.woff2
  packages/web-fonts/LeroyMerlinSans-Web-SemiBold.woff
  packages/web-fonts/LeroyMerlinSans-Web-SemiBold.woff2
  packages/web-fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff
  packages/web-fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff2
  src/docs/Components/Flags/previews/flag-all.preview.html
  src/docs/Components/Flags/previews/flag-basic.preview.html
  src/docs/Components/Flags/previews/flag-bordered.preview.html
  src/docs/Components/Flags/previews/flag-default.preview.html
  src/docs/Components/Flags/previews/flag-solid.preview.html
  static/fonts/LeroyMerlinSans-Web-Italic.woff
  static/fonts/LeroyMerlinSans-Web-Italic.woff2
  static/fonts/LeroyMerlinSans-Web-Light.woff
  static/fonts/LeroyMerlinSans-Web-Light.woff2
  static/fonts/LeroyMerlinSans-Web-LightItalic.woff
  static/fonts/LeroyMerlinSans-Web-LightItalic.woff2
  static/fonts/LeroyMerlinSans-Web-Regular.woff
  static/fonts/LeroyMerlinSans-Web-Regular.woff2
  static/fonts/LeroyMerlinSans-Web-SemiBold.woff
  static/fonts/LeroyMerlinSans-Web-SemiBold.woff2
  static/fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff
  static/fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff2
Labels: scope:pattern, skill:design, skill:dev
