Repository adeo/mozaic-design-system, pull requests merged in 2020-07, with the labels that each got.

#592 refactor(website/roadmap): update roadmap page
  src/docs/Updates/Roadmap/index.mdx
Labels: refactor, scope:website

#594 feat(pattern/tooltip): add tooltip design
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Tooltips.sketch
  src/docs/Components/Tooltip/Tooltip--Position.png
  src/docs/Components/Tooltip/Tooltip--Specs.png
  src/docs/Components/Tooltip/Tooltip--designSpacing.png
  src/docs/Components/Tooltip/design.mdx
  src/docs/Components/Tooltip/index.mdx
Labels: feat, scope:pattern, skill:design

#597 feat(pattern/tooltip): add tooltip pattern and documentation
  packages/styles/components/_c.tooltip.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Tooltip/code.mdx
  src/docs/Components/Tooltip/index.mdx
  src/docs/Components/Tooltip/previews/default.preview.html
  src/docs/Components/Tooltip/previews/default.preview.scss
  src/docs/Components/Tooltip/specs.mdx
Labels: feat, scope:pattern, skill:dev

#607 feat(patterns/tooltips): add usage and specs documentation (#594)
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Tooltips.sketch
  packages/styles/components/_c.tooltip.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Tooltip/Tooltip--Position.png
  src/docs/Components/Tooltip/Tooltip--Specs.png
  src/docs/Components/Tooltip/Tooltip--designSpacing.png
  src/docs/Components/Tooltip/code.mdx
  src/docs/Components/Tooltip/design.mdx
  src/docs/Components/Tooltip/index.mdx
  src/docs/Components/Tooltip/previews/default.preview.html
  src/docs/Components/Tooltip/previews/default.preview.scss
  src/docs/Components/Tooltip/specs.mdx
Labels: feat, scope:pattern, skill:design, skill:dev

#598 fix(patterns/input): fix calendar input with icon
  src/docs/Components/Form/TextInput/previews/input-small-left-icon.preview.html
  src/docs/Components/Form/TextInput/previews/left-icon-input.preview.html
Labels: fix, scope:pattern, skill:dev

#599 feat(patterns/datepicker): add documentation for datepicker component
  src/docs/Components/Form/Datepicker/code.mdx
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Datepicker/previews/default.preview.html
  src/docs/Components/Form/Datepicker/previews/default.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#605 feat(website/vuejs): add Vue.js link on Mozaic homepage
  src/pages/index.js
Labels: feat, scope:website

#602 feat(pattern/breadcrumb: add breadcrumb design
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Breadcrumb.sketch
  src/docs/Components/Breadcrumb/index.mdx
Labels: feat, scope:pattern, skill:design

#604 feat(website/chat): add smallchat on Mozaic website
  packages/gatsby-theme-styleguide/gatsby-ssr.js
Labels: feat, scope:website

#611 fix(patterns/form): fix inline form behaviour on mobile
  packages/styles/components/_c.fields.scss
  packages/styles/components/_c.toggle.scss
  src/docs/Components/Form/Checkbox/code.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Checkbox/previews/group-inline.preview.html
  src/docs/Components/Form/Radio/code.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Radio/previews/group-inline.preview.html
  src/docs/Components/Form/Toggle/code.mdx
  src/docs/Components/Form/Toggle/previews/group-inline.preview.html
Labels: fix, scope:pattern, skill:dev

#608 feat(patterns/breadcrumb): add breadcrumb design (#602)
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Breadcrumb.sketch
  packages/styles/components/_c.breadcrumb.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Breadcrumb/breadcrumb-preview--small.png
  src/docs/Components/Breadcrumb/code.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Breadcrumb/previews/dark-mode.preview.html
  src/docs/Components/Breadcrumb/previews/dark-mode.preview.scss
  src/docs/Components/Breadcrumb/previews/default.preview.html
  src/docs/Components/Breadcrumb/previews/default.preview.scss
  src/docs/Components/Breadcrumb/previews/mobile.preview.html
  src/docs/Components/Breadcrumb/previews/mobile.preview.scss
  src/docs/Components/Breadcrumb/previews/responsive.preview.html
  src/docs/Components/Breadcrumb/previews/responsive.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#615 feat(tools): add swift tokens and serve it in assets
  assets.config.json
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/ios/StyleDictionarySize.swift
  packages/tokens/config.js
Labels: feat, scope:tools

#613 refactor(website/chat): update how to implement smallchat
  README.md
  packages/gatsby-theme-styleguide/gatsby-ssr.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Helmet/Helmet.js
Labels: refactor, scope:website, skill:dev
