Repository adeo/mozaic-design-system, pull requests merged in 2020-06, with the labels that each got.

#563 feat(patterns/select): update select pattern to use it in forms
  packages/styles/components/_c.select.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.select.scss
  src/docs/Components/Form/Select/Select-Overview.png
  src/docs/Components/Form/Select/code.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/Select/previews/Select-all-states.preview.html
  src/docs/Components/Form/Select/previews/Select-default.preview.html
  src/docs/Components/Form/Select/previews/Selects.preview.html
  src/docs/Components/Form/Select/previews/default.preview.html
  src/docs/Components/Form/Select/previews/default.preview.scss
  src/docs/Components/Form/Select/previews/disabled.preview.html
  src/docs/Components/Form/Select/previews/disabled.preview.scss
  src/docs/Components/Form/Select/previews/help-text.preview.html
  src/docs/Components/Form/Select/previews/help-text.preview.scss
  src/docs/Components/Form/Select/previews/invalid.preview.html
  src/docs/Components/Form/Select/previews/invalid.preview.scss
  src/docs/Components/Form/Select/previews/requirement.preview.html
  src/docs/Components/Form/Select/previews/requirement.preview.scss
  src/docs/Components/Form/Select/previews/select-all-states.preview.html
  src/docs/Components/Form/Select/previews/select-all-states.preview.scss
  src/docs/Components/Form/Select/previews/select-full.preview.html
  src/docs/Components/Form/Select/previews/select-full.preview.scss
  src/docs/Components/Form/Select/previews/single.preview.html
  src/docs/Components/Form/Select/previews/single.preview.scss
  src/docs/Components/Form/Select/previews/sizes.preview.html
  src/docs/Components/Form/Select/previews/sizes.preview.scss
  src/docs/Components/Form/Select/previews/valid.preview.html
  src/docs/Components/Form/Select/previews/valid.preview.scss
  src/docs/Components/Form/Select/previews/validation.preview.html
  src/docs/Components/Form/Select/previews/validation.preview.scss
Labels: feat, scope:pattern

#570 fix(chore/dependencies): fix security alert websocket-extensions
  package.json
  yarn.lock
Labels: fix, scope:chore

#571 refactor(patterns/button): improve neutral button documentation
  src/docs/Components/Buttons/index.mdx
Labels: refactor, scope:pattern, skill:design

#564 feat(patterns/checkbox): update checkbox pattern to use it in forms
  packages/styles/components/_c.fields.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.fields.scss
  packages/tokens/properties/color/input.json
  src/docs/Components/Form/Checkbox/Checkbox-Overview.png
  src/docs/Components/Form/Checkbox/code.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Checkbox/previews/checkbox-item.preview.html
  src/docs/Components/Form/Checkbox/previews/checkbox-item.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-default.preview.html
  src/docs/Components/Form/Checkbox/previews/group-default.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-help-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-help-light.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-help-text.preview.html
  src/docs/Components/Form/Checkbox/previews/group-help-text.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-inline.preview.html
  src/docs/Components/Form/Checkbox/previews/group-inline.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-invalid-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-invalid-light.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-invalid.preview.html
  src/docs/Components/Form/Checkbox/previews/group-invalid.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-requirement-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-requirement-light.preview.scss
  src/docs/Components/Form/Checkbox/previews/group-requirement.preview.html
  src/docs/Components/Form/Checkbox/previews/group-requirement.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#572 fix(chore): upgrade graphql-playground-html version
  package.json
  yarn.lock
Labels: fix, scope:chore

#579 fix(chore): update api token
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: fix, scope:chore, skill:dev

#575 fix(patterns/reset-css): remove rules for img tag in order to avoid s…
  packages/styles/generic/_g.reset.scss
Labels: fix, scope:pattern, skill:dev

#581 feat(patterns/border-radius): update code documentation
  src/docs/Foundations/BorderRadius/code.mdx
Labels: feat, scope:pattern, skill:dev

#580 fix(patterns/fileuploader): remove href attribute on fileuploader del…
  src/docs/Components/FileUploader/code.mdx
  src/docs/Components/FileUploader/previews/file-uploader-with-file-delete.preview.html
Labels: fix, scope:pattern, skill:dev

#574 feat(pattern/tabs): Add pattern tabs
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Tabs.sketch
  packages/styles/components/_c.tabs.scss
  src/docs/Components/Tabs/Tabs--Specs.png
  src/docs/Components/Tabs/code.mdx
  src/docs/Components/Tabs/design.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tabs/previews/tabs-all-stats.preview.html
  src/docs/Components/Tabs/previews/tabs-all-stats.preview.scss
  src/docs/Components/Tabs/previews/tabs-code-states.preview.html
  src/docs/Components/Tabs/previews/tabs-code-states.preview.scss
  src/docs/Components/Tabs/previews/tabs-container.preview.html
  src/docs/Components/Tabs/previews/tabs-container.preview.scss
  src/docs/Components/Tabs/previews/tabs-dropdown.preview.html
  src/docs/Components/Tabs/previews/tabs-dropdown.preview.scss
  src/docs/Components/Tabs/previews/tabs-full.preview.html
  src/docs/Components/Tabs/previews/tabs-full.preview.scss
  src/docs/Components/Tabs/previews/tabs-fullwidth.preview.html
  src/docs/Components/Tabs/previews/tabs-fullwidth.preview.scss
  src/docs/Components/Tabs/specs.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/TextArea/index.mdx
  src/docs/Components/Toggle/index.mdx
Labels: feat, scope:pattern

#585 fix(website): remove pages that has been moved under Form menu
  src/docs/Components/TextArea/index.mdx
  src/docs/Components/Toggle/index.mdx
Labels: fix, scope:website

#588 fix(patterns/tabs): remove typo
  src/docs/Components/Tabs/design.mdx
Labels: fix, scope:pattern, skill:design

#584 fix(patterns/pagination): center by default and fix button icon for IE
  packages/styles/components/_c.pagination.scss
  src/docs/Components/Pagination/previews/pagination-default.preview.html
  src/docs/Components/Pagination/previews/pagination-default.preview.scss
  src/docs/Components/Pagination/previews/pagination-light.preview.html
  src/docs/Components/Pagination/previews/pagination-light.preview.scss
  src/docs/Components/Pagination/previews/pagination.preview.html
  src/docs/Components/Pagination/previews/pagination.preview.scss
Labels: fix, scope:pattern, skill:dev

#590 fix(patterns/container): make mc-container fluid when using class .ml…
  packages/styles/layouts/_l.container.scss
Labels: fix, scope:pattern, skill:dev
