Repository adeo/mozaic-design-system, pull requests merged in 2020-11, with the labels that each got.

#668 fix(patterns/button): update the buttons's disabled state color
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/button.json
Labels: fix, scope:pattern

#659 feat(foundations/layout): clean documentation
  src/docs/Foundations/Layout/Grid/code.mdx
  src/docs/Foundations/Layout/Grid/customization.mdx
  src/docs/Foundations/Layout/Grid/index.mdx
  src/docs/Foundations/Layout/Grid/previews/basic.preview.html
  src/docs/Foundations/Layout/Grid/previews/basic.preview.scss
  src/docs/Foundations/Spacing/MagicUnit/code.mdx
  src/docs/Foundations/Spacing/MagicUnit/index.mdx
  src/docs/Foundations/Spacing/MagicUnit/previews/magic-unit.preview.html
  src/docs/Foundations/Spacing/MagicUnit/previews/magic-unit.preview.scss
  src/docs/Foundations/Spacing/MagicUnit/previews/mdu-magic-unit-grid.preview.html
  src/docs/Foundations/Spacing/MagicUnit/previews/mdu-magic-unit-grid.preview.scss
  src/docs/Foundations/Spacing/MagicUnit/sheatsheat.mdx
  src/docs/Foundations/Spacing/MarginAndPaddings/code.mdx
  src/docs/Foundations/Spacing/MarginAndPaddings/index.mdx
  src/docs/Foundations/Spacing/MarginAndPaddings/previews/margins.preview.html
  src/docs/Foundations/Spacing/MarginAndPaddings/previews/margins.preview.scss
  src/docs/Foundations/Spacing/index.mdx
  src/docs/Foundations/Utilities/BorderRadius/code.mdx
  src/docs/Foundations/Utilities/BorderRadius/index.mdx
  src/docs/Foundations/Utilities/BorderRadius/previews/example.preview.html
  src/docs/Foundations/Utilities/BorderRadius/previews/example.preview.scss
  src/docs/Foundations/Utilities/BorderRadius/previews/large.preview.html
  src/docs/Foundations/Utilities/BorderRadius/previews/large.preview.scss
  src/docs/Foundations/Utilities/BorderRadius/previews/medium.preview.html
  src/docs/Foundations/Utilities/BorderRadius/previews/medium.preview.scss
  src/docs/Foundations/Utilities/BorderRadius/previews/small.preview.html
  src/docs/Foundations/Utilities/BorderRadius/previews/small.preview.scss
  src/docs/Foundations/Utilities/BorderRadius/specs.mdx
  src/docs/Foundations/Utilities/Images/aspect-ratios--preview.png
  src/docs/Foundations/Utilities/Images/aspect-ratios-sketch-menu.png
  src/docs/Foundations/Utilities/Images/design.mdx
  src/docs/Foundations/Utilities/Images/index.mdx
  src/docs/Foundations/Utilities/Shadows/code.mdx
  src/docs/Foundations/Utilities/Shadows/designer.mdx
  src/docs/Foundations/Utilities/Shadows/index.mdx
  src/docs/Foundations/Utilities/Shadows/previews/example.preview.html
  src/docs/Foundations/Utilities/Shadows/previews/example.preview.scss
  src/docs/Foundations/Utilities/Shadows/previews/large.preview.html
  src/docs/Foundations/Utilities/Shadows/previews/large.preview.scss
  src/docs/Foundations/Utilities/Shadows/previews/medium.preview.html
  src/docs/Foundations/Utilities/Shadows/previews/medium.preview.scss
  src/docs/Foundations/Utilities/Shadows/previews/small.preview.html
  src/docs/Foundations/Utilities/Shadows/previews/small.preview.scss
  src/docs/Foundations/Utilities/Shadows/specs.mdx
  src/docs/Foundations/Utilities/Strokes/StrokesExemples.png
  src/docs/Foundations/Utilities/Strokes/StrokesInside.png
  src/docs/Foundations/Utilities/Strokes/code.mdx
  src/docs/Foundations/Utilities/Strokes/design.mdx
  src/docs/Foundations/Utilities/Strokes/index.mdx
  src/docs/Foundations/Utilities/Strokes/specs.mdx
  src/docs/Foundations/Utilities/index.mdx
Labels: feat, scope:onboard

#674 feat(patterns/flag): prevent flag from shrinking + add modifier for multi-line flag
  packages/styles/components/_c.flag.scss
  packages/styles/settings-tools/_s.flags.scss
  src/docs/Components/Flags/code.mdx
Labels: feat, scope:pattern

#673 feat(patterns/link): make the light link accessible
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/link.json
Labels: feat, scope:pattern

#671 fix(patterns/file-uploader): improve truncation on the loaded file name
  packages/styles/components/_c.file-uploader.scss
  src/docs/Components/Form/FileUploader/previews/uploaded-files-with-errors.preview.html
Labels: fix, scope:pattern

#681 refactor(website/homepage): remove unused files
  src/components/AreaContact/AreaContact.js
  src/components/AreaContact/index.js
  src/components/AreaDiscover/AreaDiscover.js
  src/components/AreaDiscover/index.js
  src/components/AreaValues/AreaValues.js
  src/components/AreaValues/index.js
  src/components/Footer/Footer.js
  src/components/Footer/index.js
  src/components/Header/Header.js
  src/components/Header/index.js
  src/components/McButton/McButton.js
  src/components/McButton/index.js
  src/components/McButton/styles.scss
  src/components/McCheckbox/McCheckbox.js
  src/components/McCheckbox/index.js
  src/components/McCheckbox/styles.scss
  src/components/McTextInput/McTextInput.js
  src/components/McTextInput/index.js
  src/components/McTextInput/styles.scss
  src/components/McToggle/McToggle.js
  src/components/McToggle/index.js
  src/components/McToggle/styles.scss
  src/images/Adeo_logo.jpg
  src/images/Leroy_Merlin.jpg
Labels: refactor, scope:website, skill:dev

#683 feat(patterns/text-input): reset default appearance of input[type="number"] items
  packages/styles/generic/_g.reset.scss
  packages/styles/settings-tools/_t.reset-forms.scss
Labels: feat, scope:tools

#682 feat(tools/autoprefixer): add autoprefixer in the production build
  packages/css-dev-tools/postcssPluginConfig.js
Labels: feat, scope:tools, skill:dev

#675 fix(website/homepage): update roadmap link
  src/data/datas.json
Labels: fix, scope:website

#685 fix(patterns/mc-link): avoid the link icon from shrinking
  packages/styles/components/_c.links.scss
Labels: fix, scope:pattern, skill:dev

#672 refactor(website/roadmap): update the roadmap
  src/docs/Updates/Roadmap/index.mdx
Labels: refactor, scope:website
