Repository adeo/mozaic-design-system, pull requests merged in 2020-09, with the labels that each got.

#635 refactor(website/responsive): make the website responsive
  packages/gatsby-theme-styleguide/src/gatsby-components/Container/Container.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/base.scss
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: refactor, scope:website

#636 feat(website/header): add data for status and js link
  packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/FileUploader/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/Tooltip/index.mdx
Labels: feat, scope:website

#612 feat(website/header): add js links
  packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js
  packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/PatternsStatus.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternsStatus/__tests__/__snapshots__/patternStatus.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/StatusFlag.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/StatusFlag.test.js
  packages/gatsby-theme-styleguide/src/gatsby-components/StatusFlag/__tests__/__snapshots__/StatusFlag.test.js.snap
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/FileUploader/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/Tooltip/index.mdx
Labels: scope:website, skill:dev

#622 feat(website/roadmap): update the roadmap
  src/docs/Updates/Roadmap/index.mdx
Labels: feat, scope:website

#637 feat(website/calloutvue): display vuejs link in code tab
  packages/gatsby-theme-styleguide/src/gatsby-components/CalloutVue/CalloutVue.js
  packages/gatsby-theme-styleguide/src/gatsby-components/CalloutVue/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/PatternStatusGroup.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PatternStatusGroup/__tests__/__snapshots__/PatternStatusGroup.js.snap
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: feat, scope:website

#639 fix(website/docs): remove fileuploader section (already under form)
  src/docs/Components/FileUploader/index.mdx
Labels: fix, scope:website

#640 fix(patterns/toggle): remove white-space property on .mc-toggle__label
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.toggle.scss
Labels: fix, scope:pattern

#630 refactor(patterns/headings): add padding bottom
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Headings.sketch
  packages/styles/settings-tools/_s.headings.scss
  packages/styles/typography/_t.headings.scss
  src/docs/Foundations/Typography/HeadingStyles/Headings--Zoning.png
  src/docs/Foundations/Typography/HeadingStyles/code.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-alignment.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-base.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-colors.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-sizes.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-underlines.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-weight.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeadingLarge.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeadingMedium.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeadingSmall.preview.scss
Labels: refactor, scope:pattern, skill:design, skill:dev

#644 fix(patterns/accordions): set display:flex only if label has an icon
  packages/styles/components/_c.accordion.scss
  src/docs/Components/Accordion/code.mdx
  src/docs/Components/Accordion/previews/icon.preview.html
  src/docs/Components/Accordion/previews/no-padding.preview.html
Labels: fix, scope:pattern

#645 fix(patterns/accordions): update max-height value when accordion is open
  packages/styles/components/_c.accordion.scss
Labels: fix, scope:pattern

#646 fix(website/freemarker): update links to components on the core docum…
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Tag/index.mdx
Labels: fix, scope:website

#642 feat(pattern/hero): add hero pattern
  packages/styles/components/_c.hero.scss
  src/docs/Components/Hero/background.png
  src/docs/Components/Hero/code.mdx
  src/docs/Components/Hero/index.mdx
  src/docs/Components/Hero/previews/basic.preview.html
  src/docs/Components/Hero/previews/basic.preview.scss
  src/docs/Components/Hero/previews/box.preview.html
  src/docs/Components/Hero/previews/box.preview.scss
  src/docs/Components/Hero/previews/centered.preview.html
  src/docs/Components/Hero/previews/centered.preview.scss
  src/docs/Components/Hero/previews/titleCentered.preview.html
  src/docs/Components/Hero/previews/titleCentered.preview.scss
  src/docs/Components/Hero/previews/titleContent.preview.html
  src/docs/Components/Hero/previews/titleContent.preview.scss
  src/docs/Components/Hero/previews/titleContentCentered.preview.html
  src/docs/Components/Hero/previews/titleContentCentered.preview.scss
Labels: feat

#650 fix(dev-infra): upgrade packages versions
  package.json
Labels: fix, scope:tools

#648 fix(patterns/toggle): increase line-height
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_s.toggle.scss
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Form/Toggle/previews/toggle-default-2lines.preview.html
  src/docs/Components/Form/Toggle/previews/toggle-default-2lines.preview.scss
Labels: fix, skill:design, skill:dev

#649 feat(patterns/toggle): remove the horizontal variation of toggle group
  src/docs/Components/Form/Toggle/code.mdx
  src/docs/Components/Form/Toggle/previews/group-help-text.preview.html
  src/docs/Components/Form/Toggle/previews/group-inline.preview.html
  src/docs/Components/Form/Toggle/previews/group-inline.preview.scss
  src/docs/Components/Form/Toggle/previews/group-requirement.preview.html
Labels: feat, scope:pattern

#627 feat(pattern/hero): add hero design
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Hero.sketch
  packages/designer-kit/sketch-libraries/leroy-merlin/[BB]Heroes.sketch
  packages/styles/components/_c.hero.scss
  src/docs/Components/Hero/background.png
  src/docs/Components/Hero/code.mdx
  src/docs/Components/Hero/index.mdx
  src/docs/Components/Hero/previews/basic.preview.html
  src/docs/Components/Hero/previews/basic.preview.scss
  src/docs/Components/Hero/previews/box.preview.html
  src/docs/Components/Hero/previews/box.preview.scss
  src/docs/Components/Hero/previews/centered.preview.html
  src/docs/Components/Hero/previews/centered.preview.scss
  src/docs/Components/Hero/previews/titleCentered.preview.html
  src/docs/Components/Hero/previews/titleCentered.preview.scss
  src/docs/Components/Hero/previews/titleContent.preview.html
  src/docs/Components/Hero/previews/titleContent.preview.scss
  src/docs/Components/Hero/previews/titleContentCentered.preview.html
  src/docs/Components/Hero/previews/titleContentCentered.preview.scss
Labels: feat, scope:pattern, skill:design
