Repository adeo/mozaic-design-system, pull requests merged in 2020-12, with the labels that each got.

#687 fix(website/component): fix warning from website component
  packages/gatsby-theme-styleguide/src/components/Header/Header.js
  packages/gatsby-theme-styleguide/src/gatsby-components/JSImplementation/JSImplementation.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Search/Search.js
  packages/gatsby-theme-styleguide/src/pages/index.js
Labels: fix, refactor, scope:website, skill:dev

#686 feat(tools/versionning): remove beta and use semver versionning
  package.json
Labels: feat, scope:tools, skill:dev

#691 refactor(patterns/magic-unit): make magic units usable as numerical v…
  packages/styles/components/_c.file-uploader.scss
  packages/styles/settings-tools/_s.magic-unit.scss
  packages/styles/settings-tools/_s.stars.scss
  packages/styles/settings-tools/_t.size-units-converters.scss
Labels: refactor, scope:pattern, skill:dev

#692 feat(patterns/input): add height property to the input field
  packages/styles/settings-tools/_s.text-input.scss
Labels: feat, scope:pattern, skill:dev

#690 fix(onboard/flag): update flag component code documentation
  src/docs/Components/Flags/code.mdx
Labels: fix, scope:onboard

#693 fix(patterns/breadcrumb): improve breadcrumb behavior on mobile resolutions
  packages/styles/components/_c.breadcrumb.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Breadcrumb/accessibility.mdx
  src/docs/Components/Breadcrumb/code.mdx
  src/docs/Components/Breadcrumb/previews/responsive.preview.html
Labels: fix, scope:pattern, skill:dev

#678 feat(pattern/quantityselector): add quantity selector
  packages/styles/components/_c.quantity-selector.scss
  src/docs/Components/Form/QuantitySelector/QtySelector-Overview.png
  src/docs/Components/Form/QuantitySelector/accessibility.mdx
  src/docs/Components/Form/QuantitySelector/code.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/QuantitySelector/previews/basic.preview.html
  src/docs/Components/Form/QuantitySelector/previews/basic.preview.scss
  src/docs/Components/Form/QuantitySelector/previews/medium-input.preview.html
  src/docs/Components/Form/QuantitySelector/previews/medium-input.preview.scss
  src/docs/Components/Form/QuantitySelector/previews/minimal.preview.html
  src/docs/Components/Form/QuantitySelector/previews/minimal.preview.scss
  src/docs/Components/Form/QuantitySelector/previews/with-label.preview.html
  src/docs/Components/Form/QuantitySelector/previews/with-label.preview.scss
Labels: feat, scope:pattern

#679 feat(progressbar): add progress bar design
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]ProgressBar.sketch
  packages/styles/components/_c.progressbar.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.progressbar.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/progressbar.json
  src/docs/Components/ProgressBar/ProgressBar-Anatomy.png
  src/docs/Components/ProgressBar/accessibilty.mdx
  src/docs/Components/ProgressBar/code.mdx
  src/docs/Components/ProgressBar/index.mdx
  src/docs/Components/ProgressBar/previews/branded.preview.html
  src/docs/Components/ProgressBar/previews/branded.preview.scss
  src/docs/Components/ProgressBar/previews/default.preview.html
  src/docs/Components/ProgressBar/previews/default.preview.scss
  src/docs/Components/ProgressBar/previews/percentage-half.preview.html
  src/docs/Components/ProgressBar/previews/percentage-half.preview.scss
  src/docs/Components/ProgressBar/previews/percentage.preview.html
  src/docs/Components/ProgressBar/previews/percentage.preview.scss
  src/docs/Components/ProgressBar/previews/variations-colors.preview.html
  src/docs/Components/ProgressBar/previews/variations-colors.preview.scss
  src/docs/Components/ProgressBar/previews/variations-sizes.preview.html
  src/docs/Components/ProgressBar/previews/variations-sizes.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#697 refactor(onboard/accordion): update accessibility information
  src/docs/Components/Accordion/accessibilty.mdx
  src/docs/Components/Accordion/code.mdx
  src/docs/Components/Accordion/previews/basic.preview.html
  src/docs/Components/Accordion/previews/basic.preview.scss
  src/docs/Components/Accordion/previews/disable.preview.html
  src/docs/Components/Accordion/previews/disable.preview.scss
  src/docs/Components/Accordion/previews/icon.preview.html
  src/docs/Components/Accordion/previews/icon.preview.scss
  src/docs/Components/Accordion/previews/no-padding.preview.html
  src/docs/Components/Accordion/previews/no-padding.preview.scss
  src/docs/Components/Accordion/previews/open.preview.html
  src/docs/Components/Accordion/previews/open.preview.scss
  src/docs/Components/Accordion/previews/stacked.preview.html
  src/docs/Components/Accordion/previews/stacked.preview.scss
  src/docs/Components/Accordion/previews/states.preview.html
  src/docs/Components/Accordion/previews/states.preview.scss
Labels: refactor, scope:onboard

#698 refactor(onboard/breadcrumb): add the aria-current attribute on code …
  src/docs/Components/Breadcrumb/previews/dark-mode.preview.html
  src/docs/Components/Breadcrumb/previews/default.preview.html
  src/docs/Components/Breadcrumb/previews/responsive.preview.html
Labels: refactor, scope:onboard, scope:pattern

#701 fix(patterns/breadcrumb): adjust breadcrumb behavior on smaller breakpoints
  packages/styles/components/_c.breadcrumb.scss
  src/docs/Components/Breadcrumb/previews/responsive.preview.html
Labels: fix, scope:pattern

#700 feat(pattern/modal): add overflow modifier
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/accessibility.mdx
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/big-content.preview.html
Labels: feat, scope:pattern
