Repository adeo/mozaic-design-system, pull requests merged in 2020-08, with the labels that each got.

#619 fix(chore): update admzip to fix error 79 on Catalina OS
  package.json
  yarn.lock
Labels: fix, scope:chore

#625 fix(tools/tokens): update swift colors tokens
  packages/tokens/build/ios/StyleDictionaryColor.swift
Labels: fix, scope:tools

#628 fix(patterns/headings): fix responsive modifiers alignment
  packages/styles/typography/_t.headings.scss
  src/docs/Foundations/Typography/HeadingStyles/code.mdx
  src/docs/Foundations/Typography/HeadingStyles/previews/typographyHeading-underlines.preview.html
Labels: fix, scope:pattern

#629 refactor(website/toc): improve table of content styles
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/TableOfContents.js
  packages/gatsby-theme-styleguide/src/gatsby-components/TableOfContents/tableofcontents.scss
Labels: feat, scope:website
