Repository adeo/mozaic-design-system, pull requests merged in 2020-01, with the labels that each got.

#467 feat(onboard/updates): create changelog page
  packages/gatsby-github-release/gatsby-node.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/Changelog.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/__tests__/Changelog.test.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/__tests__/__snapshots__/Changelog.test.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/Changelog/index.js
  src/docs/Updates/PatternsStatus/index.mdx
  src/docs/Updates/Updates/index.mdx
Labels: feat, scope:onboard, scope:website

#464 feat(patterns/container): use LMFR‘s container as default one
  packages/styles/layouts/_l.container.scss
  src/docs/Foundations/Layout/Container/code.mdx
  src/docs/Foundations/Layout/Container/index.mdx
Labels: feat, scope:pattern, skill:design, skill:dev

#468 feat(patterns/text-input): update text-input component
  src/docs/Components/TextInput/code.mdx
  src/docs/Components/TextInput/index.mdx
  src/docs/Components/TextInput/previews/input-invalid-state.preview.html
  src/docs/Components/TextInput/previews/input-invalid.preview.html
  src/docs/Components/TextInput/previews/input-small-left-icon.preview.html
  src/docs/Components/TextInput/previews/input-small-state.preview.html
  src/docs/Components/TextInput/previews/input-state.preview.html
  src/docs/Components/TextInput/previews/left-icon-input.preview.html
Labels: feat, scope:pattern, skill:dev

#470 fix(patterns/strokes): remove typo
  src/docs/Foundations/Strokes/index.mdx
Labels: fix, scope:pattern, skill:design

#465 refactor(patterns/body styles): change body styles behavior
  src/docs/Foundations/Typography/BodyStyles/design.mdx
  src/docs/Foundations/Typography/BodyStyles/index.mdx
Labels: refactor, scope:pattern, skill:design, skill:dev

#472 fix(chore/dev build): fix unexpected and frequent process kills
  packages/gatsby-source-preview/functions.js
  packages/gatsby-source-preview/gatsby-node.js
  packages/gatsby-theme-styleguide/gatsby-node.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Preview/PreviewComponent.js
  src/docs/Components/Buttons/previews/button-icon-only.preview.html
Labels: fix, scope:chore, skill:dev

#475 fix(website/spacings): wrong var names - Fixes #474
  src/docs/Foundations/Layout/MarginAndPaddings/code.mdx
Labels: fix, scope:website
