Repository adeo/mozaic-design-system, pull requests merged in 2020-05, with the labels that each got.

#535 fix(patterns/buttons): remove some duplicate css rules
  packages/styles/components/_c.button.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.unstyle.scss
Labels: fix, scope:pattern, skill:dev

#536 fix(patterns/icons-vuejs): missing comma correction
  iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap
  iconCompiler/componentsGenerators/vueIcon.js
  packages/icons/vue/index.vue
Labels: fix, scope:pattern, skill:dev

#539 fix(patterns/rating-stars): add background-size on rating stars input
  packages/styles/components/_c.stars-input.scss
Labels: fix, scope:pattern, skill:dev

#540 feat(patterns/pagination): add pagination documentation
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Pagination.sketch
  src/docs/Components/Pagination/index.mdx
Labels: feat, scope:pattern, skill:design

#546 fix(patterns/buttons): fix regression on the color of icons
  packages/styles/components/_c.button.scss
Labels: fix, scope:pattern, skill:dev

#545 refactor(website/menu): reorganizing order in the website menu
  src/docs/Components/Checkbox/index.mdx
  src/docs/Components/Field/index.mdx
  src/docs/Components/Fields/Fields--Overview.png
  src/docs/Components/FileUploader/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Radio/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Select/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/TextArea/index.mdx
  src/docs/Components/TextInput/index.mdx
  src/docs/Components/Toggle/index.mdx
  src/docs/Foundations/AspectRatios/index.mdx
  src/docs/Foundations/BorderRadius/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Layout/index.mdx
  src/docs/Foundations/MagicUnit/index.mdx
  src/docs/Foundations/Shadows/index.mdx
  src/docs/Foundations/Strokes/index.mdx
  src/docs/Foundations/Typography/index.mdx
  src/docs/Updates/Changelog/index.mdx
Labels: refactor, scope:website

#543 refactor(patterns/buttons): disabled state fix
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Buttons.sketch
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/button.json
Labels: refactor, scope:pattern, skill:design, skill:dev

#544 feat(patterns/pagination): add pagination pattern (#540)
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Pagination.sketch
  packages/styles/components/_c.pagination.scss
  src/docs/Components/Pagination/Pagination--Specs.png
  src/docs/Components/Pagination/code.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/Pagination/previews/pagination-default.preview.html
  src/docs/Components/Pagination/previews/pagination-default.preview.scss
  src/docs/Components/Pagination/previews/pagination-light.preview.html
  src/docs/Components/Pagination/previews/pagination-light.preview.scss
  src/docs/Components/Pagination/previews/pagination.preview.html
  src/docs/Components/Pagination/previews/pagination.preview.scss
  src/docs/Components/Pagination/spec.mdx
Labels: feat, scope:pattern, skill:design, skill:dev

#549 feat(patterns/dividers): add divider pattern
  packages/styles/components/_c.divider.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.divider.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/divider.json
  src/docs/Components/Dividers/code.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/Dividers/previews/advanced.preview.html
  src/docs/Components/Dividers/previews/advanced.preview.scss
  src/docs/Components/Dividers/previews/all-variations.preview.html
  src/docs/Components/Dividers/previews/all-variations.preview.scss
  src/docs/Components/Dividers/previews/default.preview.html
  src/docs/Components/Dividers/previews/default.preview.scss
  src/docs/Components/Dividers/previews/divider-dark.preview.html
  src/docs/Components/Dividers/previews/divider-dark.preview.scss
  src/docs/Components/Dividers/previews/divider-light.preview.html
  src/docs/Components/Dividers/previews/divider-light.preview.scss
  src/docs/Components/Dividers/previews/divider-lightest.preview.html
  src/docs/Components/Dividers/previews/divider-lightest.preview.scss
  src/docs/Components/Dividers/specs.mdx
Labels: feat, scope:pattern, skill:dev

#542 feat(patterns/dividers): add dividers
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Dividers.sketch
  packages/styles/components/_c.divider.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.divider.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/divider.json
  src/docs/Components/Dividers/code.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/Dividers/previews/advanced.preview.html
  src/docs/Components/Dividers/previews/advanced.preview.scss
  src/docs/Components/Dividers/previews/all-variations.preview.html
  src/docs/Components/Dividers/previews/all-variations.preview.scss
  src/docs/Components/Dividers/previews/default.preview.html
  src/docs/Components/Dividers/previews/default.preview.scss
  src/docs/Components/Dividers/previews/divider-dark.preview.html
  src/docs/Components/Dividers/previews/divider-dark.preview.scss
  src/docs/Components/Dividers/previews/divider-light.preview.html
  src/docs/Components/Dividers/previews/divider-light.preview.scss
  src/docs/Components/Dividers/previews/divider-lightest.preview.html
  src/docs/Components/Dividers/previews/divider-lightest.preview.scss
  src/docs/Components/Dividers/specs.mdx
Labels: feat, scope:pattern, skill:design

#541 feat(patterns/cssreset): add a css reset
  packages/styles/generic/_g.reset.scss
Labels: feat, scope:pattern, skill:dev

#550 feat(pattern/disabled): add disabled cursor on pattern
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.select.scss
  packages/styles/components/_c.tag.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/components/_c.textarea.scss
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.links.scss
  src/docs/Components/FileUploader/previews/file-uploader-all-states.preview.html
Labels: feat, scope:pattern, skill:dev

#551 refactor(patterns/pagination): update aria attribute on buttons
  packages/styles/components/_c.pagination.scss
  src/docs/Components/Pagination/code.mdx
  src/docs/Components/Pagination/previews/pagination-default.preview.html
  src/docs/Components/Pagination/previews/pagination-light.preview.html
  src/docs/Components/Pagination/previews/pagination.preview.html
Labels: refactor, scope:pattern, skill:dev

#554 fix(chore): add resolutions for kind-of and minimist
  package.json
  packages/css-dev-tools/package.json
  yarn.lock
Labels: fix, scope:chore

#562 fix(chore): use adeo/httpie.action
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: fix, scope:chore
