Repository adeo/mozaic-design-system, pull requests merged in 2020-04, with the labels that each got.

#505 fix(pattern/icon): generate only path on Vue component
  iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap
  iconCompiler/componentsGenerators/__test__/index.test.js
  iconCompiler/componentsGenerators/vueIcon.js
Labels: fix

#513 refactor(pattern/icons-vuejs): generate icons as VueJS components with createElement api
  iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap
  iconCompiler/componentsGenerators/__test__/index.test.js
  iconCompiler/componentsGenerators/vueIcon.js
  iconCompiler/generateData/__tests__/__snapshots__/index.test.js.snap
  iconCompiler/generateData/lib.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconTile.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconViewer.js
  packages/icons/vue/index.vue
  src/data/icons.json
Labels: refactor, scope:chore, skill:dev

#508 chore(spellcheck): rewrite Stylelint occurrences
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Configuration/index.mdx
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
  src/docs/GetStarted/Developers/configureStylelint/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Labels: fix, scope:website

#511 chore(docs): add warning in configure PostCSS page
  src/docs/GetStarted/Developers/configurePostCss/index.mdx
Labels: fix, scope:onboard, skill:dev

#509 chore(github-pr-template): spellcheck and link fix
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix, scope:website

#518 fix(chore/github-pr-template): spellcheck and link fix (#509)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: fix, scope:chore, skill:dev

#522 fix(chore/security): fix minimist and acorn vulnerabilities
  package.json
  yarn.lock
Labels: fix

#514 fix(patterns/headings): correct some duplicate css rules
  packages/styles/settings-tools/_s.fonts-faces.scss
  packages/styles/settings-tools/_s.headings.scss
  packages/styles/typography/_t.headings.scss
Labels: fix, scope:pattern, skill:dev

#517 fix(patterns/notification): remove unnecessary css rules
  packages/styles/components/_c.notification.scss
Labels: fix, scope:pattern, skill:dev
