Repository adeo/mozaic-design-system, pull requests merged in 2020-03, with the labels that each got.

#491 feat(pattern/checkbox): add label to checkbox
  packages/styles/components/_c.checkbox.scss
  packages/styles/settings-tools/_s.checkbox.scss
  src/docs/Components/Checkbox/code.mdx
  src/docs/Components/Checkbox/previews/checkbox-state.preview.html
  src/docs/Components/Checkbox/previews/checkbox-state.preview.scss
  src/docs/Components/Checkbox/previews/intro.preview.html
  src/docs/Components/Checkbox/previews/intro.preview.scss
Labels: feat, scope:pattern

#498 fix(patterns/buttons): add pointer-events property on button label - #497
  packages/styles/components/_c.button.scss
Labels: fix, scope:pattern, skill:dev

#496 fix(pattern/magic-unit): add $mu175 variable and spell-check
  packages/styles/settings-tools/_s.magic-unit.scss
  src/docs/Foundations/MagicUnit/code.mdx
  src/docs/Foundations/MagicUnit/index.mdx
  src/docs/Foundations/MagicUnit/sheatsheat.mdx
Labels: fix, scope:pattern, skill:dev

#499 fix(website/icons): move images to static
  src/docs/Foundations/Icons/designers.mdx
Labels: fix, scope:website

#493 feat(doc/contributing): contribution journey page
  src/docs/Contributing/Principles/ContributionJourney/contribution-journey.png
  src/docs/Contributing/Principles/ContributionJourney/index.mdx
Labels: scope:website

#501 fix(pattern/ vuejs icons): change from JSX to createElement api for c…
  iconCompiler/componentsGenerators/__test__/__snapshots__/vueIcon.test.js.snap
  iconCompiler/componentsGenerators/__test__/vueIcon.test.js
  iconCompiler/componentsGenerators/vueIcon.js
  package.json
  packages/icons/vue/index.vue
  yarn.lock
Labels: fix, scope:pattern, skill:dev, test

#500 refactor(website/menu): update main menu appearance
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuHeader.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuItem.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuVersionSelect.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/__tests__/__snapshots__/MenuVersionSelect.test.js.snap
  packages/gatsby-theme-styleguide/src/gatsby-components/Search/Search.js
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  src/pages/index.scss
Labels: refactor, scope:website, skill:design, skill:dev

#504 fix(website/menu): correct the mozaic's version position
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuHeader.js
Labels: fix, scope:website, skill:dev
