Repository adeo/mozaic-design-system, pull requests merged in 2021-07, with the labels that each got.

#861 feat(styles/utilities): add a css utility class to prevent body from scrolling
  packages/styles/utilities/_u.scroll.scss
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Modals/code.mdx
Labels: feat, scope:tools, skill:dev

#864 refactor(patterns/phonenumberinput): remove the use of .mc-field__input on input tag
  src/docs/Components/Form/PhoneNumberInput/code.mdx
  src/docs/Components/Form/PhoneNumberInput/previews/label.preview.html
Labels: refactor, scope:pattern

#866 fix(patterns/tooltip): prevent side-effects when using white-space on parent elements
  packages/styles/components/_c.tooltip.scss
Labels: fix, scope:pattern

#871 feat(onboard/install): update Sass requirements on dev documentation
  src/docs/GetStarted/Developers/Installation/index.mdx
Labels: feat, scope:onboard, skill:dev

#872 feat(onboard/contributing): add the 'Quality Charter' page
  src/docs/Contributing/QualityCharter/index.mdx
Labels: feat, scope:onboard

#869 chore(gatsbyjs): upgrade Gatsby version to v3.9.1 and associated dependencies
  package.json
  packages/gatsby-github-release/package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/components/McCheckbox/styles.scss
  yarn.lock
Labels: dependencies, scope:chore, skill:dev

#873 chore(dependencies): update outdated dependencies
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/package.json
  packages/icons/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/package.json
  packages/stylelint-plugin-mozaic/package.json
  yarn.lock
Labels: dependencies, scope:chore

#874 feat(patterns/button): change background-color of the neutral button
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/button.json
Labels: feat, scope:pattern

#875 chore(husky): update husky version to 7.0.1
  .husky/.gitignore
  package.json
  yarn.lock
Labels: dependencies, scope:chore

#876 chore(tokens): update style-dictionary version to 3.0.1
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/ios/StyleDictionarySize.h
  packages/tokens/build/ios/StyleDictionarySize.m
  packages/tokens/build/ios/StyleDictionarySize.swift
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/package.json
  yarn.lock
Labels: dependencies, scope:chore

#877 fix(onboard/install): fix wrong link to the Margic Unit documentation
  src/docs/Foundations/Spacing/MagicUnit/code.mdx
Labels: fix, scope:onboard, scope:website
