Repository adeo/mozaic-design-system, pull requests merged in 2021-12, with the labels that each got.

#970 fix(website/menu): reorder pages
  src/docs/Components/Badge/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/FileUploader/index.mdx
  src/docs/Components/Form/PasswordInput/index.mdx
  src/docs/Components/Form/PhoneNumberInput/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Form/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/ProgressBar/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Stepper/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/Tooltip/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Layout/Container/index.mdx
  src/docs/Foundations/Layout/Grid/index.mdx
  src/docs/Foundations/Layout/index.mdx
  src/docs/Foundations/Spacing/MarginAndPaddings/index.mdx
  src/docs/Foundations/Spacing/index.mdx
  src/docs/Foundations/Typography/BodyStyles/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeroStyles/index.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
  src/docs/Foundations/Typography/TextColors/code.mdx
  src/docs/Foundations/Typography/TextColors/index.mdx
  src/docs/Foundations/Typography/TextColors/previews/font-colors.preview.html
  src/docs/Foundations/Typography/TextColors/previews/font-colors.preview.scss
  src/docs/Foundations/Typography/index.mdx
  src/docs/Foundations/Utilities/BorderRadius/index.mdx
  src/docs/Foundations/Utilities/Shadows/index.mdx
  src/docs/Foundations/Utilities/Strokes/index.mdx
  src/docs/Foundations/Utilities/index.mdx
Labels: fix, scope:website

#963 fix(component/quantityselector): improve the component's accessibility
  src/docs/Components/Form/QuantitySelector/accessibility.mdx
  src/docs/Components/Form/QuantitySelector/previews/basic.preview.html
  src/docs/Components/Form/QuantitySelector/previews/medium-input.preview.html
  src/docs/Components/Form/QuantitySelector/previews/minimal.preview.html
  src/docs/Components/Form/QuantitySelector/previews/with-label.preview.html
Labels: fix, scope:pattern, accessibility

#961 refactor(postcss): add react path for windows
  src/docs/GetStarted/Developers/Installation/postcss.mdx
Labels: refactor, scope:onboard

#967 fix(component/modal): adjust the margin-right behavior of the footer button
  packages/styles/components/_c.modal.scss
Labels: fix, scope:pattern

#971 refactor(home): add react logo to homepage
  packages/gatsby-theme-styleguide/src/components/Header/Header.js
Labels: refactor, scope:website

#972 chore(readme): add react and webcomponent
  README.md
Labels: refactor, scope:website, scope:onboard

#973 refactor(links): add react links to component
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/ProgressBar/index.mdx
  src/docs/Components/Tooltip/index.mdx
Labels: refactor, scope:onboard

#969 feat(patterns/badges): add usage documentation
  src/docs/Components/Badge/Badge-Options.png
  src/docs/Components/Badge/Badge-Tooltip.png
  src/docs/Components/Badge/index.mdx
  src/docs/Components/Badge/previews/badge-danger.preview.html
  src/docs/Components/Badge/previews/badge-danger.preview.scss
  src/docs/Components/Badge/previews/badge-info.preview.html
  src/docs/Components/Badge/previews/badge-info.preview.scss
  src/docs/Components/Badge/previews/badge-neutral.preview.html
  src/docs/Components/Badge/previews/badge-neutral.preview.scss
  src/docs/Components/Badge/previews/badge-success.preview.html
  src/docs/Components/Badge/previews/badge-success.preview.scss
  src/docs/Components/Badge/previews/badge-warning.preview.html
  src/docs/Components/Badge/previews/badge-warning.preview.scss
  yarn.lock
Labels: feat, scope:pattern, skill:design

#974 fix(tokens): update of the token value of some components
  packages/styles/components/_c.file-uploader.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/js/tokensObject.js
  packages/tokens/properties/color/fileuploder.json
  packages/tokens/properties/color/notification.json
  packages/tokens/properties/color/toggle.json
Labels: fix, scope:tools

#975 fix(component/checkbox): adjust the visual rendering of the checked & disabled status
  packages/styles/components/_c.checkbox.scss
  src/docs/Components/Form/Checkbox/previews/intro.preview.html
Labels: fix, scope:pattern

#977 fix(logo): change view box for logo
  packages/gatsby-theme-styleguide/src/components/Header/Header.js
Labels: fix, scope:website

#979 fix(tools/tokens): implement a custom SASS function to manage rgba colors
  packages/styles/components/_c.hero.scss
  packages/styles/components/_c.modal.scss
  packages/styles/components/_c.tabs.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.modal.scss
  packages/styles/settings-tools/_s.shadows.scss
  packages/styles/settings-tools/_t.colors.scss
  packages/tokens/actions/actions.js
  packages/tokens/build/css/_variables.scss
Labels: fix, scope:tools

#981 feat(foundations/fonts): update LeroyMerlin font with fixed Cyrillic characters
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-Bold.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-BoldItalic.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-Italic.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-Light.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-LightItalic.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-Regular.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-SemiBold.ttf
  packages/designer-kit/fonts/leroymerlinsans-web/LeroyMerlinSans-Digital-SemiBoldItalic.ttf
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Italic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Italic.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Light.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Light.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-LightItalic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-LightItalic.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Regular.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Regular.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBold.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBold.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBoldItalic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBoldItalic.woff2
  static/fonts/LeroyMerlinSans-Web-Italic.woff
  static/fonts/LeroyMerlinSans-Web-Italic.woff2
  static/fonts/LeroyMerlinSans-Web-Light.woff
  static/fonts/LeroyMerlinSans-Web-Light.woff2
  static/fonts/LeroyMerlinSans-Web-LightItalic.woff
  static/fonts/LeroyMerlinSans-Web-LightItalic.woff2
  static/fonts/LeroyMerlinSans-Web-Regular.woff
  static/fonts/LeroyMerlinSans-Web-Regular.woff2
  static/fonts/LeroyMerlinSans-Web-SemiBold.woff
  static/fonts/LeroyMerlinSans-Web-SemiBold.woff2
  static/fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff
  static/fonts/LeroyMerlinSans-Web-SemiBoldItalic.woff2
Labels: feat, scope:pattern

#983 feat(component/pagination): change the size breakpoint - xl to l
  packages/styles/components/_c.pagination.scss
Labels: feat, scope:pattern

#984 feat(component/badge): ensure that badges are always on one line
  packages/styles/settings-tools/_s.badges.scss
Labels: feat, scope:pattern

#953 feat(component/datatable): add the new DataTable component
  packages/styles/components/_c.datatable-footer.scss
  packages/styles/components/_c.datatable-header.scss
  packages/styles/components/_c.datatable-subtable.scss
  packages/styles/components/_c.datatable-tools.scss
  packages/styles/components/_c.datatable.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.datatable.scss
  src/docs/Components/DataTable/code.mdx
  src/docs/Components/DataTable/expand.mdx
  src/docs/Components/DataTable/footer.mdx
  src/docs/Components/DataTable/header.mdx
  src/docs/Components/DataTable/index.mdx
  src/docs/Components/DataTable/previews/default.preview.html
  src/docs/Components/DataTable/previews/default.preview.scss
  src/docs/Components/DataTable/previews/expanded.preview.html
  src/docs/Components/DataTable/previews/expanded.preview.scss
  src/docs/Components/DataTable/previews/footer-noselect.preview.html
  src/docs/Components/DataTable/previews/footer-noselect.preview.scss
  src/docs/Components/DataTable/previews/footer.preview.html
  src/docs/Components/DataTable/previews/footer.preview.scss
  src/docs/Components/DataTable/previews/header-edition.preview.html
  src/docs/Components/DataTable/previews/header-edition.preview.scss
  src/docs/Components/DataTable/previews/header.preview.html
  src/docs/Components/DataTable/previews/header.preview.scss
  src/docs/Components/DataTable/previews/large.preview.html
  src/docs/Components/DataTable/previews/large.preview.scss
  src/docs/Components/DataTable/previews/small.preview.html
  src/docs/Components/DataTable/previews/small.preview.scss
  src/docs/Components/DataTable/previews/sticky.preview.html
  src/docs/Components/DataTable/previews/sticky.preview.scss
Labels: feat, scope:pattern

#982 feat(component/buttons): improve the button behaviour with long label
  packages/styles/components/_c.button.scss
  packages/styles/settings-tools/_s.buttons.scss
Labels: feat, scope:pattern

#985 build(npm/scripts): update release & publish scripts name for beta version
  package.json
Labels: scope:tools, scope:chore

#986 fix(component/button): ensure that the buttons with icons keep the right height
  packages/styles/components/_c.button.scss
Labels: fix, scope:pattern
