Repository adeo/mozaic-design-system, pull requests merged in 2021-01, with the labels that each got.

#704 refactor(onboard/container): improve container documentation
  src/docs/Foundations/Layout/Container/code.mdx
  src/docs/Foundations/Layout/Container/index.mdx
Labels: refactor, scope:onboard

#705 refactor(onboard/hero): improve hero documentation
  src/docs/Components/Hero/code.mdx
Labels: refactor, scope:onboard

#706 feat(patterns/hero): add the mc-hero--boxed-l modifier
  packages/styles/components/_c.hero.scss
  src/docs/Components/Hero/code.mdx
  src/docs/Components/Hero/previews/boxed-content-l.preview.html
  src/docs/Components/Hero/previews/boxed-content-l.preview.scss
Labels: feat, scope:pattern, skill:dev

#713 feat(pattern/tags): removable tag - add text to the remove button
  packages/styles/components/_c.tag.scss
  src/docs/Components/Tag/accessibility.mdx
  src/docs/Components/Tag/code.mdx
  src/docs/Components/Tag/design.mdx
  src/docs/Components/Tag/previews/Tag.preview.html
  src/docs/Components/Tag/previews/TagRemovable.preview.html
  src/docs/Components/Tag/specs.mdx
Labels: fix, scope:pattern

#703 chore(release): remove patch keyword from release command
  package.json
Labels: scope:chore, skill:dev

#716 fix(patterns/hero): remove unnecessary z-index on hero boxed content
  packages/styles/components/_c.hero.scss
Labels: fix, scope:pattern

#715 refactor(chore/webdriverio): remove unused files and packages for visual testing
  .gitignore
  package.json
  packages/gatsby-theme-styleguide/gatsby-node.js
  src/docs/Contributing/VisualTesting/applitools-API-key.gif
  src/docs/Contributing/VisualTesting/applitools-analyse-screenshots.png
  src/docs/Contributing/VisualTesting/applitools-how-it-works.png
  src/docs/Contributing/VisualTesting/index.mdx
  test/spec/screenshots.test.js
  wdio.conf.js
  yarn.lock
Labels: refactor, scope:chore

#720 feat(pattern/hero): remove --boxed-bottom modifier
  packages/styles/components/_c.hero.scss
Labels: feat, scope:pattern

#714 fix(pattern/modal): add accessibility rules for modal opening
  src/docs/Components/Modals/accessibility.mdx
Labels: fix, scope:pattern

#722 feat(foundations/ratio): add utility and helper for ratios
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.ratio.scss
  packages/styles/utilities/_u.ratio.scss
  src/docs/Foundations/Utilities/Images/code.mdx
  src/docs/Foundations/Utilities/Images/design.mdx
  src/docs/Foundations/Utilities/Images/previews/ratio-with-helpers.preview.html
  src/docs/Foundations/Utilities/Images/previews/ratio-with-helpers.preview.scss
  src/docs/Foundations/Utilities/Images/previews/ratio-with-mixin.preview.html
  src/docs/Foundations/Utilities/Images/previews/ratio-with-mixin.preview.scss
Labels: scope:pattern, skill:dev

#723 feat(foundations/font): add a parameter to the import-font-families()…
  packages/styles/settings-tools/_s.fonts-faces.scss
  src/docs/Foundations/Typography/FontFamilies/code.mdx
Labels: feat, scope:pattern

#719 feat(pattern/tabs): add no-shadow variation
  packages/styles/components/_c.tabs.scss
  src/docs/Components/Tabs/code.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tabs/previews/tabs-no-shadow.preview.html
  src/docs/Components/Tabs/previews/tabs-no-shadow.preview.scss
Labels: feat, scope:pattern

#727 fix(chore/docker): use version 20.3.3 for pip
  ci/docker-wait/Dockerfile
Labels: refactor, scope:chore
