Repository adeo/mozaic-design-system, pull requests merged in 2021-02, with the labels that each got.

#726 feat(patterns/accordions): add small accordions variation
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Accordions.sketch
  packages/styles/components/_c.accordion.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.accordions.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  src/docs/Components/Accordion/code.mdx
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Accordion/previews/sizes.preview.html
  src/docs/Components/Accordion/previews/sizes.preview.scss
  test/previewsPath.js
Labels: scope:pattern, skill:design

#718 feat(chore): upgrade nodejs minimal version required - node12
  .github/workflows/push.yml
  .github/workflows/release.yml
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/package.json
  packages/icons/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  yarn.lock
Labels: refactor, scope:chore

#737 Revert "feat(chore/node): upgrade nodejs minimal version required - n…
  .github/workflows/push.yml
  .github/workflows/release.yml
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/package.json
  packages/icons/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  yarn.lock
Labels: scope:tools, skill:dev

#732 refactor(onboard/postcss): update PostCSS documentation for Angular
  src/docs/GetStarted/Developers/Installation/postcss.mdx
Labels: refactor, scope:onboard

#730 feat(patterns/accordion): add focus when keyboard navigation
  packages/styles/components/_c.accordion.scss
Labels: fix, scope:pattern, skill:dev

#728 refactor(pattern/checkboxes): add indeterminate case
  packages/designer-kit/sketch-libraries/leroy-merlin/[BA]Forms.sketch
  packages/styles/components/_c.checkbox.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/input.json
  src/docs/Components/Form/Checkbox/code.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Checkbox/previews/group-indeterminate.preview.html
  src/docs/Components/Form/Checkbox/previews/group-indeterminate.preview.scss
  src/docs/Components/Form/Checkbox/previews/intro.preview.html
Labels: scope:pattern, skill:design

#738 feat(patterns/notification): add small notification variation
  packages/styles/components/_c.notification.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.notification.scss
  src/docs/Components/Notification/accessibility.mdx
  src/docs/Components/Notification/code.mdx
  src/docs/Components/Notification/previews/sizes.preview.html
  src/docs/Components/Notification/previews/sizes.preview.scss
Labels: feat, scope:pattern

#741 chore(node): upgrade node version to node12
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Labels: scope:chore

#743 fix(pattern/qtyselector): remove spin button in mozilla
  packages/styles/settings-tools/_t.reset-forms.scss
Labels: fix, scope:pattern

#742 refactor(patterns/notification): update set-notification-type() mixin to handle small variation
  packages/styles/components/_c.notification.scss
  packages/styles/settings-tools/_s.notification.scss
Labels: refactor, scope:pattern

#745 feat(foundations/fonts): add font-display:swap on @font-face declarations
  packages/styles/settings-tools/_s.fonts-faces.scss
Labels: feat, scope:pattern
