Repository adeo/mozaic-design-system, pull requests merged in 2021-11, with the labels that each got.

#952 refactor(onboard): remove import-font-families from preview docs & components
  src/docs/Components/Badge/code.mdx
  src/docs/Components/Breadcrumb/code.mdx
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Cards/code.mdx
  src/docs/Components/Flags/code.mdx
  src/docs/Components/Form/Checkbox/code.mdx
  src/docs/Components/Form/Datepicker/code.mdx
  src/docs/Components/Form/Field/code.mdx
  src/docs/Components/Form/FileUploader/code.mdx
  src/docs/Components/Form/PasswordInput/code.mdx
  src/docs/Components/Form/Radio/code.mdx
  src/docs/Components/Form/Select/code.mdx
  src/docs/Components/Form/TextArea/code.mdx
  src/docs/Components/Form/TextInput/code.mdx
  src/docs/Components/Form/Toggle/code.mdx
  src/docs/Components/Hero/code.mdx
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Links/code.mdx
  src/docs/Components/Modals/code.mdx
  src/docs/Components/ProgressBar/code.mdx
  src/docs/Components/Stepper/code.mdx
  src/docs/Components/Tabs/code.mdx
  src/docs/Components/Tag/code.mdx
  src/docs/Components/Tooltip/code.mdx
  src/docs/Foundations/Layout/Grid/code.mdx
  src/docs/Foundations/Layout/Grid/customization.mdx
  src/docs/Foundations/Typography/BodyStyles/code.mdx
  src/docs/Foundations/Typography/Colors/code.mdx
  src/docs/Foundations/Typography/HeadingStyles/code.mdx
  src/docs/Foundations/Typography/HeroStyles/code.mdx
  src/docs/Foundations/Utilities/BorderRadius/code.mdx
  src/docs/Foundations/Utilities/Shadows/code.mdx
  src/docs/Foundations/Utilities/Strokes/code.mdx
Labels: refactor, scope:onboard

#950 docs(onboard/glossary): add component definition
  src/docs/Contributing/Principles/Glossary/index.mdx
Labels: scope:website, scope:onboard

#948 build(npm/scripts): added scripts to create a prerelease and a beta version
  package.json
Labels: scope:chore, skill:dev, dependencies

#939 feat(tools/purgecss): add PurgeCSS PostCSS plugin for production
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  src/docs/GetStarted/Developers/Configuration/index.mdx
Labels: feat, scope:tools

#951 refactor(onboard/glossary): reorder the glossary alphabetically
  src/docs/Contributing/Principles/Glossary/index.mdx
Labels: refactor, scope:onboard

#955 feat(tooltip): add border for a11y
  packages/styles/components/_c.tooltip.scss
Labels: feat, scope:pattern, accessibility

#959 fix(component/accordion): correct the display of the opening icon
  packages/styles/components/_c.accordion.scss
  packages/styles/settings-tools/_s.accordions.scss
  src/docs/Components/Accordion/previews/basic.preview.html
  src/docs/Components/Accordion/previews/checkbox.preview.html
  src/docs/Components/Accordion/previews/icon.preview.html
  src/docs/Components/Accordion/previews/no-padding.preview.html
  src/docs/Components/Accordion/previews/open.preview.html
  src/docs/Components/Accordion/previews/sizes.preview.html
  src/docs/Components/Accordion/previews/stacked.preview.html
  src/docs/Components/Accordion/previews/states.preview.html
  src/docs/Components/Accordion/previews/toggle.preview.html
Labels: fix, scope:pattern
