Repository adeo/mozaic-design-system, pull requests merged in 2021-06, with the labels that each got.

#759 chore(postcss): upgrade PostCSS to version 8
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  packages/postcss-media-queries-packer-on-demand/index.js
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/index.js
  packages/postcss-prepend/package.json
  packages/stylelint-plugin-mozaic/package.json
  yarn.lock
Labels: dependencies, scope:chore, skill:dev

#845 chore(babel): fix babel warning about the 'loose' option
  babel.config.js
  package.json
  packages/gatsby-theme-styleguide/package.json
  yarn.lock
Labels: dependencies, scope:chore, skill:dev

#842 feat(patterns/pagination): a11y - add aria and role attributes
  src/docs/Components/Pagination/accessibilty.mdx
  src/docs/Components/Pagination/code.mdx
  src/docs/Components/Pagination/previews/pagination-default.preview.html
  src/docs/Components/Pagination/previews/pagination-light.preview.html
  src/docs/Components/Pagination/previews/pagination.preview.html
Labels: accessibility, feat, scope:pattern

#848 refactor(patterns/modal): standardize common code between layer and modal
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.modal.scss
Labels: refactor, scope:pattern, skill:dev

#849 feat(patterns/modal): add css class .is-open & .is-visible on opening
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/big-content.preview.html
  src/docs/Components/Modals/previews/cta-link.preview.html
  src/docs/Components/Modals/previews/cta-two.preview.html
  src/docs/Components/Modals/previews/default.preview.html
  src/docs/Components/Modals/previews/opening.preview.html
  src/docs/Components/Modals/previews/withouttitle.preview.html
  yarn.lock
Labels: feat, scope:pattern, skill:dev

#853 fix(tools/stylelint): turn of the rule 'no-invalid-position-at-import-rule'
  packages/css-dev-tools/styleLintConfig.js
  yarn.lock
Labels: fix, scope:tools

#847 chore(postcss): externalize sass config & make stylelint and autoprefixer plugins
  packages/css-dev-tools/postcssPluginConfig.js
  packages/css-dev-tools/sassConfig.js
  src/docs/GetStarted/Developers/Configuration/index.mdx
Labels: feat, scope:chore

#855 refactor(patterns/modal): set pointer-events only when open
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
Labels: refactor, scope:pattern

#856 refactor(docs/vue.js): update PostCSS x Vue.js documentation
  src/docs/GetStarted/Developers/Installation/postcss.mdx
Labels: refactor, scope:onboard, scope:website

#857 feat(button): only icon usage and accessibility tab
  packages/styles/settings-tools/_s.buttons.scss
  src/docs/Components/Buttons/accessibility.mdx
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Buttons/design.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Buttons/previews/button-icon-and-text.preview.html
  src/docs/Components/Buttons/previews/button-icon-only.preview.html
  src/docs/Components/Buttons/previews/button-icon.preview.html
  src/docs/Components/Buttons/specs.mdx
Labels: feat, scope:pattern, scope:website

#858 refactor(patterns/modal): code refactor - use HTML semantic tags
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/big-content.preview.html
  src/docs/Components/Modals/previews/big-content.preview.scss
  src/docs/Components/Modals/previews/cta-link.preview.html
  src/docs/Components/Modals/previews/cta-two.preview.html
  src/docs/Components/Modals/previews/default.preview.html
  src/docs/Components/Modals/previews/opening.preview.html
  src/docs/Components/Modals/previews/withouttitle.preview.html
Labels: refactor, scope:pattern

#859 fix(patterns/accordion): increase max-height to manage long contents
  packages/styles/components/_c.accordion.scss
Labels: fix, scope:pattern
