Repository adeo/mozaic-design-system, pull requests merged in 2021-08, with the labels that each got.

#879 fix(patterns): increase css specificity in fields and breadcrumb
  packages/styles/components/_c.breadcrumb.scss
  packages/styles/components/_c.fields.scss
Labels: fix, scope:pattern, skill:dev

#881 feat(patterns/textinput): add 'cursor: pointer' property for input search
  packages/styles/settings-tools/_t.reset-forms.scss
Labels: feat, scope:pattern, skill:dev

#882 refactor(docs/help): add github link and create new help section
  packages/gatsby-theme-styleguide/jest-preprocess.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  src/docs/Help/Help/index.mdx
  src/docs/Help/ReportBug/index.mdx
  src/docs/Help/index.mdx
  src/docs/WantToHelp/index.mdx
Labels: refactor, scope:website

#884 fix(icon/balcony): rename balcony svg
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svg/Various_Balcony_32px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
Labels: fix, scope:pattern

#880 feat(layout/container): add 'box-sizing: border-box' property to .ml-container
  packages/styles/layouts/_l.container.scss
Labels: feat, scope:pattern

#894 fix(patterns/text-input): update the line-height & paddings of the component
  packages/styles/settings-tools/_s.text-input.scss
Labels: fix, scope:pattern

#897 feat(patterns/notification): add new variation w/ buttons
  packages/styles/components/_c.notification.scss
  packages/styles/settings-tools/_s.notification.scss
  src/docs/Components/Notification/code.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Notification/previews/notification-danger.preview.html
  src/docs/Components/Notification/previews/notification-success.preview.html
  src/docs/Components/Notification/previews/notification-types.preview.html
  src/docs/Components/Notification/previews/notification-variations.preview.html
  src/docs/Components/Notification/previews/notification-warning.preview.html
  src/docs/Components/Notification/previews/notification.preview.html
  src/docs/Components/Notification/previews/sizes.preview.html
  src/docs/Components/Notification/previews/with-buttons-usage.preview.html
  src/docs/Components/Notification/previews/with-buttons-usage.preview.scss
  src/docs/Components/Notification/previews/with-buttons.preview.html
  src/docs/Components/Notification/previews/with-buttons.preview.scss
Labels: feat, scope:pattern

#901 feat(patterns/passwordinput): add code and associated documentation
  packages/styles/components/_c.password-input.scss
  src/docs/Components/Form/PasswordInput/accessibilty.mdx
  src/docs/Components/Form/PasswordInput/code.mdx
  src/docs/Components/Form/PasswordInput/index.mdx
  src/docs/Components/Form/PasswordInput/previews/all-cases.preview.html
  src/docs/Components/Form/PasswordInput/previews/all-cases.preview.scss
  src/docs/Components/Form/PasswordInput/previews/default.preview.html
  src/docs/Components/Form/PasswordInput/previews/default.preview.scss
Labels: feat, scope:pattern, skill:dev
