Repository adeo/mozaic-design-system, pull requests merged in 2021-09, with the labels that each got.

#896 feat(patterns/passwordinput): add documentation
  packages/styles/components/_c.password-input.scss
  src/docs/Components/Form/PasswordInput/Password-Overview.png
  src/docs/Components/Form/PasswordInput/Password-RevealButton.png
  src/docs/Components/Form/PasswordInput/accessibilty.mdx
  src/docs/Components/Form/PasswordInput/code.mdx
  src/docs/Components/Form/PasswordInput/index.mdx
  src/docs/Components/Form/PasswordInput/previews/all-cases.preview.html
  src/docs/Components/Form/PasswordInput/previews/all-cases.preview.scss
  src/docs/Components/Form/PasswordInput/previews/default.preview.html
  src/docs/Components/Form/PasswordInput/previews/default.preview.scss
  src/docs/Components/Form/PhoneNumberInput/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
Labels: feat, scope:pattern, skill:design

#903 refactor(patterns/cards): changed outline colour to G-500
  packages/styles/components/_c.card.scss
Labels: refactor, scope:pattern, skill:design, skill:dev

#905 feat(a11y): add a mixin to hide content visually
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.visually-hidden.scss
Labels: feat, scope:tools, skill:dev

#906 chore(format/prettier): implement overrides option for .scss files
  .prettierrc
Labels: scope:chore, skill:dev

#910 feat(flex): add missing justify modifier
  packages/styles/layouts/_l.flexy.scss
Labels: feat, skill:dev

#911 fix(patterns/layer): make the layer's shadow unclickable
  packages/styles/components/_c.layer.scss
Labels: fix, scope:pattern

#895 fix(patterns/dialogs): prevent dialog elements to be focusable on modal & layer
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
Labels: fix, scope:pattern

#913 fix(patterns/toggle): update the label padding value from mixin
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_s.toggle.scss
  src/docs/Components/Form/Toggle/previews/toggle-extend-sizes.preview.html
Labels: fix, scope:pattern

#915 fix(tokens/tabs): use primary colors tokens for the tab component
  packages/tokens/build/js/tokensObject.js
  packages/tokens/properties/color/tabs.json
Labels: fix, scope:pattern, scope:tools, skill:dev

#919 feat(badge): add badge component code
  packages/styles/components/_c.badge.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.badges.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/ios/StyleDictionarySize.h
  packages/tokens/build/ios/StyleDictionarySize.m
  packages/tokens/build/ios/StyleDictionarySize.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/badge.json
  src/docs/Components/Badge/code.mdx
  src/docs/Components/Badge/index.mdx
  src/docs/Components/Badge/previews/basic.preview.html
  src/docs/Components/Badge/previews/basic.preview.scss
Labels: feat, scope:pattern

#920 feat(patterns/rating-stars): add new variations with label, link & overall score
  packages/styles/components/_c.stars-result.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.stars.scss
  src/docs/Components/RatingStars/code.mdx
  src/docs/Components/RatingStars/previews/stars-result-label-link.preview.html
  src/docs/Components/RatingStars/previews/stars-result-label-link.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-label.preview.html
  src/docs/Components/RatingStars/previews/stars-result-label.preview.scss
  src/docs/Components/RatingStars/previews/stars-result-overall.preview.html
  src/docs/Components/RatingStars/previews/stars-result-overall.preview.scss
Labels: feat, scope:pattern

#902 feat(tools/tokens): generate tokens as native css variables
  packages/tokens/actions/actions.js
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/variables.css
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/ios/StyleDictionarySize.h
  packages/tokens/build/ios/StyleDictionarySize.m
  packages/tokens/build/ios/StyleDictionarySize.swift
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/config.js
Labels: feat, scope:tools, skill:dev

#925 fix(patterns/toggle): add missing classes
  packages/gatsby-theme-styleguide/src/components/McToggle/McToggle.js
  packages/styles/components/_c.toggle.scss
Labels: fix, scope:pattern, skill:dev

#926 feat(installation): add some guidelines to add mozaic for a react pro…
  src/docs/GetStarted/Developers/Installation/postcss.mdx
Labels: feat, scope:website

#932 fix(tools/tokens): generate only color tokens as CSS variables
  packages/css-dev-tools/sassConfig.js
  packages/tokens/actions/actions.js
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/config.js
Labels: fix, scope:tools, skill:dev

#934 fix(onboard): fix typo font-families
  src/docs/Foundations/Typography/FontFamilies/code.mdx
Labels: fix, scope:onboard

#930 feat(foundations/fonts): add the Cyrillic version of LeroyMerlin webfont
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Italic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Italic.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Light.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Light.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-LightItalic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-LightItalic.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Regular.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-Regular.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBold.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBold.woff2
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBoldItalic.woff
  packages/web-fonts/cyrillic/LeroyMerlinSans-Web-SemiBoldItalic.woff2
Labels: feat, scope:pattern

#933 refactor(website/links): update links documentation
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Badge/index.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Cards/index.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/FileUploader/index.mdx
  src/docs/Components/Form/PasswordInput/index.mdx
  src/docs/Components/Form/PhoneNumberInput/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Hero/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/ProgressBar/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Stepper/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/Tooltip/index.mdx
  src/docs/Foundations/Colors/index.mdx
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Layout/Grid/index.mdx
  src/docs/Foundations/Typography/BodyStyles/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
  src/docs/Foundations/Typography/HeroStyles/index.mdx
  src/docs/Foundations/Typography/ScaleAndSizes/index.mdx
  src/docs/Foundations/Utilities/Images/index.mdx
  src/docs/Foundations/Utilities/Shadows/index.mdx
Labels: refactor, scope:onboard
