Repository adeo/mozaic-design-system, pull requests merged in 2021-05, with the labels that each got.

#814 fix(phonenumber): add white background for list
  packages/styles/components/_c.phone-number.scss
Labels: fix, scope:pattern

#816 feat(tools/token): improve and add new colors to the Adeo preset
  packages/tokens/AdeoProperties/color/base.json
Labels: scope:tools, skill:design, skill:dev

#817 refactor(onboard/tokens): improve documentation about tokens customization
  src/docs/GetStarted/Developers/CustomizeTokens/adeoPreset.mdx
  src/docs/GetStarted/Developers/CustomizeTokens/index.mdx
Labels: refactor, scope:onboard

#820 fix(pattern/tabs): add a pointer-events on tabs dropdown variation
  packages/styles/components/_c.tabs.scss
Labels: fix, scope:pattern

#818 feat(pattern/progressbar): add new size variation - xs variation
  packages/styles/components/_c.progressbar.scss
  packages/styles/settings-tools/_s.progressbar.scss
  src/docs/Components/ProgressBar/code.mdx
  src/docs/Components/ProgressBar/previews/variations-sizes.preview.html
Labels: feat, scope:pattern, skill:design, skill:dev

#822 refactor(patterns/progressbar): code & documentation refactor
  packages/styles/components/_c.progressbar.scss
  src/docs/Components/ProgressBar/code.mdx
  src/docs/Components/ProgressBar/previews/branded.preview.html
  src/docs/Components/ProgressBar/previews/default.preview.html
  src/docs/Components/ProgressBar/previews/percentage-half.preview.html
  src/docs/Components/ProgressBar/previews/percentage.preview.html
  src/docs/Components/ProgressBar/previews/variations-colors.preview.html
  src/docs/Components/ProgressBar/previews/variations-sizes.preview.html
Labels: refactor, scope:pattern

#833 fix(tools/css-dev-tools): add missing paths to the const basePaths
  packages/css-dev-tools/postcssPluginConfig.js
Labels: fix, scope:tools, skill:dev

#810 fix(docs): solve A11y issue with the left side collapsible menu
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/MenuItem.js
Labels: fix, scope:website

#834 fix(tools/sass): use the new math.div() function for divisions
  packages/gatsby-theme-styleguide/package.json
  packages/styles/components/_c.accordion.scss
  packages/styles/components/_c.stars-input.scss
  packages/styles/components/_c.stars-result.scss
  packages/styles/components/_c.tabs.scss
  packages/styles/components/_c.tag.scss
  packages/styles/settings-tools/_s.card.scss
  packages/styles/settings-tools/_s.focus.scss
  packages/styles/settings-tools/_s.fonts-scale.scss
  packages/styles/settings-tools/_s.hero.scss
  packages/styles/settings-tools/_s.magic-unit.scss
  packages/styles/settings-tools/_s.progressbar.scss
  packages/styles/settings-tools/_s.ratio.scss
  packages/styles/settings-tools/_s.toggle.scss
  packages/styles/settings-tools/_t.flexy.scss
  packages/styles/settings-tools/_t.size-units-converters.scss
  yarn.lock
Labels: fix, scope:tools

#799 feat(patterns/stepper): add stepper component
  packages/styles/components/_c.stepper.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.stepper.scss
  src/docs/Components/Stepper/Stepper--Current-step.png
  src/docs/Components/Stepper/Stepper--Step-states.png
  src/docs/Components/Stepper/accessibilty.mdx
  src/docs/Components/Stepper/code.mdx
  src/docs/Components/Stepper/index.mdx
  src/docs/Components/Stepper/previews/default.preview.html
  src/docs/Components/Stepper/previews/default.preview.scss
  src/docs/Components/Stepper/previews/three-and-more.preview.html
  src/docs/Components/Stepper/previews/three-and-more.preview.scss
  src/docs/Components/Stepper/previews/up-to-three.preview.html
  src/docs/Components/Stepper/previews/up-to-three.preview.scss
Labels: feat, scope:pattern

#841 refactor(patterns/stepper): use the new math.div() function for divisions
  packages/styles/components/_c.stepper.scss
Labels: refactor, scope:pattern
