Repository adeo/mozaic-design-system, pull requests merged in 2021-03, with the labels that each got.

#739 feat(patterns/notifications): add usage documentation
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Notification/notification-small-zoning.png
Labels: feat, scope:pattern, skill:design

#746 feat(patterns/button): improve button focus for accessibility
  packages/styles/components/_c.button.scss
  packages/styles/settings-tools/_s.buttons.scss
Labels: feat, scope:pattern

#747 fix(patterns/notification): correct the closing icon position
  packages/styles/components/_c.notification.scss
  packages/styles/settings-tools/_s.inline-icons.scss
Labels: fix, scope:pattern

#750 feat(patterns/icons): add arrow-top-16 in sass inline-icons function
  packages/styles/settings-tools/_s.inline-icons.scss
Labels: feat, scope:pattern

#751 chore(deps): bump axios from 0.19.0 to 0.21.1
  package.json
  yarn.lock
Labels: scope:chore, skill:dev

#752 refactor(patterns/button): update of the previews code
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Buttons/previews/basic.preview.html
  src/docs/Components/Buttons/previews/button-icon-and-text.preview.html
  src/docs/Components/Buttons/previews/button-icon-only.preview.html
  src/docs/Components/Buttons/previews/button-icon-position.preview.html
  src/docs/Components/Buttons/previews/button-icon.preview.html
  src/docs/Components/Buttons/previews/button-proximity-dont.preview.html
  src/docs/Components/Buttons/previews/button-sizes.preview.html
  src/docs/Components/Buttons/previews/button-state.preview.html
  src/docs/Components/Buttons/previews/button-styles.preview.html
  src/docs/Components/Buttons/previews/button-widths-responsive.preview.html
  src/docs/Components/Buttons/previews/button-widths.preview.html
  src/docs/Components/Buttons/previews/intro-bordered.preview.html
  src/docs/Components/Buttons/previews/intro.preview.html
  src/docs/Components/Buttons/previews/suportedMarkup.preview.html
Labels: refactor, scope:pattern

#753 chore(postcss): log env variable used
  packages/css-dev-tools/postcssPluginConfig.js
Labels: scope:chore, scope:tools, skill:dev

#756 chore(gatsby): update gatsbyjs version and associated dependencies
  package.json
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/gatsby-theme-styleguide/package.json
  packages/gatsby-theme-styleguide/src/components/AreaContact/index.js
  packages/gatsby-theme-styleguide/src/components/AreaDiscover/index.js
  packages/gatsby-theme-styleguide/src/components/AreaValues/index.js
  packages/gatsby-theme-styleguide/src/components/Footer/index.js
  packages/gatsby-theme-styleguide/src/components/Header/index.js
  packages/gatsby-theme-styleguide/src/components/McButton/index.js
  packages/gatsby-theme-styleguide/src/components/McCheckbox/index.js
  packages/gatsby-theme-styleguide/src/components/McTextInput/index.js
  packages/gatsby-theme-styleguide/src/components/McToggle/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/CalloutVue/index.js
  yarn.lock
Labels: scope:chore, skill:dev

#761 fix(onboard/link): fix the documentation of the link mixin
  src/docs/Components/Links/code.mdx
Labels: fix, scope:onboard

#764 feat(pattern/layer): add variation scrollbar at the layer edge
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Layers/previews/border-scroll-bar.preview.html
  src/docs/Components/Layers/previews/border-scroll-bar.preview.scss
Labels: feat, scope:pattern

#760 chore(deps): use postcss-sass instead of postcss-node-sass
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  yarn.lock
Labels: refactor, scope:chore, skill:dev

#766 fix(patterns/modal): update height and width values
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/index.mdx
Labels: fix, scope:pattern, skill:design, skill:dev

#767 fix(patterns/accordion): a11y - manage focusable elements on closed accordion
  packages/styles/components/_c.accordion.scss
  src/docs/Components/Accordion/previews/stacked.preview.html
  src/docs/Components/Accordion/previews/stacked.preview.scss
Labels: fix, scope:pattern

#724 feat(pattern/cards): add card pattern design part
  packages/styles/components/_c.card.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.card.scss
  src/docs/Components/Cards/CardsAnatomy--Mandatory.png
  src/docs/Components/Cards/code.mdx
  src/docs/Components/Cards/index.mdx
  src/docs/Components/Cards/previews/card-bordered.preview.html
  src/docs/Components/Cards/previews/card-bordered.preview.scss
  src/docs/Components/Cards/previews/card-button.preview.html
  src/docs/Components/Cards/previews/card-button.preview.scss
  src/docs/Components/Cards/previews/card-link.preview.html
  src/docs/Components/Cards/previews/card-link.preview.scss
  src/docs/Components/Cards/previews/card-ratios.preview.html
  src/docs/Components/Cards/previews/card-ratios.preview.scss
  src/docs/Components/Cards/previews/default.preview.html
  src/docs/Components/Cards/previews/default.preview.scss
  src/docs/Components/Cards/previews/two-cards.preview.html
  src/docs/Components/Cards/previews/two-cards.preview.scss
Labels: scope:pattern, skill:design

#769 refactor(chore/browserslist): implement .browserslistrc file
  .browserslistrc
  package.json
Labels: refactor, scope:chore, skill:dev

#768 chore(license): add MIT license for Mozaic
  LICENSE
Labels: scope:chore, scope:tools

#771 chore(deps): upgrade dependencies in @mozaic-ds/designsystem package
  package.json
  yarn.lock
Labels: scope:chore, skill:dev

#772 chore(deps/lerna): upgrade Lerna version to 4.0.0
  lerna.json
  package.json
  yarn.lock
Labels: scope:chore, skill:dev

#773 chore(deps/prettier): upgrade prettier version to >=2.2.1
  .prettierrc
  package.json
  yarn.lock
Labels: scope:chore, skill:dev

#776 chore(deps): upgrade resolutions dependencies
  package.json
  yarn.lock
Labels: dependencies, scope:chore

#770 fix(pattern/accordion): add transition on content
  packages/styles/components/_c.accordion.scss
Labels: fix, scope:pattern

#785 chore(ci): fix google-cloud-sdk version
  ci/docker-wait/Dockerfile
Labels: fix, scope:chore

#774 chore(deps): upgrade deps for security reason
  package.json
  yarn.lock
Labels: dependencies, scope:chore

#781 chore(deps/lint-staged): upgrade lint-staged version
  package.json
  yarn.lock
Labels: dependencies, scope:chore

#784 feat(onboard): update roadmap
  src/docs/Updates/Roadmap/index.mdx
Labels: feat, scope:onboard
