Repository adeo/mozaic-design-system, pull requests merged in 2021-04, with the labels that each got.

#786 fix(layout/grid): update ml-flexy__col--initial behaviour
  packages/styles/layouts/_l.flexy.scss
  yarn.lock
Labels: fix, scope:pattern

#790 chore(ci): use python3 and pip3 version
  ci/docker-wait/Dockerfile
Labels: fix, scope:tools

#780 feat(patterns/phonenumber): add phone number input
  packages/styles/components/_c.phone-number.scss
  src/docs/Components/Form/PhoneNumberInput/PhoneNumber-Overview.png
  src/docs/Components/Form/PhoneNumberInput/accessibility.mdx
  src/docs/Components/Form/PhoneNumberInput/code.mdx
  src/docs/Components/Form/PhoneNumberInput/index.mdx
  src/docs/Components/Form/PhoneNumberInput/previews/basic.preview.html
  src/docs/Components/Form/PhoneNumberInput/previews/basic.preview.scss
  src/docs/Components/Form/PhoneNumberInput/previews/label.preview.html
  src/docs/Components/Form/PhoneNumberInput/previews/label.preview.scss
  src/docs/Components/Form/PhoneNumberInput/previews/opened.preview.html
  src/docs/Components/Form/PhoneNumberInput/previews/opened.preview.scss
Labels: feat, scope:pattern, skill:design, skill:dev

#788 feat(patterns): a11y - standardize focus states
  packages/styles/components/_c.accordion.scss
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.links.scss
  packages/styles/components/_c.modal.scss
  packages/styles/components/_c.notification.scss
  packages/styles/components/_c.pagination.scss
  packages/styles/components/_c.quantity-selector.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.select.scss
  packages/styles/components/_c.stars-input.scss
  packages/styles/components/_c.tabs.scss
  packages/styles/components/_c.tag.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/components/_c.textarea.scss
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.focus.scss
  packages/styles/settings-tools/_s.links.scss
  packages/styles/settings-tools/_s.tag.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/focus.json
  packages/tokens/properties/color/input.json
Labels: accessibility, feat, scope:pattern

#789 fix(patterns/layers): update layer widths
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Layers/previews/extended.preview.html
  src/docs/Components/Layers/previews/extended.preview.scss
Labels: fix, scope:pattern

#795 fix(tools/tokens): fix missing tokens
  packages/styles/settings-tools/_s.focus.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/input.json
Labels: fix, scope:tools

#782 refactor(chore/husky): upgrade husky version
  .husky/.gitignore
  .husky/commit-msg
  .husky/pre-commit
  package.json
  yarn.lock
Labels: dependencies, refactor, scope:chore

#798 feat(website): redirect to https
  app.demo.yaml
  app.yaml
Labels: feat, scope:website, skill:dev

#800 refactor(website/status): update figma status
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Dividers/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/Select/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Hero/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/ProgressBar/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
  src/docs/Components/Tooltip/index.mdx
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
Labels: feat, scope:website

#796 feat(patterns/layer): add extended variation documentation
  src/docs/Components/Layers/index.mdx
Labels: feat, scope:pattern, skill:design

#792 chore(ci): remove httpie and enhance workflow
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: feat, scope:tools, skill:dev

#806 fix(patterns): focus - fix pseudo-element behaviour
  packages/styles/settings-tools/_s.focus.scss
Labels: fix, scope:pattern

#801 fix(patterns/card): unify unboxed & outlined cards width on breakpoint M
  packages/styles/components/_c.card.scss
Labels: fix, scope:pattern

#803 fix(patterns/layer): make the overlay clickable
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/previews/extended.preview.html
Labels: fix, scope:pattern

#804 fix(patterns): a11y - fix pseudo-element behaviour
  CHANGELOG.md
  lerna.json
  packages/styles/CHANGELOG.md
  packages/styles/package.json
Labels: fix, scope:pattern

#811 fix: review the Getting Started tutorial
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Labels: fix, scope:website
