Repository adeo/mozaic-design-system, pull requests merged in 2022-11, with the labels that each got.

#1243 feat(icons): delete the old index file listing the icons
  packages/icons/index.js
Labels: :rocket: feat

#1244 feat(icons/js): generate a basic typescript declaration file
  iconCompiler/generateIconsJS/index.js
  packages/icons/js/icons.d.ts
  packages/icons/package.json
Labels: :rocket: feat

#1245 feat(components/button): improve colour a11y
  packages/styles/settings-tools/_s.buttons.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/button.json
Labels: :rocket: feat, :zap: design, scope:a11y

#1254 refactor(foundations/icons): regenerate icons files for React & Svelte
  packages/icons/react/index.js
  packages/icons/svelte/icons.js
Labels: :soap: chore

#1246 fix(components/tabs): change adeo colour values
  packages/tokens/AdeoProperties/color/tabs.json
Labels: :fire_extinguisher: fix, :zap: design

#1257 docs(listbox): clean preview
  src/docs/Components/ListBox/code.mdx
  src/docs/Components/ListBox/previews/actions.preview.html
  src/docs/Components/ListBox/previews/actions.preview.scss
  src/docs/Components/ListBox/previews/default.preview.html
  src/docs/Components/ListBox/previews/default.preview.scss
  src/docs/Components/ListBox/previews/flags.preview.html
  src/docs/Components/ListBox/previews/flags.preview.scss
  src/docs/Components/ListBox/previews/icons.preview.html
  src/docs/Components/ListBox/previews/icons.preview.scss
  src/docs/Components/ListBox/previews/multiselect.preview.html
  src/docs/Components/ListBox/previews/multiselect.preview.scss
  src/docs/Components/ListBox/previews/trigger.preview.html
  src/docs/Components/ListBox/previews/trigger.preview.scss
Labels: :books: docs

#1262 fix(icons): add typescript for common
  iconCompiler/generateIconsJS/index.js
  packages/icons/js/icons.common.d.ts
  packages/icons/js/icons.d.ts
  packages/icons/svelte/icons.js
Labels: :fire_extinguisher: fix

#1265 fix(component/accordion): improve trigger button styles for scoped modules
  packages/styles/components/_c.accordion.scss
  packages/styles/settings-tools/_s.accordions.scss
  packages/styles/settings-tools/_s.unstyle.scss
  src/docs/Components/Accordion/previews/basic.preview.html
  src/docs/Components/Accordion/previews/basic.preview.scss
Labels: :fire_extinguisher: fix, scope:component

#1259 docs(components/badge): improve documentation
  src/docs/Components/Badge/index.mdx
Labels: :zap: design, :books: docs

#1267 feat(component/modal): add icon in modal header
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/header-with-icon.preview.html
  src/docs/Components/Modals/previews/header-with-icon.preview.scss
Labels: :rocket: feat, scope:component

#1271 chore(action): downgrade appengine version
  .github/workflows/release.yml
Labels: :soap: chore

#1273 fix(component/overlay): remove `cursor:pointer` on overlay
  packages/styles/settings-tools/_s.overlay.scss
Labels: :fire_extinguisher: fix, scope:component

#1274 fix(components/tabs): add the modifier `no-padding`
  packages/styles/components/_c.breadcrumb.scss
Labels: :fire_extinguisher: fix
