Repository adeo/mozaic-design-system, pull requests merged in 2022-09, with the labels that each got.

#1193 feat(component/listbox): improve the styles and documentation of the component
  packages/styles/components/_c.listbox.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.listbox.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/listbox.json
  src/docs/Components/ListBox/accessibilty.mdx
  src/docs/Components/ListBox/code.mdx
  src/docs/Components/ListBox/index.mdx
  src/docs/Components/ListBox/previews/actions.preview.html
  src/docs/Components/ListBox/previews/default.preview.html
  src/docs/Components/ListBox/previews/default.preview.scss
  src/docs/Components/ListBox/previews/flags.preview.html
  src/docs/Components/ListBox/previews/icons.preview.html
  src/docs/Components/ListBox/previews/multiselect.preview.html
  src/docs/Components/ListBox/previews/trigger.preview.html
  src/docs/Components/ListBox/previews/trigger.preview.scss
Labels: :rocket: feat, scope:component, :books: docs

#1194 fix(component/modal): styles - replace `fill-available` to `stretch`
  packages/styles/components/_c.modal.scss
Labels: :fire_extinguisher: fix, scope:component

#1195 fix(layouts/grid): make the `.ml-flexy__col` selector scopable
  packages/styles/layouts/_l.flexy.scss
Labels: :fire_extinguisher: fix

#1198 fix(component/datatable): improve datatable-actions position
  packages/styles/components/_c.datatable-header.scss
Labels: :fire_extinguisher: fix, scope:component

#1199 fix(generic/resetcss): remove the `input` tag from the scope of the `appearance:none` rule
  packages/styles/generic/_g.reset.scss
Labels: :fire_extinguisher: fix

#1201 chore(github/issues): improve the display of the bug report issue template
  .github/ISSUE_TEMPLATE/1-styleguide-bug-report.md
  .github/ISSUE_TEMPLATE/2-styleguide-feature-request.md
  .github/ISSUE_TEMPLATE/3-pattern-addition-proposal.md
  .github/ISSUE_TEMPLATE/4-pattern-bug-report.md
  .github/ISSUE_TEMPLATE/5-pattern-enhancement-proposal.md
  .github/ISSUE_TEMPLATE/6-other.md
  .github/ISSUE_TEMPLATE/BUG-REPORT.yml
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
Labels: :soap: chore

#1202 fix(docs/colours): update links
  src/docs/Foundations/Colours/migration.mdx
Labels: :fire_extinguisher: fix, :books: docs

#1209 fix(layouts/grid): improve `.ml-flexy__col` selector scopable behaviour
  packages/styles/layouts/_l.flexy.scss
Labels: :fire_extinguisher: fix, scope:component

#1188 feat(component/overlay): delete the `.mc-layer-overlay` & `.mc-modal-overlay` classes in favor of `.mc-overlay`
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Layers/previews/border-scroll-bar.preview.html
  src/docs/Components/Layers/previews/border-scroll-bar.preview.scss
  src/docs/Components/Layers/previews/cta-link.preview.html
  src/docs/Components/Layers/previews/cta-link.preview.scss
  src/docs/Components/Layers/previews/cta-two.preview.html
  src/docs/Components/Layers/previews/cta-two.preview.scss
  src/docs/Components/Layers/previews/default.preview.html
  src/docs/Components/Layers/previews/extended.preview.html
  src/docs/Components/Layers/previews/header-with-icon.preview.html
  src/docs/Components/Layers/previews/open-ltr.preview.html
  src/docs/Components/Layers/previews/scrolling-content.preview.html
  src/docs/Components/Layers/previews/scrolling-content.preview.scss
  src/docs/Components/Layers/previews/without-footer.preview.html
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/opening.preview.html
  src/docs/Components/Modals/previews/opening.preview.scss
Labels: :rocket: feat, scope:component, BREAKING CHANGE, @next

#1211 docs(autocomplete): add checkbox import
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.scss
Labels: :books: docs

#1213 fix(component/layer): Improve the scoping of the `is-open` state class
  packages/styles/components/_c.layer.scss
Labels: :fire_extinguisher: fix
