Repository adeo/mozaic-design-system, pull requests merged in 2022-03, with the labels that each got.

#1048 docs(colours): add link to adeo preset
  src/docs/Foundations/Colours/adeo.mdx
  src/docs/Foundations/Colours/index.mdx
Labels: scope:onboard

#1050 refactor(website/sitemapdata): remove unused keys in the SiteMapData query
  packages/css-dev-tools/postcssPluginConfig.js
  packages/gatsby-theme-styleguide/src/gatsby-components/SiteMapData/SiteMapData.js
Labels: refactor, scope:website

#1064 refactor(component/accordion): change the way the trigger input is hidden
  packages/styles/components/_c.accordion.scss
Labels: refactor, scope:component

#1063 feat(components/layer): update the padding value of the `.mc-layer__content` element
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/previews/cta-link.preview.scss
  src/docs/Components/Layers/previews/cta-two.preview.scss
  src/docs/Components/Layers/previews/default.preview.scss
  src/docs/Components/Layers/previews/extended.preview.scss
  src/docs/Components/Layers/previews/header-with-icon.preview.scss
  src/docs/Components/Layers/previews/without-footer.preview.scss
Labels: feat, scope:component

#1058 fix(tools/stylelint): turn off the rule `max-line-length`
  packages/css-dev-tools/styleLintConfig.js
  yarn.lock
Labels: scope:tools

#1060 feat(component/loader): add the new Loader component
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.loader.scss
  packages/styles/components/_c.modal.scss
  packages/styles/components/_c.overlay.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.loader.scss
  packages/styles/settings-tools/_s.modal.scss
  packages/styles/settings-tools/_s.overlay.scss
  src/docs/Components/Loader/code.mdx
  src/docs/Components/Loader/index.mdx
  src/docs/Components/Loader/overlay.mdx
  src/docs/Components/Loader/previews/default.preview.html
  src/docs/Components/Loader/previews/default.preview.scss
  src/docs/Components/Loader/previews/opening.preview.html
  src/docs/Components/Loader/previews/opening.preview.scss
  src/docs/Components/Loader/previews/overlay-text.preview.html
  src/docs/Components/Loader/previews/overlay-text.preview.scss
  src/docs/Components/Loader/previews/overlay.preview.html
  src/docs/Components/Loader/previews/overlay.preview.scss
  src/docs/Components/Loader/previews/sizes.preview.html
  src/docs/Components/Loader/previews/sizes.preview.scss
  src/docs/Components/Loader/previews/themes.preview.html
  src/docs/Components/Loader/previews/themes.preview.scss
Labels: feat, scope:component

#921 feat(components/modal): update paddings values
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/big-content.preview.html
  src/docs/Components/Modals/previews/big-content.preview.scss
  src/docs/Components/Modals/previews/cta-link.preview.html
  src/docs/Components/Modals/previews/cta-link.preview.scss
  src/docs/Components/Modals/previews/cta-two.preview.html
  src/docs/Components/Modals/previews/cta-two.preview.scss
  src/docs/Components/Modals/previews/default.preview.html
  src/docs/Components/Modals/previews/default.preview.scss
  src/docs/Components/Modals/previews/delete-action.preview.html
  src/docs/Components/Modals/previews/delete-action.preview.scss
  src/docs/Components/Modals/previews/opening.preview.html
  src/docs/Components/Modals/previews/opening.preview.scss
  src/docs/Components/Modals/previews/withouttitle.preview.html
  src/docs/Components/Modals/previews/withouttitle.preview.scss
  yarn.lock
Labels: fix, scope:pattern, skill:dev

#1067 fix(tools/stylelint): turn off some new stylelint rules
  packages/css-dev-tools/styleLintConfig.js
Labels: fix, scope:tools

#1071 fix(icons): fix ts for react icons
  iconCompiler/componentsGenerators/index.js
  packages/icons/react/index.d.ts
Labels: fix

#1072 feat(tools/tokens): add the new Bricoman preset
  packages/gatsby-theme-styleguide/src/components/McButton/styles.scss
  packages/gatsby-theme-styleguide/src/components/McCheckbox/styles.scss
  packages/gatsby-theme-styleguide/src/components/McToggle/styles.scss
  packages/tokens/BricomanProperties/color/base.json
  packages/tokens/BricomanProperties/color/button.json
  packages/tokens/BricomanProperties/color/input.json
  packages/tokens/BricomanProperties/color/link.json
  packages/tokens/BricomanProperties/color/toggle.json
  packages/tokens/BricomanProperties/preset.json
  packages/tokens/config.js
  yarn.lock
Labels: feat, scope:tools

#1076 docs(colours): add link from the preset doc to the colour doc
  src/docs/Foundations/Colours/adeo.mdx
  src/docs/GetStarted/Developers/CustomizeTokens/adeoPreset.mdx
Labels: scope:onboard

#1082 feat(tools/tokens): update of ADEO colours for buttons, flags & links
  packages/tokens/AdeoProperties/color/button.json
  packages/tokens/AdeoProperties/color/flag.json
  packages/tokens/AdeoProperties/color/link.json
Labels: scope:tools

#1078 feat(dropdown): add dropdown
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Dropdown/accessibility.mdx
  src/docs/Components/Form/Dropdown/code.mdx
  src/docs/Components/Form/Dropdown/index.mdx
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/default.preview.scss
  src/docs/Components/Form/Dropdown/previews/disabled.preview.html
  src/docs/Components/Form/Dropdown/previews/disabled.preview.scss
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.scss
Labels: feat, scope:component

#1080 feat(autocomplete): add autocomplete component
  packages/styles/components/_c.autocomplete.scss
  src/docs/Components/Form/Autocomplete/accessibility.mdx
  src/docs/Components/Form/Autocomplete/code.mdx
  src/docs/Components/Form/Autocomplete/index.mdx
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/default.preview.scss
  src/docs/Components/Form/Autocomplete/previews/disabled.preview.html
  src/docs/Components/Form/Autocomplete/previews/disabled.preview.scss
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.scss
  src/docs/Components/ListBox/previews/default.preview.html
Labels: scope:component

#1083 fix(listbox): clean broken preview
  src/docs/Components/ListBox/previews/default.preview.html
Labels: fix

#1066 refactor(gatsby/pattern-page): remove unused keys in the MDXQuery
  packages/gatsby-theme-styleguide/src/templates/pattern-page.js
Labels: refactor, scope:website
