Repository adeo/mozaic-design-system, pull requests merged in 2022-07, with the labels that each got.

#1164 feat(foundations/colours): update colour tokens
  packages/tokens/AdeoProperties/color/base.json
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/base.json
  src/docs/Foundations/Colours/index.mdx
Labels: :rocket: feat, :zap: design

#1161 docs(components/tooltip): improve documentation
  src/docs/Components/Tooltip/Tooltip--WithoutPointer.png
  src/docs/Components/Tooltip/index.mdx
Labels: :zap: design, :books: docs

#1155 feat(tools/postcss-sass)!: use `csstools/postcss-sass` instead of `@mozaic-ds/postcss-sass`
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  yarn.lock
Labels: :rocket: feat, BREAKING CHANGE, scope:tools, @next, dependencies

#1157 feat(tools): update the dependencies and the code of the `@mozaic-ds/stylelint-plugin-mozaic` package
  packages/stylelint-plugin-mozaic/README.md
  packages/stylelint-plugin-mozaic/index.js
  packages/stylelint-plugin-mozaic/index.test.js
  packages/stylelint-plugin-mozaic/jest.config.js
  packages/stylelint-plugin-mozaic/lib/getSelectors.js
  packages/stylelint-plugin-mozaic/package-lock.json
  packages/stylelint-plugin-mozaic/package.json
  yarn.lock
Labels: :rocket: feat, scope:tools, @next

#1168 docs(foundations/colours): update colour swatches
  packages/tokens/buildAdeo/js/tokens.js
  packages/tokens/buildAdeo/js/tokensObject.js
  src/docs/Foundations/Colours/adeo.mdx
Labels: scope:website, :zap: design, :books: docs

#1092 feat(rating): use new icons
  packages/styles/components/_c.stars-input.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.stars.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/star.json
Labels: :rocket: feat, :sparkles: refactor

#1174 fix(component/accordion): improve styles to handle nested accordions
  packages/styles/components/_c.accordion.scss
  packages/styles/settings-tools/_s.accordions.scss
  yarn.lock
Labels: :fire_extinguisher: fix, scope:component
