Repository adeo/mozaic-design-system, pull requests merged in 2022-04, with the labels that each got.

#1088 fix(listbox): enhance left opening
  packages/styles/components/_c.listbox.scss
Labels: :fire_extinguisher: fix

#1087 fix(component/toggle): maintain the input position within the component
  packages/styles/components/_c.toggle.scss
Labels: :fire_extinguisher: fix, scope:component

#1094 docs(refactor/flags): update HTML code in previews
  src/docs/Components/Flags/previews/bordered.preview.html
  src/docs/Components/Flags/previews/flag-all.preview.html
  src/docs/Components/Flags/previews/solid.preview.html
Labels: :sparkles: refactor, :books: docs

#1098 feat(component/breadcrumb): remove `padding-left` & dark `background-color`
  packages/styles/components/_c.breadcrumb.scss
  src/docs/Components/Breadcrumb/previews/dark-mode.preview.scss
Labels: :rocket: feat, scope:component, BREAKING CHANGE

#1104 fix(pattern/colors): update the color of the notification icons
  packages/tokens/properties/color/notification.json
Labels: :fire_extinguisher: fix

#1111 fix(dropdown): add arrow up when dropdown is open
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
Labels: :fire_extinguisher: fix

#1112 feat(component/layer/modal): add divider under the header
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/previews/big-content.preview.html
  src/docs/Components/Modals/previews/big-content.preview.scss
  src/docs/Components/Modals/previews/cta-link.preview.html
  src/docs/Components/Modals/previews/cta-link.preview.scss
  src/docs/Components/Modals/previews/cta-two.preview.html
  src/docs/Components/Modals/previews/cta-two.preview.scss
  src/docs/Components/Modals/previews/default.preview.html
  src/docs/Components/Modals/previews/default.preview.scss
  src/docs/Components/Modals/previews/delete-action.preview.html
  src/docs/Components/Modals/previews/delete-action.preview.scss
  src/docs/Components/Modals/previews/opening.preview.html
  src/docs/Components/Modals/previews/opening.preview.scss
  src/docs/Components/Modals/previews/withouttitle.preview.html
  src/docs/Components/Modals/previews/withouttitle.preview.scss
Labels: :rocket: feat, scope:component

#1113 chore(licence): use APACHE licence
  LICENSE
  NOTICE
Labels: :soap: chore

#1115 feat(component/layer): allow the layer to open from the left to the right
  packages/styles/components/_c.layer.scss
  src/docs/Components/Layers/code.mdx
  src/docs/Components/Layers/previews/open-ltr.preview.html
  src/docs/Components/Layers/previews/open-ltr.preview.scss
Labels: :rocket: feat, scope:component

#1114 feat(listbox): add flags preview
  packages/styles/components/_c.listbox.scss
  src/docs/Components/ListBox/index.mdx
  src/docs/Components/ListBox/previews/flags.preview.html
  src/docs/Components/ListBox/previews/flags.preview.scss
Labels: :rocket: feat, scope:component

#1116 feat(component/tag): update tags colors
  packages/styles/components/_c.tag.scss
  packages/styles/settings-tools/_s.tag.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/tag.json
Labels: :rocket: feat, scope:component
