Repository adeo/mozaic-design-system, pull requests merged in 2022-05, with the labels that each got.

#1118 feat(foundations/icons): add color icons in the `icons.js` file
  iconCompiler/index.js
  packages/icons/js/icons.js
Labels: :rocket: feat

#1119 refactor(component/accordion): implement sass math.div
  packages/styles/settings-tools/_s.accordions.scss
Labels: :sparkles: refactor

#1125 feat(phonenumber): use emoji flags
  packages/styles/components/_c.phone-number.scss
  src/docs/Components/Form/PhoneNumberInput/previews/basic.preview.html
  src/docs/Components/Form/PhoneNumberInput/previews/label.preview.html
  src/docs/Components/Form/PhoneNumberInput/previews/opened.preview.html
Labels: :rocket: feat, :sparkles: refactor

#1129 feat(foundations/icons): icons.js - implement a better management of colored icons
  iconCompiler/generateIconsJS/iconsModules.js
  packages/icons/js/icons.js
Labels: :rocket: feat
