Repository adeo/mozaic-design-system, pull requests merged in 2022-08, with the labels that each got.

#1179 fix(foundation/colours): change primary-02-100 token value
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/base.json
Labels: :fire_extinguisher: fix, :zap: design

#1186 feat(icons): add id type for logos
  iconCompiler/generateIconsJS/iconsModules.js
  packages/icons/js/icons.js
Labels: :rocket: feat

#1185 fix(patterns/icons): generate usable react icon with @babel/preset-react
  iconCompiler/componentsGenerators/index.js
Labels: :fire_extinguisher: fix

#1190 chore(icons): build react icons with babel
  packages/icons/react/index.js
Labels: :soap: chore

#1192 fix(component/option-card): manage the use of the @at-root selector differently
  packages/styles/components/_c.option-card.scss
  packages/styles/settings-tools/_t.selectors.scss
Labels: :fire_extinguisher: fix, scope:component
