Repository adeo/mozaic-design-system, pull requests merged in 2022-12, with the labels that each got.

#1277 feat(component/dropdown): improve component styles & documentation
  packages/styles/components/_c.dropdown.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.dropdown.scss
  src/docs/Components/Form/Dropdown/code.mdx
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/default.preview.scss
  src/docs/Components/Form/Dropdown/previews/disabled.preview.html
  src/docs/Components/Form/Dropdown/previews/disabled.preview.scss
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.scss
Labels: :rocket: feat, scope:component

#1264 feat(components/datepicker): add new types
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Datepicker/previews/datetime-local.preview.html
  src/docs/Components/Form/Datepicker/previews/datetime-local.preview.scss
  src/docs/Components/Form/Datepicker/previews/month.preview.html
  src/docs/Components/Form/Datepicker/previews/month.preview.scss
  src/docs/Components/Form/Datepicker/previews/time.preview.html
  src/docs/Components/Form/Datepicker/previews/time.preview.scss
  src/docs/Components/Form/Datepicker/previews/week.preview.html
  src/docs/Components/Form/Datepicker/previews/week.preview.scss
Labels: :rocket: feat, :books: docs

#1282 style(component/badge): line-height update + code improvement
  packages/styles/components/_c.badge.scss
  packages/styles/settings-tools/_s.badges.scss
Labels: :sparkles: refactor, scope:component, perf

#1284 feat(component/option-card): add variation with `disabled` state
  packages/styles/components/_c.option-card.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/option-card.json
  src/docs/Components/OptionGroup/OptionCard/code.mdx
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.scss
Labels: :rocket: feat, scope:component

#1286 feat(components/form): update icons for `valid` & `invalid` states on form elements
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.quantity-selector.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.select.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/components/_c.toggle.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/styles/settings-tools/_s.select.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/input.json
  packages/tokens/properties/color/toggle.json
  src/docs/Components/Form/Autocomplete/code.mdx
  src/docs/Components/Form/Autocomplete/previews/invalid.preview.html
  src/docs/Components/Form/Autocomplete/previews/invalid.preview.scss
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
Labels: :rocket: feat, scope:component

#1291 fix(component/starsinput): fix the display of stars in `s`, `l` & `xl` variations
  packages/styles/components/_c.stars-input.scss
Labels: :fire_extinguisher: fix

#1293 fix(components/autocomplete-dropdown): adjust the padding-right value according to the clear button
  packages/styles/components/_c.autocomplete.scss
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Autocomplete/code.mdx
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/disabled.preview.html
  src/docs/Components/Form/Autocomplete/previews/invalid.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/code.mdx
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/disabled.preview.html
  src/docs/Components/Form/Dropdown/previews/invalid.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
Labels: :fire_extinguisher: fix, scope:component

#1294 fix(component/option-card): make the content element height's suitable to the parent
  packages/styles/components/_c.option-card.scss
  src/docs/Components/OptionGroup/OptionCard/code.mdx
  src/docs/Components/OptionGroup/OptionCard/previews/withcontent.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/withcontent.preview.scss
Labels: :fire_extinguisher: fix

#1258 feat(icons): remove base64 transformation
  packages/css-dev-tools/postcssPluginConfig.js
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.modal.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.stars-input.scss
  packages/styles/settings-tools/_s.inline-icons.scss
  packages/tokens/CHANGELOG.md
  src/docs/Components/Flags/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/withButton.preview.scss
  src/docs/Components/Tabs/previews/tabs-dropdown.preview.scss
  src/docs/Components/Tabs/previews/tabs-with-icons.preview.scss
  src/docs/GetStarted/Developers/Installation/postcss.mdx
Labels: scope:tools, @next

#1296 style(component/card): improve content space & fluid variation
  packages/styles/components/_c.card.scss
Labels: :sparkles: refactor, scope:component

#1298 chore(package): clean package.json
  README.md
  package.json
  packages/gatsby-theme-styleguide/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/package.json
  packages/stylelint-plugin-mozaic/package.json
  packages/styles/package.json
  packages/tokens/package.json
  src/docs/GetStarted/Developers/Installation/import.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Labels: :soap: chore, @next

#1305 build(npm/scripts): update npm script to release rc
  package.json
Labels: :soap: chore, @next

#1300 feat(component/autocomplete-dropdown): add the `clearable` modifier to manage the display of the clear button
  packages/styles/components/_c.autocomplete.scss
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Autocomplete/code.mdx
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/invalid.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/code.mdx
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/invalid.preview.html
  src/docs/Components/Form/Dropdown/previews/invalid.preview.scss
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.scss
Labels: :rocket: feat, scope:component

#1301 refactor(states): remove demo state classes and previews
  packages/styles/components/_c.button.scss
  packages/styles/components/_c.checkbox.scss
  packages/styles/components/_c.dropdown.scss
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.radio.scss
  packages/styles/components/_c.select.scss
  packages/styles/components/_c.text-input.scss
  packages/styles/components/_c.textarea.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.buttons.scss
  packages/styles/settings-tools/_s.links.scss
  packages/styles/settings-tools/_t.demo-state-class.scss
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Buttons/code.mdx
  src/docs/Components/Buttons/previews/button-state.preview.html
  src/docs/Components/Buttons/previews/button-state.preview.scss
  src/docs/Components/Form/FileUploader/code.mdx
  src/docs/Components/Form/FileUploader/previews/all-states.preview.html
  src/docs/Components/Form/FileUploader/previews/all-states.preview.scss
  src/docs/Components/Form/TextInput/code.mdx
  src/docs/Components/Form/TextInput/previews/input-default-event.preview.html
  src/docs/Components/Form/TextInput/previews/input-default-event.preview.scss
  src/docs/Components/Form/TextInput/previews/input-disabled-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-disabled-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-focus-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-focus-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-hover-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-hover-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-invalid-event.preview.html
  src/docs/Components/Form/TextInput/previews/input-invalid-event.preview.scss
  src/docs/Components/Form/TextInput/previews/input-invalid-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-invalid-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-invalid.preview.html
  src/docs/Components/Form/TextInput/previews/input-invalid.preview.scss
  src/docs/Components/Form/TextInput/previews/input-preview.preview.html
  src/docs/Components/Form/TextInput/previews/input-preview.preview.scss
  src/docs/Components/Form/TextInput/previews/input-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-valid-event.preview.html
  src/docs/Components/Form/TextInput/previews/input-valid-event.preview.scss
  src/docs/Components/Form/TextInput/previews/input-valid-state.preview.html
  src/docs/Components/Form/TextInput/previews/input-valid-state.preview.scss
  src/docs/Components/Form/TextInput/previews/input-valid.preview.html
  src/docs/Components/Form/TextInput/previews/input-valid.preview.scss
  src/docs/Components/Links/code.mdx
  src/docs/Components/Links/previews/link-state.preview.html
  src/docs/Components/Links/previews/link-state.preview.scss
Labels: :sparkles: refactor, @next

#1306 fix(component/datatable): improve the overflow behaviour of the datatable
  packages/styles/components/_c.datatable.scss
Labels: :fire_extinguisher: fix, scope:component

#1312 feat(component/autocomplete-dropdown): update the position of the loader
  packages/styles/components/_c.autocomplete.scss
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/default.preview.scss
  src/docs/Components/Form/Autocomplete/previews/multi.preview.scss
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/default.preview.scss
  src/docs/Components/Form/Dropdown/previews/invalid.preview.scss
Labels: :rocket: feat, scope:component

#1311 docs(links): update links
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/DataTable/index.mdx
  src/docs/Components/Form/Autocomplete/index.mdx
  src/docs/Components/Form/Dropdown/index.mdx
  src/docs/Components/Form/PasswordInput/index.mdx
  src/docs/Components/Form/PhoneNumberInput/index.mdx
  src/docs/Components/Heading/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/ListBox/index.mdx
  src/docs/Components/Loader/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/OptionGroup/OptionButton/index.mdx
  src/docs/Components/OptionGroup/OptionCard/index.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Stepper/index.mdx
  src/docs/Components/Tabs/index.mdx
  src/docs/Components/Tag/index.mdx
Labels: :books: docs, @next

#1309 feat(tools/stylelint-plugin-mozaic): remove unused `postcss-bem-linter` plugin
  packages/stylelint-plugin-mozaic/package.json
  yarn.lock
Labels: scope:tools, :soap: chore, @next
