Repository adeo/mozaic-design-system, pull requests merged in 2022-01, with the labels that each got.

#988 docs(component/heading): move to component category and improve the documentation
  src/docs/Components/Heading/Headings--Zoning.png
  src/docs/Components/Heading/code.mdx
  src/docs/Components/Heading/index.mdx
  src/docs/Components/Heading/previews/Heading-alignment.preview.html
  src/docs/Components/Heading/previews/Heading-alignment.preview.scss
  src/docs/Components/Heading/previews/Heading-base.preview.html
  src/docs/Components/Heading/previews/Heading-base.preview.scss
  src/docs/Components/Heading/previews/Heading-colors.preview.html
  src/docs/Components/Heading/previews/Heading-colors.preview.scss
  src/docs/Components/Heading/previews/Heading-sizes.preview.html
  src/docs/Components/Heading/previews/Heading-sizes.preview.scss
  src/docs/Components/Heading/previews/Heading-underlines.preview.html
  src/docs/Components/Heading/previews/Heading-underlines.preview.scss
  src/docs/Components/Heading/previews/Heading-weight.preview.html
  src/docs/Components/Heading/previews/Heading-weight.preview.scss
  src/docs/Components/Heading/previews/HeadingLarge.preview.html
  src/docs/Components/Heading/previews/HeadingLarge.preview.scss
  src/docs/Components/Heading/previews/HeadingMedium.preview.html
  src/docs/Components/Heading/previews/HeadingMedium.preview.scss
  src/docs/Components/Heading/previews/HeadingSmall.preview.html
  src/docs/Components/Heading/previews/HeadingSmall.preview.scss
  src/docs/Foundations/Typography/HeadingStyles/index.mdx
Labels: feat, fix, scope:pattern

#989 docs(website/spelling): remove typos
  src/docs/Components/Accordion/index.mdx
  src/docs/Components/Badge/index.mdx
  src/docs/Components/Breadcrumb/index.mdx
  src/docs/Components/Buttons/index.mdx
  src/docs/Components/Cards/index.mdx
  src/docs/Components/DataTable/index.mdx
  src/docs/Components/Flags/index.mdx
  src/docs/Components/Form/Checkbox/index.mdx
  src/docs/Components/Form/Datepicker/index.mdx
  src/docs/Components/Form/Field/index.mdx
  src/docs/Components/Form/FileUploader/index.mdx
  src/docs/Components/Form/QuantitySelector/index.mdx
  src/docs/Components/Form/Radio/index.mdx
  src/docs/Components/Form/TextArea/index.mdx
  src/docs/Components/Form/TextInput/index.mdx
  src/docs/Components/Form/Toggle/index.mdx
  src/docs/Components/Hero/index.mdx
  src/docs/Components/Layers/index.mdx
  src/docs/Components/Links/index.mdx
  src/docs/Components/Notification/index.mdx
  src/docs/Components/RatingStars/index.mdx
  src/docs/Components/Tabs/index.mdx
Labels: fix, scope:website

#990 fix(pattern/pagination): change margin to 16px
  packages/styles/components/_c.pagination.scss
Labels: fix, skill:design, skill:dev

#993 feat(component/pagination): add the new 'compact' variation
  packages/styles/components/_c.pagination.scss
  src/docs/Components/Pagination/code.mdx
  src/docs/Components/Pagination/index.mdx
  src/docs/Components/Pagination/previews/pagination-compact.preview.html
  src/docs/Components/Pagination/previews/pagination-compact.preview.scss
Labels: feat, scope:pattern

#987 docs(readme): update readme.md
  README.md
Labels: [ W I P ]

#994 fix(component/accordion): allow title to go to line on small screens
  packages/styles/components/_c.accordion.scss
  src/docs/Components/Accordion/previews/stacked.preview.html
Labels: fix, scope:pattern

#1005 chore(dependencies): upgrade outdated dependencies
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  yarn.lock
Labels: dependencies

#1004 chore(node): upgrade node version to node16
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  yarn.lock
Labels: dependencies

#1000 docs(website/contact): improve contact page
  src/docs/Help/Help/index.mdx
Labels: refactor, scope:onboard

#999 feat(pattern/colors): add new LeroyMerlin colours
  packages/styles/components/_c.stepper.scss
  packages/styles/components/_c.tag.scss
  packages/styles/settings-tools/_s.notification.scss
  packages/styles/settings-tools/_s.stepper.scss
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/base.json
  packages/tokens/properties/color/button.json
  packages/tokens/properties/color/flag.json
  packages/tokens/properties/color/font.json
  packages/tokens/properties/color/link.json
  packages/tokens/properties/color/notification.json
  packages/tokens/properties/color/tabs.json
  packages/tokens/properties/color/tag.json
Labels: scope:pattern

#1001 docs(component/heading): remove unecessary text
  src/docs/Components/Heading/index.mdx
Labels: fix, scope:website

#1014 chore(dependencies): upgrade outdated dependencies
  yarn.lock
Labels: dependencies

#1015 docs(menu): limit to last 20 versions
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
Labels: scope:onboard, scope:chore

#1016 chore(secu): add http header
  app.demo.yaml
  app.yaml
Labels: scope:website, scope:chore
