Repository adeo/mozaic-design-system, pull requests merged in 2022-02, with the labels that each got.

#1018 feat(pattern/font): set the Roboto font-family when using the Adeo preset
  packages/styles/settings-tools/_s.fonts-faces.scss
Labels: feat, scope:pattern

#1019 docs(build): remove unnecessary secu rules for PR
  app.demo.yaml
Labels: scope:website, skill:dev

#992 feat(pattern/optiongroup): add component
  packages/styles/components/_c.option-button.scss
  packages/styles/components/_c.option-card.scss
  src/docs/Components/OptionGroup/OptionButton/code.mdx
  src/docs/Components/OptionGroup/OptionButton/index.mdx
  src/docs/Components/OptionGroup/OptionButton/previews/default.preview.html
  src/docs/Components/OptionGroup/OptionButton/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionButton/previews/width.preview.html
  src/docs/Components/OptionGroup/OptionButton/previews/width.preview.scss
  src/docs/Components/OptionGroup/OptionCard/Option-card.png
  src/docs/Components/OptionGroup/OptionCard/code.mdx
  src/docs/Components/OptionGroup/OptionCard/index.mdx
  src/docs/Components/OptionGroup/OptionCard/previews/centered.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/centered.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/delivery.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/delivery.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/product.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/product.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.scss
  src/docs/Components/OptionGroup/index.mdx
Labels: feat, scope:pattern, skill:design, skill:dev

#991 feat(pattern/datatable): Add usage documentation
  app.demo.yaml
  src/docs/Components/DataTable/index.mdx
  src/docs/Components/DataTable/previews/default.preview.html
  src/docs/Components/DataTable/previews/footer-only.preview.html
  src/docs/Components/DataTable/previews/footer-only.preview.scss
  src/docs/Components/DataTable/previews/header-only.preview.html
  src/docs/Components/DataTable/previews/header-only.preview.scss
Labels: feat, scope:pattern, skill:design

#1006 fix(component/breadcrumb): correct the size of the breadcrumb links
  packages/styles/components/_c.breadcrumb.scss
  packages/styles/components/_c.links.scss
  packages/styles/settings-tools/_s.links.scss
  src/docs/Components/Breadcrumb/code.mdx
  src/docs/Components/Breadcrumb/previews/dark-mode.preview.html
  src/docs/Components/Breadcrumb/previews/default.preview.html
  src/docs/Components/Breadcrumb/previews/mobile.preview.html
  src/docs/Components/Breadcrumb/previews/responsive.preview.html
  src/docs/Components/Links/code.mdx
Labels: fix, scope:pattern

#1020 chore(script): add script for release candidate
  app.demo.yaml
  app.yaml
  package.json
  packages/gatsby-theme-styleguide/src/gatsby-components/Menu/Menu.js
  packages/styles/components/_c.option-button.scss
  packages/styles/components/_c.option-card.scss
  packages/styles/settings-tools/_s.fonts-faces.scss
  src/docs/Components/Heading/index.mdx
  src/docs/Components/Modals/index.mdx
  src/docs/Components/Modals/previews/delete-action.preview.html
  src/docs/Components/Modals/previews/delete-action.preview.scss
  src/docs/Components/OptionGroup/OptionButton/code.mdx
  src/docs/Components/OptionGroup/OptionButton/index.mdx
  src/docs/Components/OptionGroup/OptionButton/previews/default.preview.html
  src/docs/Components/OptionGroup/OptionButton/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionButton/previews/width.preview.html
  src/docs/Components/OptionGroup/OptionButton/previews/width.preview.scss
  src/docs/Components/OptionGroup/OptionCard/Option-card.png
  src/docs/Components/OptionGroup/OptionCard/code.mdx
  src/docs/Components/OptionGroup/OptionCard/index.mdx
  src/docs/Components/OptionGroup/OptionCard/previews/centered.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/centered.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/checkbox.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/default.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/delivery.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/delivery.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/product.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/product.preview.scss
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.html
  src/docs/Components/OptionGroup/OptionCard/previews/small.preview.scss
  src/docs/Components/OptionGroup/index.mdx
Labels: @next

#1021 fix(release): remove duplicate from app.yaml
  app.yaml
Labels: fix, scope:chore

#995 feat(component/flag): improve long text flag behaviour
  packages/styles/components/_c.flag.scss
  packages/styles/settings-tools/_s.flags.scss
  src/docs/Components/Flags/code.mdx
  src/docs/Components/Flags/previews/bordered.preview.html
  src/docs/Components/Flags/previews/bordered.preview.scss
  src/docs/Components/Flags/previews/default.preview.html
  src/docs/Components/Flags/previews/default.preview.scss
  src/docs/Components/Flags/previews/flag-all.preview.html
  src/docs/Components/Flags/previews/flag-basic.preview.html
  src/docs/Components/Flags/previews/flag-basic.preview.scss
  src/docs/Components/Flags/previews/flag-default.preview.html
  src/docs/Components/Flags/previews/flag-default.preview.scss
  src/docs/Components/Flags/previews/solid.preview.html
  src/docs/Components/Flags/previews/solid.preview.scss
Labels: feat, scope:pattern, BREAKING CHANGE, [ W I P ]

#1025 feat(icons): add typescript to react icons
  packages/icons/react/index.d.ts
Labels: feat, scope:pattern

#1027 docs(website/roadmap): update roadmap
  src/docs/Updates/Roadmap/index.mdx
Labels: scope:website, scope:onboard

#1032 feat(component/pswdinput): increase CSS specificity on the input[type="password"] element
  packages/styles/components/_c.password-input.scss
Labels: feat, scope:component

#1033 feat(component/option-card): increase CSS specificity on the input element
  packages/styles/components/_c.option-card.scss
Labels: feat, scope:component

#1003 Development branch to update dependencies
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  packages/gatsby-source-preview/create-fsmachine.js
  packages/gatsby-source-preview/gatsby-node.js
  packages/gatsby-theme-styleguide/package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  yarn.lock
Labels: scope:chore, dependencies
