Repository adeo/mozaic-design-system, pull requests merged in 2022-10, with the labels that each got.

#1189 feat(tools/tokens): enable tokens export based on parameters
  mozaic.config.js
  packages/styles/components/_c.stepper.scss
  packages/tokens/build/android/font_dimens.xml
  packages/tokens/build/ios/StyleDictionarySize.h
  packages/tokens/build/ios/StyleDictionarySize.m
  packages/tokens/build/ios/StyleDictionarySize.swift
  packages/tokens/config.js
  src/docs/GetStarted/Developers/Configuration/index.mdx
Labels: :rocket: feat, BREAKING CHANGE, scope:tools, @next

#1206 perf(component/layer): improve the performance of the layer transition using `translate3d`
  packages/styles/components/_c.layer.scss
Labels: scope:component, perf

#1217 docs(icons): add icons documentation
  packages/gatsby-theme-styleguide/src/gatsby-components/IconsLink/IconsLink.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconsLink/index.js
  packages/gatsby-theme-styleguide/src/gatsby-components/layout.js
  packages/icons/react/index.js
  src/docs/Foundations/Icons/catalog.mdx
  src/docs/Foundations/Icons/catalogColor.mdx
  src/docs/Foundations/Icons/code.mdx
  src/docs/Foundations/Icons/iconsAnatomy.jpg
  src/docs/Foundations/Icons/index.mdx
  src/docs/Foundations/Icons/specs.mdx
Labels: :books: docs, @next

#1208 chore(dependencies): upgrade outdated dependencies
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  packages/gatsby-source-preview/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/package.json
  packages/tokens/package.json
  yarn.lock
Labels: :soap: chore, dependencies

#1214 fix(component/field): update the unicode character for no-break space
  packages/styles/components/_c.fields.scss
Labels: :fire_extinguisher: fix, scope:component

#1220 feat(component/m-link): remove modifiers `mc-link__icon--left` & `mc-link__icon--right`
  packages/styles/components/_c.links.scss
  packages/styles/settings-tools/_s.links.scss
  src/docs/Components/Links/code.mdx
  src/docs/Components/Links/previews/link-dont.preview.html
  src/docs/Components/Links/previews/link-icon-left.preview.html
  src/docs/Components/Links/previews/link-icon-right.preview.html
  src/docs/Components/Links/previews/link-icon.preview.html
Labels: :rocket: feat, scope:component, BREAKING CHANGE

#1230 feat(tooltip): use help cursor
  packages/styles/components/_c.tooltip.scss
Labels: :rocket: feat, :sparkles: refactor

#1222 feat(foundations/icons): add new icons
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/CardsMonochromeMaestro24.svelte
  packages/icons/svelte/CardsMonochromeMaestro32.svelte
  packages/icons/svelte/CardsMonochromeMaestro48.svelte
  packages/icons/svelte/CardsMonochromeMaestro64.svelte
  packages/icons/svelte/PromiseCircularEconomy24.svelte
  packages/icons/svelte/PromiseCircularEconomy32.svelte
  packages/icons/svelte/PromiseCircularEconomy48.svelte
  packages/icons/svelte/PromiseCircularEconomy64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg-color/Logotypes_Payment_Bizum_24px.svg
  packages/icons/svg-color/Logotypes_Payment_Bizum_32px.svg
  packages/icons/svg-color/Logotypes_Payment_Bizum_48px.svg
  packages/icons/svg-color/Logotypes_Payment_Bizum_64px.svg
  packages/icons/svg-color/Payment_Cards_Colors_Maestro_24px.svg
  packages/icons/svg-color/Payment_Cards_Colors_Maestro_32px.svg
  packages/icons/svg-color/Payment_Cards_Colors_Maestro_48px.svg
  packages/icons/svg-color/Payment_Cards_Colors_Maestro_64px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Maestro_24px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Maestro_32px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Maestro_48px.svg
  packages/icons/svg/Payment_Cards_Monochrome_Maestro_64px.svg
  packages/icons/svg/Product_Promise_CircularEconomy_24px.svg
  packages/icons/svg/Product_Promise_CircularEconomy_32px.svg
  packages/icons/svg/Product_Promise_CircularEconomy_48px.svg
  packages/icons/svg/Product_Promise_CircularEconomy_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/SVG/24px/Logotypes_Payment_Bizum_24px.svg
  src/icons/COLORS/SVG/24px/Payment_Cards_Colors_Maestro_24px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_Bizum_32px.svg
  src/icons/COLORS/SVG/32px/Payment_Cards_Colors_Maestro_32px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_Bizum_48px.svg
  src/icons/COLORS/SVG/48px/Payment_Cards_Colors_Maestro_48px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_Bizum_64px.svg
  src/icons/COLORS/SVG/64px/Payment_Cards_Colors_Maestro_64px.svg
  src/icons/SVG/24px/Payment_Cards_Monochrome_Maestro_24px.svg
  src/icons/SVG/24px/Product_Promise_CircularEconomy_24px.svg
  src/icons/SVG/32px/Payment_Cards_Monochrome_Maestro_32px.svg
  src/icons/SVG/32px/Product_Promise_CircularEconomy_32px.svg
  src/icons/SVG/48px/Payment_Cards_Monochrome_Maestro_48px.svg
  src/icons/SVG/48px/Product_Promise_CircularEconomy_48px.svg
  src/icons/SVG/64px/Payment_Cards_Monochrome_Maestro_64px.svg
  src/icons/SVG/64px/Product_Promise_CircularEconomy_64px.svg
  static/colorsvg/Logotypes_Payment_Bizum_24px.svg
  static/colorsvg/Logotypes_Payment_Bizum_32px.svg
  static/colorsvg/Logotypes_Payment_Bizum_48px.svg
  static/colorsvg/Logotypes_Payment_Bizum_64px.svg
  static/colorsvg/Payment_Cards_Colors_Maestro_24px.svg
  static/colorsvg/Payment_Cards_Colors_Maestro_32px.svg
  static/colorsvg/Payment_Cards_Colors_Maestro_48px.svg
  static/colorsvg/Payment_Cards_Colors_Maestro_64px.svg
Labels: :rocket: feat, :zap: design

#1238 fix(component/phninput): remove `z-index` on `.mc-phone-number__dropdown` element
  packages/styles/components/_c.phone-number.scss
Labels: :fire_extinguisher: fix, scope:component

#1218 feat(component/autocomplete): improve component styles & documentation
  packages/styles/components/_c.autocomplete.scss
  packages/styles/components/_c.listbox.scss
  packages/styles/settings-tools/_all-settings.scss
  packages/styles/settings-tools/_s.autocomplete.scss
  packages/styles/settings-tools/_s.listbox.scss
  src/docs/Components/Form/Autocomplete/code.mdx
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/default.preview.scss
  src/docs/Components/Form/Autocomplete/previews/disabled.preview.html
  src/docs/Components/Form/Autocomplete/previews/disabled.preview.scss
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.scss
Labels: :rocket: feat, scope:component

#1239 chore(product-info.json): Github Adeo organization file updated [ci skip]
  product-info.json
Labels: :soap: chore

#1240 feat(foundations/icons): add new icons
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/Glass24.svelte
  packages/icons/svelte/Glass32.svelte
  packages/icons/svelte/Glass48.svelte
  packages/icons/svelte/Glass64.svelte
  packages/icons/svelte/Leak24.svelte
  packages/icons/svelte/Leak32.svelte
  packages/icons/svelte/Leak48.svelte
  packages/icons/svelte/Leak64.svelte
  packages/icons/svelte/Pool24.svelte
  packages/icons/svelte/Pool32.svelte
  packages/icons/svelte/Pool48.svelte
  packages/icons/svelte/Pool64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg/Universe_Glass_24px.svg
  packages/icons/svg/Universe_Glass_32px.svg
  packages/icons/svg/Universe_Glass_48px.svg
  packages/icons/svg/Universe_Glass_64px.svg
  packages/icons/svg/Universe_Leak_24px.svg
  packages/icons/svg/Universe_Leak_32px.svg
  packages/icons/svg/Universe_Leak_48px.svg
  packages/icons/svg/Universe_Leak_64px.svg
  packages/icons/svg/Universe_Pool_24px.svg
  packages/icons/svg/Universe_Pool_32px.svg
  packages/icons/svg/Universe_Pool_48px.svg
  packages/icons/svg/Universe_Pool_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/SVG/24px/Universe_Glass_24px.svg
  src/icons/SVG/24px/Universe_Leak_24px.svg
  src/icons/SVG/24px/Universe_Pool_24px.svg
  src/icons/SVG/32px/Universe_Glass_32px.svg
  src/icons/SVG/32px/Universe_Leak_32px.svg
  src/icons/SVG/32px/Universe_Pool_32px.svg
  src/icons/SVG/48px/Universe_Glass_48px.svg
  src/icons/SVG/48px/Universe_Leak_48px.svg
  src/icons/SVG/48px/Universe_Pool_48px.svg
  src/icons/SVG/64px/Universe_Glass_64px.svg
  src/icons/SVG/64px/Universe_Leak_64px.svg
  src/icons/SVG/64px/Universe_Pool_64px.svg
  yarn.lock
Labels: :rocket: feat, :zap: design

#1241 fix(component/tabs): add `pointer-events: none;` on `.mc-tabs__text` element
  packages/styles/components/_c.tabs.scss
Labels: :fire_extinguisher: fix, scope:component

#1242 fix(components/modal/layer): improve overlay for scoped modules
  packages/styles/components/_c.layer.scss
  packages/styles/components/_c.modal.scss
Labels: :fire_extinguisher: fix, scope:component
