Repository adeo/mozaic-design-system, pull requests merged in 2022-06, with the labels that each got.

#1133 feat(foundations/icons): add new icons
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/DisplayLogOut24.svelte
  packages/icons/svelte/DisplayLogOut32.svelte
  packages/icons/svelte/DisplayLogOut48.svelte
  packages/icons/svelte/DisplayLogOut64.svelte
  packages/icons/svelte/DisplaySearchList24.svelte
  packages/icons/svelte/DisplaySearchList32.svelte
  packages/icons/svelte/DisplaySearchList48.svelte
  packages/icons/svelte/DisplaySearchList64.svelte
  packages/icons/svelte/PublishLock16.svelte
  packages/icons/svelte/PublishLock24.svelte
  packages/icons/svelte/PublishLock32.svelte
  packages/icons/svelte/PublishLock48.svelte
  packages/icons/svelte/PublishLock64.svelte
  packages/icons/svg/Navigation_Display_LogOut_24px.svg
  packages/icons/svg/Navigation_Display_LogOut_32px.svg
  packages/icons/svg/Navigation_Display_LogOut_48px.svg
  packages/icons/svg/Navigation_Display_LogOut_64px.svg
  packages/icons/svg/Navigation_Display_SearchList_24px.svg
  packages/icons/svg/Navigation_Display_SearchList_32px.svg
  packages/icons/svg/Navigation_Display_SearchList_48px.svg
  packages/icons/svg/Navigation_Display_SearchList_64px.svg
  packages/icons/svg/Navigation_Publish_Lock_16px.svg
  packages/icons/svg/Navigation_Publish_Lock_24px.svg
  packages/icons/svg/Navigation_Publish_Lock_32px.svg
  packages/icons/svg/Navigation_Publish_Lock_48px.svg
  packages/icons/svg/Navigation_Publish_Lock_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/SVG/16px/Navigation_Publish_Lock_16px.svg
  src/icons/SVG/24px/Navigation_Display_LogOut_24px.svg
  src/icons/SVG/24px/Navigation_Display_SearchList_24px.svg
  src/icons/SVG/24px/Navigation_Publish_Lock_24px.svg
  src/icons/SVG/32px/Navigation_Display_LogOut_32px.svg
  src/icons/SVG/32px/Navigation_Display_SearchList_32px.svg
  src/icons/SVG/32px/Navigation_Publish_Lock_32px.svg
  src/icons/SVG/48px/Navigation_Display_LogOut_48px.svg
  src/icons/SVG/48px/Navigation_Display_SearchList_48px.svg
  src/icons/SVG/48px/Navigation_Publish_Lock_48px.svg
  src/icons/SVG/64px/Navigation_Display_LogOut_64px.svg
  src/icons/SVG/64px/Navigation_Display_SearchList_64px.svg
  src/icons/SVG/64px/Navigation_Publish_Lock_64px.svg
Labels: :rocket: feat, :zap: design

#1143 feat(grid): add all col for base 12
  packages/styles/layouts/_l.flexy.scss
Labels: :rocket: feat, :sparkles: refactor

#1158 fix(modal): use fill-available
  packages/styles/components/_c.modal.scss
Labels: :fire_extinguisher: fix

#1156 refactor(foundations/icons): re-design some icons
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/DisplayExternalLink16.svelte
  packages/icons/svelte/DisplayExternalLink24.svelte
  packages/icons/svelte/DisplayExternalLink32.svelte
  packages/icons/svelte/DisplayExternalLink48.svelte
  packages/icons/svelte/DisplayExternalLink64.svelte
  packages/icons/svelte/DisplayOptions24.svelte
  packages/icons/svelte/DisplayOptions32.svelte
  packages/icons/svelte/DisplayOptions48.svelte
  packages/icons/svelte/DisplayOptions64.svelte
  packages/icons/svelte/DisplayOther24.svelte
  packages/icons/svelte/DisplayOther32.svelte
  packages/icons/svelte/DisplayOther48.svelte
  packages/icons/svelte/DisplayOther64.svelte
  packages/icons/svelte/PublishEdit24.svelte
  packages/icons/svelte/PublishEdit32.svelte
  packages/icons/svelte/PublishEdit48.svelte
  packages/icons/svelte/PublishEdit64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg/Navigation_Display_ExternalLink_16px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_24px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_32px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_48px.svg
  packages/icons/svg/Navigation_Display_ExternalLink_64px.svg
  packages/icons/svg/Navigation_Display_Options_24px.svg
  packages/icons/svg/Navigation_Display_Options_32px.svg
  packages/icons/svg/Navigation_Display_Options_48px.svg
  packages/icons/svg/Navigation_Display_Options_64px.svg
  packages/icons/svg/Navigation_Display_Other_24px.svg
  packages/icons/svg/Navigation_Display_Other_32px.svg
  packages/icons/svg/Navigation_Display_Other_48px.svg
  packages/icons/svg/Navigation_Display_Other_64px.svg
  packages/icons/svg/Navigation_Publish_Edit_24px.svg
  packages/icons/svg/Navigation_Publish_Edit_32px.svg
  packages/icons/svg/Navigation_Publish_Edit_48px.svg
  packages/icons/svg/Navigation_Publish_Edit_64px.svg
  packages/icons/vue/index.vue
  src/icons/SVG/16px/Navigation_Display_ExternalLink_16px.svg
  src/icons/SVG/24px/Navigation_Display_ExternalLink_24px.svg
  src/icons/SVG/24px/Navigation_Display_Options_24px.svg
  src/icons/SVG/24px/Navigation_Display_Other_24px.svg
  src/icons/SVG/24px/Navigation_Publish_Edit_24px.svg
  src/icons/SVG/32px/Navigation_Display_ExternalLink_32px.svg
  src/icons/SVG/32px/Navigation_Display_Options_32px.svg
  src/icons/SVG/32px/Navigation_Display_Other_32px.svg
  src/icons/SVG/32px/Navigation_Publish_Edit_32px.svg
  src/icons/SVG/48px/Navigation_Display_ExternalLink_48px.svg
  src/icons/SVG/48px/Navigation_Display_Options_48px.svg
  src/icons/SVG/48px/Navigation_Display_Other_48px.svg
  src/icons/SVG/48px/Navigation_Publish_Edit_48px.svg
  src/icons/SVG/64px/Navigation_Display_ExternalLink_64px.svg
  src/icons/SVG/64px/Navigation_Display_Options_64px.svg
  src/icons/SVG/64px/Navigation_Display_Other_64px.svg
  src/icons/SVG/64px/Navigation_Publish_Edit_64px.svg
Labels: :sparkles: refactor, scope:component, :zap: design

#1160 fix(grid): enhance loop to remove stylelint issue
  packages/styles/layouts/_l.flexy.scss
Labels: :fire_extinguisher: fix
