Repository adeo/mozaic-design-system, pull requests merged in 2023-01, with the labels that each got.

#1313 refactor(component/modal): set a `min-height` value for the modal's header
  packages/styles/components/_c.modal.scss
Labels: :sparkles: refactor, scope:component

#1319 fix(component/option-card): update the `z-index` values of the component elements
  packages/styles/components/_c.option-card.scss
  src/docs/Components/OptionGroup/OptionCard/code.mdx
  src/docs/Components/OptionGroup/OptionCard/previews/product.preview.scss
Labels: :fire_extinguisher: fix, scope:component

#1321 fix(tools/tokens): update script `tokens:clean`
  package.json
  packages/tokens/build/lm/scss/tokens.scss
Labels: scope:tools, @next

#1320 feat(foundations/icons): add new mb logotype
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/PaymentMonochromeMBMultibanco24.svelte
  packages/icons/svelte/PaymentMonochromeMBMultibanco32.svelte
  packages/icons/svelte/PaymentMonochromeMBMultibanco48.svelte
  packages/icons/svelte/PaymentMonochromeMBMultibanco64.svelte
  packages/icons/svelte/PaymentMonochromeMBWay24.svelte
  packages/icons/svelte/PaymentMonochromeMBWay32.svelte
  packages/icons/svelte/PaymentMonochromeMBWay48.svelte
  packages/icons/svelte/PaymentMonochromeMBWay64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg-color/Logotypes_Payment_MB--Multibanco_24px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Multibanco_32px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Multibanco_48px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Multibanco_64px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Way_24px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Way_32px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Way_48px.svg
  packages/icons/svg-color/Logotypes_Payment_MB--Way_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Multibanco_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Multibanco_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Multibanco_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Multibanco_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Way_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Way_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Way_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_MB--Way_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/SVG/24px/Logotypes_Payment_MB--Multibanco_24px.svg
  src/icons/COLORS/SVG/24px/Logotypes_Payment_MB--Way_24px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_MB--Multibanco_32px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_MB--Way_32px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_MB--Multibanco_48px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_MB--Way_48px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_MB--Multibanco_64px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_MB--Way_64px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_MB--Multibanco_24px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_MB--Way_24px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_MB--Multibanco_32px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_MB--Way_32px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_MB--Multibanco_48px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_MB--Way_48px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_MB--Multibanco_64px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_MB--Way_64px.svg
  static/colorsvg/Logotypes_Payment_MB--Multibanco_24px.svg
  static/colorsvg/Logotypes_Payment_MB--Multibanco_32px.svg
  static/colorsvg/Logotypes_Payment_MB--Multibanco_48px.svg
  static/colorsvg/Logotypes_Payment_MB--Multibanco_64px.svg
  static/colorsvg/Logotypes_Payment_MB--Way_24px.svg
  static/colorsvg/Logotypes_Payment_MB--Way_32px.svg
  static/colorsvg/Logotypes_Payment_MB--Way_48px.svg
  static/colorsvg/Logotypes_Payment_MB--Way_64px.svg
Labels: :rocket: feat

#1323 fix(toggle): use background-position
  packages/styles/components/_c.toggle.scss
Labels: :fire_extinguisher: fix, @next

#1326 chore(previews): avoid reloading all previews when scss changes
  packages/gatsby-source-preview/gatsby-node.js
Labels: :soap: chore, @next
