Repository adeo/mozaic-design-system, pull requests merged in 2023-08, with the labels that each got.

#1468 chore(fonts): add polish fonts
  packages/web-fonts/polish/LeroyMerlinSans-Web-Italic.woff2
  packages/web-fonts/polish/LeroyMerlinSans-Web-Light.woff2
  packages/web-fonts/polish/LeroyMerlinSans-Web-LightItalic.woff2
  packages/web-fonts/polish/LeroyMerlinSans-Web-Regular.woff2
  packages/web-fonts/polish/LeroyMerlinSans-Web-SemiBold.woff2
  packages/web-fonts/polish/LeroyMerlinSans-Web-SemiBoldItalic.woff2
Labels: :rocket: feat

#1478 fix(field): add element class for inline
  packages/styles/components/_c.fields.scss
Labels: :fire_extinguisher: fix

#1480 feat(docs): add content design principles
  src/docs/Foundations/Content design/Principles/index.mdx
  src/docs/Foundations/Content design/index.mdx
Labels: :zap: design, :books: docs

#1481 feat(segmented-control): add code
  packages/styles/components/_c.segmented-control.scss
  packages/tokens/AdeoProperties/color/segmented-control.json
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/segmented-control.json
  src/docs/Components/SegmentedControl/code.mdx
  src/docs/Components/SegmentedControl/index.mdx
  src/docs/Components/SegmentedControl/previews/basic.preview.html
  src/docs/Components/SegmentedControl/previews/basic.preview.scss
  src/docs/Components/SegmentedControl/previews/full.preview.html
  src/docs/Components/SegmentedControl/previews/full.preview.scss
  src/docs/Components/SegmentedControl/previews/medium.preview.html
  src/docs/Components/SegmentedControl/previews/medium.preview.scss
Labels: :rocket: feat

#1483 feat(menu): add code
  packages/styles/components/_c.menu.scss
  packages/tokens/AdeoProperties/color/menu.json
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/menu.json
  src/docs/Components/Built-inMenu/code.mdx
  src/docs/Components/Built-inMenu/index.mdx
  src/docs/Components/Built-inMenu/previews/basic.preview.html
  src/docs/Components/Built-inMenu/previews/basic.preview.scss
Labels: :rocket: feat

#1486 fix(segmented): add box-sizing
  packages/styles/components/_c.segmented-control.scss
Labels: :fire_extinguisher: fix

#1491 feat(segmented): add no-wrap modifier
  packages/styles/components/_c.segmented-control.scss
Labels: :rocket: feat, :fire_extinguisher: fix
