Repository adeo/mozaic-design-system, pull requests merged in 2023-05, with the labels that each got.

#1420 feat(docs): add segmented control documentation
  package.json
  packages/gatsby-theme-styleguide/package.json
  src/docs/Components/Built-in menu/index.mdx
  src/docs/Components/SegmentedControl/code.mdx
  src/docs/Components/SegmentedControl/index.mdx
  yarn.lock
Labels: :books: docs

#1419 fix(component/stars-input): stringify "background-image" parameter to avoid ";" expectation SASS error
  packages/styles/components/_c.stars-input.scss
Labels: :fire_extinguisher: fix, scope:component

#1428 chore(deps): upgrade outdated dependencies
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/package.json
  packages/stylelint-plugin-mozaic/package.json
  packages/tokens/package.json
  yarn.lock
Labels: :soap: chore, dependencies

#1430 chore(node): upgrade Node.js to version 18
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
Labels: :soap: chore

#1432 feat(tokens): add sidebar tokens
  packages/tokens/AdeoProperties/color/sidebar.json
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/sidebar.json
Labels: :rocket: feat

#1431 fix(component/qtyselector): adjust the focus behaviour
  packages/styles/components/_c.quantity-selector.scss
Labels: :fire_extinguisher: fix, scope:component

#1434 feat(font-size): update font size 07 to 24px
  packages/tokens/BricomanProperties/size/font.json
Labels: :rocket: feat
