Repository adeo/mozaic-design-system, pull requests merged in 2023-03, with the labels that each got.

#1375 fix(component/field-group): make legend optional
  packages/styles/components/_c.fields.scss
  src/docs/Components/Form/Checkbox/previews/group-help-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-help-text.preview.html
  src/docs/Components/Form/Checkbox/previews/group-indeterminate.preview.html
  src/docs/Components/Form/Checkbox/previews/group-inline.preview.html
  src/docs/Components/Form/Checkbox/previews/group-invalid-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-invalid.preview.html
  src/docs/Components/Form/Checkbox/previews/group-requirement-light.preview.html
  src/docs/Components/Form/Checkbox/previews/group-requirement.preview.html
Labels: :fire_extinguisher: fix, scope:component

#1393 feat(tools/tokens): adeo - updating the Tooltip component tokens
  packages/tokens/AdeoProperties/color/tooltip.json
Labels: :rocket: feat, scope:tools

#1394 fix(chrome): add background-size to display icons
  packages/styles/components/_c.file-uploader.scss
  packages/styles/components/_c.notification.scss
  packages/styles/components/_c.toggle.scss
Labels: :fire_extinguisher: fix

#1398 feat(component/fileuploader): report fix styles coming from mozaic-vue
  packages/styles/components/_c.file-uploader.scss
Labels: :rocket: feat, scope:component

#1397 feat(component/autocomplete): add styles for the error message
  packages/styles/components/_c.autocomplete.scss
Labels: :rocket: feat, scope:component

#1396 fix(component/stepper): remove default background of 'indicator' element
  packages/styles/components/_c.stepper.scss
Labels: :fire_extinguisher: fix, scope:component

#1392 feat(tools/tokens): add tokens for datatable component
  packages/styles/components/_c.datatable-header.scss
  packages/styles/components/_c.datatable-subtable.scss
  packages/styles/components/_c.datatable-tools.scss
  packages/styles/components/_c.datatable.scss
  packages/styles/settings-tools/_s.datatable.scss
  packages/tokens/AdeoProperties/color/datatable.json
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/datatable.json
Labels: :rocket: feat, scope:tools

#1406 fix(button): remove pointer-event from disable button
  packages/styles/components/_c.button.scss
  packages/styles/settings-tools/_s.buttons.scss
Labels: :fire_extinguisher: fix

#1404 feat(component/toggle): improve toggle component for scoped modules
  packages/styles/components/_c.toggle.scss
  src/docs/Components/Form/Toggle/previews/Toggle-item.preview.scss
Labels: :rocket: feat, scope:component

#1407 feat(notification): add role status
  src/docs/Components/Notification/accessibility.mdx
  src/docs/Components/Notification/previews/notification-success.preview.html
  src/docs/Components/Notification/previews/notification-types.preview.html
  src/docs/Components/Notification/previews/notification-variations.preview.html
  src/docs/Components/Notification/previews/notification-warning.preview.html
  src/docs/Components/Notification/previews/notification.preview.html
  src/docs/Components/Notification/previews/sizes.preview.html
  src/docs/Components/Notification/previews/with-buttons-usage.preview.html
  src/docs/Components/Notification/previews/with-buttons.preview.html
Labels: :rocket: feat, :books: docs
