Repository adeo/mozaic-design-system, pull requests merged in 2023-04, with the labels that each got.

#1410 feat(foundations/icons): icon.js - add the icon name in the exported icons objects
  iconCompiler/generateIconsJS/iconsCommon.js
  iconCompiler/generateIconsJS/iconsModules.js
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/svelte/icons.js
Labels: :rocket: feat

#1415 fix(component/tag): update of the value of the paddings
  packages/styles/components/_c.tag.scss
  packages/styles/settings-tools/_s.tag.scss
Labels: :fire_extinguisher: fix, scope:component

#1418 fix: regenerate missing tokens & updating icons js files
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/svelte/icons.js
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
Labels: :fire_extinguisher: fix, scope:tools

#1421 feat(component/autocomplete-dropdown): improve the display of the loader & the clear button
  packages/styles/components/_c.autocomplete.scss
  packages/styles/components/_c.dropdown.scss
  src/docs/Components/Form/Autocomplete/previews/default.preview.html
  src/docs/Components/Form/Autocomplete/previews/invalid.preview.html
  src/docs/Components/Form/Autocomplete/previews/multi.preview.html
  src/docs/Components/Form/Dropdown/previews/default.preview.html
  src/docs/Components/Form/Dropdown/previews/invalid.preview.html
  src/docs/Components/Form/Dropdown/previews/multi.preview.html
Labels: :rocket: feat, scope:component

#1390 feat(docs): add built-in menu documentation
  src/docs/Components/Built-in menu/code.mdx
  src/docs/Components/Built-in menu/index.mdx
Labels: :books: docs, @next
