Repository adeo/mozaic-design-system, pull requests merged in 2023-02, with the labels that each got.

#1350 chore(github/issues): update the issues `config.yml` file
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/config.yml
Labels: :soap: chore

#1347 feat(component/button): apply a `pointer-events:none` in the case of a disabled button
  packages/styles/settings-tools/_s.buttons.scss
Labels: :rocket: feat, scope:component

#1345 feat(component/badge): ensure the correct display of text in according to design rules
  packages/styles/settings-tools/_s.badges.scss
  src/docs/Components/Badge/previews/basic.preview.html
Labels: :rocket: feat, scope:component

#1340 docs(tabs): use Mozaic tabs in docs
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/PageTabs.js
  packages/gatsby-theme-styleguide/src/gatsby-components/PageTabs/styles.scss
  packages/icons/react/index.js
  packages/icons/svelte/icons.js
  packages/styles/components/_c.datatable.scss
  packages/styles/components/_c.dropdown.scss
  packages/styles/components/_c.stepper.scss
  yarn.lock
Labels: :books: docs, @next

#1355 chore(deps): upgrade packages version
  .gitignore
  package.json
  packages/gatsby-theme-styleguide/package.json
  yarn.lock
Labels: :soap: chore

#1356 feat(icons): add oneyx4 logotype
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/PaymentMonochromeOney4x24.svelte
  packages/icons/svelte/PaymentMonochromeOney4x32.svelte
  packages/icons/svelte/PaymentMonochromeOney4x48.svelte
  packages/icons/svelte/PaymentMonochromeOney4x64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg-color/Logotypes_Payment_Oney--4x_24px.svg
  packages/icons/svg-color/Logotypes_Payment_Oney--4x_32px.svg
  packages/icons/svg-color/Logotypes_Payment_Oney--4x_48px.svg
  packages/icons/svg-color/Logotypes_Payment_Oney--4x_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Oney--4x_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Oney--4x_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Oney--4x_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Oney--4x_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/SVG/24px/Logotypes_Payment_Oney--4x_24px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_Oney--4x_32px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_Oney--4x_48px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_Oney--4x_64px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_Oney--4x_24px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_Oney--4x_32px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_Oney--4x_48px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_Oney--4x_64px.svg
  static/colorsvg/Logotypes_Payment_Oney--4x_24px.svg
  static/colorsvg/Logotypes_Payment_Oney--4x_32px.svg
  static/colorsvg/Logotypes_Payment_Oney--4x_48px.svg
  static/colorsvg/Logotypes_Payment_Oney--4x_64px.svg
Labels: :rocket: feat, :zap: design, :books: docs

#1315 feat(config): allow usage of .cjs extension
  packages/configuration-manager/index.js
Labels: :rocket: feat, scope:tools

#1370 feat(icons): add search for icons list
  packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconTile.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/IconViewer.js
  packages/gatsby-theme-styleguide/src/gatsby-components/IconViewer/styles.scss
Labels: :books: docs
