Repository adeo/mozaic-design-system, pull requests merged in 2023-07, with the labels that each got.

#1458 feat(icons): add store lm icon
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/StoreBM24.svelte
  packages/icons/svelte/StoreBM32.svelte
  packages/icons/svelte/StoreBM48.svelte
  packages/icons/svelte/StoreBM64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg/Store_StoreBM_24px.svg
  packages/icons/svg/Store_StoreBM_32px.svg
  packages/icons/svg/Store_StoreBM_48px.svg
  packages/icons/svg/Store_StoreBM_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/SVG/24px/Store_StoreBM_24px.svg
  src/icons/SVG/32px/Store_StoreBM_32px.svg
  src/icons/SVG/48px/Store_StoreBM_48px.svg
  src/icons/SVG/64px/Store_StoreBM_64px.svg
Labels: :zap: design, :books: docs

#1445 chore(css-dev-tools): remove base64 plugin
  packages/css-dev-tools/package.json
  packages/css-dev-tools/postcssPluginConfig.js
  packages/gatsby-theme-styleguide/gatsby-config.js
  packages/stylelint-plugin-mozaic/package.json
  packages/stylelint-plugin-mozaic/test/index.js
  packages/styles/settings-tools/_s.inline-icons.scss
  yarn.lock
Labels: :soap: chore

#1388 feat(docs): update datatable documentation
  src/docs/Components/DataTable/TableLayout--Fill.png
  src/docs/Components/DataTable/TableLayout--Fixed.png
  src/docs/Components/DataTable/index.mdx
Labels: scope:component, :books: docs

#1387 feat(components): add sidebar documentation
  src/docs/Components/Sidebar/code.mdx
  src/docs/Components/Sidebar/index.mdx
Labels: :books: docs

#1465 feat(tooltip): add word break modifier
  packages/styles/components/_c.tooltip.scss
Labels: :rocket: feat

#1466 Revert "fix: label prevents clicking on the accordion (#1448)"
  packages/styles/components/_c.accordion.scss
Labels: :rocket: feat, scope:component

#1386 feat(components): add header documentation
  src/docs/Components/PageHeader/code.mdx
  src/docs/Components/PageHeader/index.mdx
Labels: scope:component, :books: docs

#1477 fix(component/optioncard): add `position:relative` on focusable elements
  packages/styles/components/_c.option-card.scss
Labels: :fire_extinguisher: fix, scope:component

#1400 docs(getstarted): rework get started documentation
  src/docs/Contributing/Designers/DesignRequirements/index.mdx
  src/docs/GetStarted/About/index.mdx
  src/docs/GetStarted/Designers/PresetAdeo/index.mdx
  src/docs/GetStarted/Designers/aboutTheSystem/index.mdx
  src/docs/GetStarted/Designers/index.mdx
  src/docs/GetStarted/Designers/installation/1.Preferences-libraries.png
  src/docs/GetStarted/Designers/installation/index.mdx
  src/docs/GetStarted/Designers/installation/library-update.jpg
  src/docs/GetStarted/Designers/namingConvention/buttons--sketch-menu.png
  src/docs/GetStarted/Designers/namingConvention/index.mdx
  src/docs/GetStarted/Designers/requirements/index.mdx
  src/docs/GetStarted/Designers/whatsIncluded/index.mdx
Labels: :books: docs
