Repository adeo/mozaic-design-system, pull requests merged in 2023-06, with the labels that each got.

#1436 fix(component/modal): manage long content by default
  packages/styles/components/_c.modal.scss
  src/docs/Components/Modals/code.mdx
  src/docs/Components/Modals/previews/big-content.preview.html
  src/docs/Components/Modals/previews/big-content.preview.scss
Labels: :fire_extinguisher: fix, scope:component

#1440 ci(github/actions): implement GCP WIF authentication
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: :soap: chore

#1442 ci(gcp/appengine): update `.gcloudignore` file to exclude cache files
  .gcloudignore
Labels: :soap: chore

#1443 ci(gha/gcp): display the site url on the deployed environment
  .github/workflows/push.yml
  .github/workflows/release.yml
Labels: :soap: chore

#1444 fix(sidebar): update tokens for adeo
  packages/tokens/AdeoProperties/color/sidebar.json
  packages/tokens/properties/color/sidebar.json
Labels: :fire_extinguisher: fix

#1447 chore(lerna): remove useWorkspace and bootstrap
  lerna.json
  package.json
Labels: :soap: chore

#1446 chore(token): run build
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.h
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
Labels: :soap: chore

#1456 chore(deps): add babel deps
  package.json
  yarn.lock
Labels: :soap: chore
