Repository adeo/mozaic-design-system, pull requests merged in 2024-03, with the labels that each got.

#1562 fix(component/tooltip): update word-break to avoid cutting word in half
  packages/styles/components/_c.tooltip.scss
Labels: :fire_extinguisher: fix

#1526 feat(docs): Key performance indicator
  src/docs/Components/KeyPerformanceIndicator/index.mdx
Labels: :books: docs

#1563 fix(tools/tokens): downgrade `style-dictionary` to v3.9.0
  packages/tokens/package.json
  yarn.lock
Labels: :fire_extinguisher: fix, :soap: chore

#1568 fix(component/textarea): limit resize beyond the max width
  packages/styles/components/_c.textarea.scss
Labels: :fire_extinguisher: fix, scope:component

#1570 feat(components/datatable): update empty states display
  packages/styles/components/_c.datatable-empty.scss
  packages/styles/components/_c.datatable.scss
Labels: :rocket: feat, scope:component
