Repository adeo/mozaic-design-system, pull requests merged in 2024-02, with the labels that each got.

#1543 fix(component/listbox): update the `danger` state of listbox actions
  packages/styles/components/_c.listbox.scss
Labels: :fire_extinguisher: fix, scope:component

#1544 chore(robots): clean robot sitemap url
  static/robots.txt
Labels: :soap: chore

#1546 fix(Tooltip): make tooltip usable by keyboard for accessibility
  packages/styles/components/_c.tooltip.scss
Labels: :fire_extinguisher: fix, scope:component

#1553 fix(component/breadcrumb): remove extra padding on 1st item
  packages/styles/components/_c.breadcrumb.scss
Labels: :fire_extinguisher: fix, scope:component

#1549 feat(icons): add oneyraty logotype
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/PaymentMonochromeOneyRaty24.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty32.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty48.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg-color/Logotypes_Payment_OneyRaty_24px.svg
  packages/icons/svg-color/Logotypes_Payment_OneyRaty_32px.svg
  packages/icons/svg-color/Logotypes_Payment_OneyRaty_48px.svg
  packages/icons/svg-color/Logotypes_Payment_OneyRaty_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/SVG/24px/Logotypes_Payment_OneyRaty_24px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_OneyRaty_32px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_OneyRaty_48px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_OneyRaty_64px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_OneyRaty_24px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_OneyRaty_32px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_OneyRaty_48px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_OneyRaty_64px.svg
  static/colorsvg/Logotypes_Payment_OneyRaty_24px.svg
  static/colorsvg/Logotypes_Payment_OneyRaty_32px.svg
  static/colorsvg/Logotypes_Payment_OneyRaty_48px.svg
  static/colorsvg/Logotypes_Payment_OneyRaty_64px.svg
Labels: :zap: design

#1555 chore(codeowner): add codeowners file
  .github/CODEOWNERS
Labels: :soap: chore

#1556 fix(component/accordion): remove default white background
  packages/styles/components/_c.accordion.scss
Labels: :fire_extinguisher: fix, scope:component
