Repository adeo/mozaic-design-system, pull requests merged in 2024-06, with the labels that each got.

#1590 fix(listbox): set same style on hover and focus
  packages/styles/components/_c.listbox.scss
Labels: :fire_extinguisher: fix, scope:component

#1593 feat(components/a11y): update of focus states
  packages/styles/components/_c.datatable-tools.scss
  packages/styles/components/_c.menu.scss
  packages/styles/components/_c.password-input.scss
  packages/styles/components/_c.segmented-control.scss
  packages/styles/components/_c.stepper.scss
  packages/styles/components/_c.tag.scss
Labels: :rocket: feat, scope:component

#1595 chore(node): upgrade Node.js to version 20
  .github/workflows/push.yml
  .github/workflows/release.yml
  .nvmrc
  app.demo.yaml
  app.yaml
  ci/docker-wait/Dockerfile
  package.json
  src/docs/Contributing/Developers/InstallForDev/index.mdx
  src/docs/GetStarted/Developers/Installation/index.mdx
  src/docs/GetStarted/Developers/npmScriptTutorial/index.mdx
  yarn.lock
Labels: :soap: chore, dependencies

#1596 chore(deps): update outdated dependencies
  package.json
  packages/css-dev-tools/package.json
  packages/gatsby-github-release/package.json
  packages/gatsby-source-preview/package.json
  packages/gatsby-theme-styleguide/package.json
  packages/icons/package.json
  packages/postcss-media-queries-packer-on-demand/package.json
  packages/postcss-prepend/package.json
  packages/stylelint-plugin-mozaic/package.json
  yarn.lock
Labels: :soap: chore, dependencies

#1597 chore(deps/commitlin): upgrade commitlint to latest major version v19+
  commitlint.config.mjs
  package.json
  yarn.lock
Labels: :soap: chore, dependencies

#1598 chore(deps/husky): upgrade husky to its latest major version v9+
  .github/workflows/push.yml
  .github/workflows/release.yml
  .husky/commit-msg
  .husky/pre-commit
  package.json
  yarn.lock
Labels: :soap: chore, dependencies

#1599 feat(icons): update icon and logotype set
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/PaymentMonochromeBlik24.svelte
  packages/icons/svelte/PaymentMonochromeBlik32.svelte
  packages/icons/svelte/PaymentMonochromeBlik48.svelte
  packages/icons/svelte/PaymentMonochromeBlik64.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty24.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty32.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty48.svelte
  packages/icons/svelte/PaymentMonochromeOneyRaty64.svelte
  packages/icons/svelte/Transfer24.svelte
  packages/icons/svelte/Transfer32.svelte
  packages/icons/svelte/Transfer48.svelte
  packages/icons/svelte/Transfer64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg-color/Logotypes_Payment_Przelesw_24px.svg
  packages/icons/svg-color/Logotypes_Payment_Przelesw_32px.svg
  packages/icons/svg-color/Logotypes_Payment_Przelesw_48px.svg
  packages/icons/svg-color/Logotypes_Payment_Przelesw_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Blik_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Blik_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Blik_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_Blik_64px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_24px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_32px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_48px.svg
  packages/icons/svg/Logotypes_Payment_Monochrome_OneyRaty_64px.svg
  packages/icons/svg/Payment_Transfer_24px.svg
  packages/icons/svg/Payment_Transfer_32px.svg
  packages/icons/svg/Payment_Transfer_48px.svg
  packages/icons/svg/Payment_Transfer_64px.svg
  packages/icons/vue/index.vue
  src/data/icons.json
  src/icons/COLORS/SVG/24px/Logotypes_Payment_Przelesw_24px.svg
  src/icons/COLORS/SVG/32px/Logotypes_Payment_Przelesw_32px.svg
  src/icons/COLORS/SVG/48px/Logotypes_Payment_Przelesw_48px.svg
  src/icons/COLORS/SVG/64px/Logotypes_Payment_Przelesw_64px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_Blik_24px.svg
  src/icons/SVG/24px/Logotypes_Payment_Monochrome_OneyRaty_24px.svg
  src/icons/SVG/24px/Payment_Transfer_24px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_Blik_32px.svg
  src/icons/SVG/32px/Logotypes_Payment_Monochrome_OneyRaty_32px.svg
  src/icons/SVG/32px/Payment_Transfer_32px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_Blik_48px.svg
  src/icons/SVG/48px/Logotypes_Payment_Monochrome_OneyRaty_48px.svg
  src/icons/SVG/48px/Payment_Transfer_48px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_Blik_64px.svg
  src/icons/SVG/64px/Logotypes_Payment_Monochrome_OneyRaty_64px.svg
  src/icons/SVG/64px/Payment_Transfer_64px.svg
  static/colorsvg/Logotypes_Payment_Przelesw_24px.svg
  static/colorsvg/Logotypes_Payment_Przelesw_32px.svg
  static/colorsvg/Logotypes_Payment_Przelesw_48px.svg
  static/colorsvg/Logotypes_Payment_Przelesw_64px.svg
Labels: :rocket: feat, :zap: design

#1600 fix(tools/tokens): custom source path should be relative to project root
  packages/tokens/config.js
Labels: :fire_extinguisher: fix, scope:tools

#1602 fix(foundations/icons): ensure that each svg url value corresponds to an associated id attr
  iconCompiler/generateIconsJS/iconsCommon.js
  iconCompiler/generateIconsJS/iconsModules.js
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/svelte/icons.js
Labels: :fire_extinguisher: fix

#1594 docs(configuration): add documentation about mozaic.config.js
  src/docs/GetStarted/Developers/Configuration/index.mdx
Labels: :books: docs
