Repository adeo/mozaic-design-system, pull requests merged in 2024-01, with the labels that each got.

#1524 feat(component/stepper): a11y - change colors for accessibility
  packages/tokens/build/android/colors.xml
  packages/tokens/build/css/_variables.scss
  packages/tokens/build/css/root.scss
  packages/tokens/build/ios/StyleDictionaryColor.m
  packages/tokens/build/ios/StyleDictionaryColor.swift
  packages/tokens/build/js/tokens.js
  packages/tokens/build/js/tokensObject.js
  packages/tokens/build/scss/_tokens.scss
  packages/tokens/properties/color/stepper.json
Labels: :rocket: feat, scope:component, scope:a11y

#1530 feat(icons): update destocking icon
  packages/icons/js/icons.common.js
  packages/icons/js/icons.js
  packages/icons/react/index.js
  packages/icons/svelte/PromiseDestocking24.svelte
  packages/icons/svelte/PromiseDestocking32.svelte
  packages/icons/svelte/PromiseDestocking48.svelte
  packages/icons/svelte/PromiseDestocking64.svelte
  packages/icons/svelte/icons.js
  packages/icons/svg/Product_Promise_Destocking_24px.svg
  packages/icons/svg/Product_Promise_Destocking_32px.svg
  packages/icons/svg/Product_Promise_Destocking_48px.svg
  packages/icons/svg/Product_Promise_Destocking_64px.svg
  packages/icons/vue/index.vue
  src/icons/SVG/24px/Product_Promise_Destocking_24px.svg
  src/icons/SVG/32px/Product_Promise_Destocking_32px.svg
  src/icons/SVG/48px/Product_Promise_Destocking_48px.svg
  src/icons/SVG/64px/Product_Promise_Destocking_64px.svg
Labels: :zap: design

#1533 ci(gha/workflows): release - update standard token permissions
  .github/workflows/release.yml
Labels: :soap: chore

#1532 fix(component/listbox): adjust label size
  packages/styles/components/_c.listbox.scss
Labels: :fire_extinguisher: fix, scope:component

#1535 fix(component/listbox): adjust behaviour of listbox (actions)
  packages/styles/components/_c.listbox.scss
Labels: :fire_extinguisher: fix, scope:component

#1538 docs(gatsby/seo): add Gatsby plugins to manage sitemap & canonical links
  gatsby-config.mjs
  package.json
  packages/gatsby-theme-styleguide/src/pages/{mdx.fields__slug}.js
  yarn.lock
Labels: :books: docs

#1540 docs(gatsby/seo): add robots.txt
  static/robots.txt
Labels: :books: docs
